### ISSUE TITLE
About the variable "num_index"

### ISSUE THREAD

**Issue by CleverFat** [ruanjue/wtdbg2#100]
Greetings!
When I was assembling seqs using wtdbg, I found that changing the value of "num_index" can reduce the memory usage of this software. However, after the program successfully terminated, I noticed that the TOT and N50 are much different from the original results. So I have two questions.
1. What does this variable do in wtdbg?
2. If I change this variable, will the result be correct?
Thank you!

**Comment by ruanjue** [comment]
RE 1: Please see the `--kbm-parts` release v2.4 (https://github.com/ruanjue/wtdbg2/releases/tag/v2.4). 
RE 2: Please keep it as itself, unless you know exactly what's it do.

**Comment by CleverFat** [comment]
Thanks for your time !
I only changed the value to 2 and did nothing else, but the TOT and N50 changed greatly, is that normal?

**Comment by ruanjue** [comment]
The assembly can be evaluated when existing reference sequences. If you doesn't know what is correct, please keep it as itself.

**Comment by CleverFat** [comment]
Alright, thank you !
