### ISSUE TITLE
split_seqs_2.pl needed

### ISSUE THREAD

**Issue by yzs981130** [ruanjue/wtdbg2#103]
Hi,

I experienced the same problem as https://github.com/ruanjue/wtdbg2/issues/7#issuecomment-392053647. I tried using `wtdbg --load-alignments reads.kbmap.all` and `wtdbg --load-alignments reads.kbmap.node1 --load-alignments reads.kbmap.node2 --load-alignments reads.kbmap.node1 ...` but neither worked. I wonder if there is anything wrong with my splitter.
As mentioned in [issue 7](https://github.com/ruanjue/wtdbg2/issues/7#issuecomment-392696390), there's fasta/fastq splitter tools called split_seqs_2.pl. So could you provide the script for me please? 

 Extremely appreciate of the help.

**Comment by ruanjue** [comment]
https://github.com/ruanjue/wtdbg2/blob/master/scripts/split_seqs_2.pl
