### ISSUE TITLE
get original fastq from wtdbg read names (S)

### ISSUE THREAD

**Issue by jakubjulian** [ruanjue/wtdbg2#104]
Hello,

Is it possible to get original fastq read name from wtdbg read name (S)?
E.g.
from ctg.lay file:
`S       S0000027464     +       6400    2816    TGAATCATCG...`
get fastq read id @... 

Thanks!

**Comment by ruanjue** [comment]
what version are you using? wtdbg-2.3 has an option `--keep-name`. Since wtdbg-2.4, program won't change read names unless using `--tidy-name`. 

It is hard to retrieve original read name from wtdg-2.3's lay file.
