### ISSUE TITLE
PB human genome coverage upper limit?

### ISSUE THREAD

**Issue by isantana-bio** [ruanjue/wtdbg2#105]
Is there a recommended upper limit for pacbio data, the examples you shared use up to 93x of high error reads and up to 28x of CCS. Should the presets below and any other defaults remain the same if the coverage is twice as much?

sequel (high error reads):preset3: -p 19 -AS 2 -s 0.05 -L 5000 
sequel ccs: preset4: -p 21 -k 0 -AS 4 -K 0.05 -s 0.5

Thanks!

**Comment by ruanjue** [comment]
wtdbg2 has two options `-g <gsize>` and `-X 50.0`, it will select 50X longest reads. If you want to use more in assembly please change `-X`. About the presets, you can increase `-p 19`  to `-p 21` if have much more data.

**Comment by isantana-bio** [comment]
Will test with those params. Thank you.
