### ISSUE TITLE
--kbm-parts might cause incomplete slicing on kbm->reads

### ISSUE THREAD

**Issue by eee4017** [ruanjue/wtdbg2#106]
Dear @ruanjue ,

I found something strange inside proc_alignments_core(), and I am not sure if this is a bug. In wtdbg.h:1385 inside proc_alignments_core(), we can see the slice size `ic` is ceiling of size/num_index, where `num_index` is pass down from `--kbm-parts`

```c
ic = (g->kbm->bins->size + g->num_index - 1) / g->num_index;
ie = 0;
```

In wtdbg.h:1453 we can find a for loop iterate through each slice. However, ie = ic*num_index in the last slice. Since `ic` is the ceiling of size/num_index, so this might exceed the original size. Furthermore,  `kbm->bins->buffer` is large enough so the exceeded index would not cause a segmentation fault but `g->kbm->bins->buffer[ie - 1].ridx` would give out 0, so we got `qb=qe=0` in the last slice. Finally, the `thread_mdbg_func` would not run if `qb=qe=0`.
```c
        in = g->corr_mode? 1 : g->num_index;
        ...
	for(ii=0;ii<in;ii++){
		ib = ie;
		ie = ib + ic;
		while(ie > 0 && ie < g->kbm->bins->size && g->kbm->bins->buffer[ie - 1].ridx == g->kbm->bins->buffer[ie].ridx) ie ++;
		if(g->corr_mode == 0){
			qb = 0;
			qe = ie? g->kbm->bins->buffer[ie - 1].ridx : 0;
		}
```

Please check if I have some misunderstanding on this part.

Thank and best regards,
Frank Lin

**Comment by ruanjue** [comment]
Thanks, it is a bug. See fixed https://github.com/ruanjue/wtdbg2/commit/08c2e7b34fc252bcfc2c127aae14ef4abc0422e7
