### ISSUE TITLE
Question: Recommended minimum coverage?

### ISSUE THREAD

**Issue by mjmillerlab** [ruanjue/wtdbg2#109]
Hi Jue:  I am trying to generate data for a couple of bird genomes (1 GB and 1.6 GB). Unfortunately, bird sequences are difficult to obtain on Oxford Nanopore...the pores clog. I can typically only get 1–3 GB per flow cell ($1000 per cell!). Can you recommend a minimum coverage that I should try to shoot for? 

Thanks!

**Comment by ruanjue** [comment]
30X ONT data can give an draft assembly, please use small kmer-size and `-R` in wtdbg2's assembly.

**Comment by desmodus1984** [comment]
Dear Jue,
Do you think using kmergenie will work to find a good k-mer size?
Thanks;'

**Comment by ruanjue** [comment]
I don't think so. The kmer-size in wtdbg2 is more about the sequencing type and genome size.
