### ISSUE TITLE
wtpoa-cns segmentation fault

### ISSUE THREAD

**Issue by kautto** [ruanjue/wtdbg2#112]
Hi @ruanjue,

I'm having trouble getting wtpoa-cns to run. I noticed there was a previous issue about it being unstable, but I built the newest release yesterday (2019-06-12) so it should have been fixed already.

Basically what happens is:

```
---
--
-- total memory      783896508.0 kB
-- available         778242732.0 kB
-- 96 cores
-- Starting program: /igm/projects/KAUTTO_Esko/apps/wtdbg2/wtpoa-cns -t 96 -i wtdbg2/NA12878.ctg.lay.gz -fo wtpoa-cns/NA12878.ctg.slf.fa
-- pid                     67346
-- date         Wed Jun 12 03:27:21 2019
--
1 contigs 1800 edges 0 bases/igm/apps/sge/sge-8.1.9_install/default/spool/rpl-igmsge04/job_scripts/1603825: line 33: 67346 Segmentation fault      (core dumped) ${wtpoa} -t ${threads} -i wtdbg2/NA12878.ctg.lay.gz -fo wtpoa-cns/NA12878.ctg.slf.fa
```

Retrying the same thing then gave me
```
--
-- total memory      783896508.0 kB
-- available         778502216.0 kB
-- 96 cores
-- Starting program: /igm/projects/KAUTTO_Esko/apps/wtdbg2/wtpoa-cns -t 96 -i wtdbg2/NA12878.ctg.lay.gz -fo wtpoa-cns/NA12878.ctg.slf.fa
-- pid                     42509
-- date         Wed Jun 12 10:50:04 2019
--
1 contigs 27900 edges 0 bases/igm/apps/sge/sge-8.1.9_install/default/spool/rpl-igmsge04/job_scripts/1605535: line 33: 42509 Segmentation fault      (core dumped) ${wtpoa} -t ${threads} -i wtdbg2/NA12878.ctg.lay.gz -fo wtpoa-cns/NA12878.ctg.slf.fa
```

So the number of edges seems to vary. However, I'm not sure what causes it to be stuck at "0 bases". If I try to run the command through an interactive shell (i.e. not a properly queued grid job), it does start calculating bases as well, e.g.
```
--
-- total memory      783896512.0 kB
-- available         692205004.0 kB
-- 96 cores
-- Starting program: /igm/projects/KAUTTO_Esko/apps/wtdbg2/wtpoa-cns -t 96 -i wtdbg2/NA12878.ctg.lay.gz -fo wtpoa-cns/NA12878.ctg.slf.fa
-- pid                     10945
-- date         Wed Jun 12 11:57:43 2019
--
3 contigs 72900 edges 71416919 bases
```

But this is on the exact same servers with the same data, so there's no real difference in the environment. Any ideas what could be causing it to segfault on that?

**Comment by ruanjue** [comment]
Please try the https://github.com/ruanjue/wtdbg2/commit/f86214f0cf66bb1087fe66a5038f0ed363184306, I just pushed. I am debuging it under valgrind to find the hidden bug, it may take days. If the segfault occur again, please let me know.

Thanks,
Jue

**Comment by kautto** [comment]
Hi Jue,

I tried to recompile from the newest commit but it still gives me the same error, even on a different AWS instance type:
```
--
-- total memory     2014445944.0 kB
-- available        2001723248.0 kB
-- 128 cores
-- Starting program: /dev/shm/wtdbg2/bin/wtpoa-cns -t 128 -i /disk1/wtdbg2/wtdbg2/NA12878.ctg.lay.gz -fo /disk1/wtdbg2/wtpoa-cns/NA12878.ctg.slf.fa
-- pid                     83058
-- date         Thu Jun 13 15:40:05 2019
--
1 contigs 27200 edges 0 bases/igm/apps/sge/sge-8.1.9_install/default/spool/rpl-igmsge05/job_scripts/1609294: line 42: 83058 Segmentation fault      (core dumped) /dev/shm/wtdbg2/bin/wtpoa-cns -t ${threads} -i ${workspace}/wtdbg2/NA12878.ctg.lay.gz -fo ${workspace}/wtpoa-cns/NA12878.ctg.slf.fa
```

The odd thing is that it always seems to crash at the first contig ("1 contigs"), with "0 bases", but running it interactively works fine... 

Thanks for looking into it!

Best,
Esko

**Comment by ruanjue** [comment]
If possible please cut the first 30000 edges from NA12878.ctg.lay.gz, and email it to me (ruanjue.big@qq.com) in gzip comressed format. I debuged wtpoa-cns on a small dataset under valgrind, but found nothing.

Best,
Jue

**Comment by evolgenomology** [comment]
Hi Jue,

I am having the same issue. Just to report it here.

Best

Philipp

**Comment by evolgenomology** [comment]
Short update. Switching back from today (25/6/19) to the f86214f0cf66bb1087fe66a5038f0ed363184306 commit it actually seems to work.

**Comment by ruanjue** [comment]
thanks.

**Comment by reachsagaya** [comment]
Hi @ruanjue
I'm having trouble getting wtpoa-cns to run.  Looks like the problem still exists.  As suggested in this chain I updated to the commit f86214f.  But still having problems with wtpoa-cns.  Below is the error I get:
[Error_wtbdg2.txt](https://github.com/ruanjue/wtdbg2/files/3379755/Error_wtbdg2.txt)
Please let me know if Iam missing something.
best
Sagaya

**Comment by ruanjue** [comment]
There were many changes after https://github.com/ruanjue/wtdbg2/commit/f86214f0cf66bb1087fe66a5038f0ed363184306, could you update to latest commit to make sure this bug is still live?

**Comment by reachsagaya** [comment]
Thanks @ruanjue.

I reinstalled with the latest commit and started my job yesterday and the job is still  running with no segmentation error this time. 
Thanks for you help and quick response.

best regards
Sagaya

**Comment by reachsagaya** [comment]
Hi @ruanjue,
Iam enclosing the error message for the run, Iam still having the segmentation issue.  
Here is my wtdbg2 install details:

ssagayaradj@barbera:/share/rwmwork/Sagaya/Packages/wtdbg2$ git log -1
commit c89e73aa92e5eee71737a4a0faf11445c72a341c
Author: ruanjue <ruanjue@gmail.com>
Date:   Thu Jul 11 16:17:40 2019 +0800

Could you please look into this issue again.

best regards
Sagaya

**Comment by reachsagaya** [comment]
Here is the error:
-- total memory      264121616.0 kB
-- available         224896412.0 kB
-- 64 cores
-- Starting program: wtpoa-cns -i /share/rwmwork/Sagaya/Assembly/ont/03-wtdbg2/wtdbg2-cns-try/lettuce_Pi251246.ctg.lay.gz -t 16 -fo lettuce_Pi251246.ctg.fa
-- pid                     63986
-- date         Fri Jul 12 17:42:24 2019
--

1 contigs 100 edges 0 bases
1 contigs 200 edges 0 bases
1 contigs 300 edges 0 bases
1 contigs 400 edges 0 bases
1 contigs 500 edges 0 bases
1 contigs 600 edges 0 bases
1 contigs 700 edges 0 bases
2 contigs 800 edges 2492468 bases
2 contigs 900 edges 2492468 bases
2 contigs 1000 edges 2492468 bases
2 contigs 1100 edges 2492468 bases
2 contigs 1200 edges 2492468 bases
2 contigs 1300 edges 2492468 bases
2 contigs 1400 edges 2492468 bases
2 contigs 1500 edges 2492468 bases
.......

376 contigs 213400 edges 631751954 bases/var/spool/slurmd/job1727428/slurm_script: line 35: 63986 Segmentation fault      wtpoa-cns -i /share/rwmwork/Sagaya/Assembly/ont/03-wtdbg2/wtdbg2-cns-try/lettuce_Pi251246.ctg.lay.gz -t 16 -fo lettuce_Pi251246.ctg.fa

best 
Sagaya

**Comment by ruanjue** [comment]
Could you truncate the lettuce_Pi251246.ctg.lay into a minimal size that can produce the seqgfault, and send me the lay file for debug, thanks.

**Comment by reachsagaya** [comment]
Hi @ruanjue,
After doing a run of adapter trimming I attempted to rerun the wtpoa-cns again.  This time it completed with no error.
Thanks for you quick response and you may close this issue.

Thanks
Sagaya
