### ISSUE TITLE
How does one pronounce wtdbg2, and is there a preferred more usable name?

### ISSUE THREAD

**Issue by oneillkza** [ruanjue/wtdbg2#116]
We're starting to work with the tool, but are having difficulty speaking about it. Spelling out the letters is cumbersome ("double-you-tee-dee-bee-gee-two"), requiring eight syllables. Trying to pronounce it as a word is even more difficult, as "wtdbg" is all consonants.

The name is also very hard to remember, since 't', 'd', 'b' and 'g' all sound similar, so the brain tends to mix their order up.

Is there a preferred alternate name for wtdbg2 that is easier to pronounce and remember?

**Comment by ruanjue** [comment]
Yes, `wtdbg` is difficult to be pronounced, which was also complained by many users. This word came from https://github.com/ruanjue/smartdenovo, you will find many programs like `wtxxx`. `wt` is shorted for WatchTower, representing how we deal with the long noisy reads.

I used to plan to change the name of `wtdbg` to `redbean` in futher version 3.x. `redbean` looks-XOR-sounds like `read binning`, which represents the key idea of wtdbg, using big kmers (k-bin) from reads to construct DBG, see doi:10.1101/530972.

I think you can call wtdbg `redbean` for convenient.

Jue

**Comment by oneillkza** [comment]
Thanks! Redbean it is!

WatchTower is a great name too.

Also thank you for writing the tool -- we're very excited to be using it!

**Comment by Psy-Fer** [comment]
We've been calling it "wobbly graph" in our lab. I guess I'll have to change that to redbean. Cheers.

**Comment by baraaorabi** [comment]
At some point I started calling it What-The-dgb 🤷‍♂️

**Comment by ruanjue** [comment]
^_^
