### ISSUE TITLE
Recommended parameters for coverage titration?

### ISSUE THREAD

**Issue by adigenova** [ruanjue/wtdbg2#117]
Hi, 
I'm trying to determine the coverage peak of wtdbg2 on a human genome. I'm using ONT data at the following coverage:

10X, 15X, 20X, 25X, 30X, 35X, 40X, 45X, 50X 

What parameters should I tune to maximize performance at each coverage?.

Thank in advance.
Best
Alex

**Comment by ruanjue** [comment]
I am afraid <20X won't work. If you are assembling low coverage data, please also try realignment option `-R` to get more accurate alignments. Please note that wtdbg2 has an default option `-X50` to select 50X reads. 

Best,
Jue

**Comment by adigenova** [comment]
Great!!! thanks.
