### ISSUE TITLE
truncated output, with no errors in log

### ISSUE THREAD

**Issue by swomics** [ruanjue/wtdbg2#118]
Hi,

I downloaded the latest version with git clone (Version: 2.4.1 (20190603)) and had no problems compiling. However when I ran the first step the output appeared truncated and no errors had been indicated in the program log. I used a colleagues older version, which so far seems to have run with no problems (Version: 2.4 (20190312))

Output files from Version: 2.4.1 (20190603):
dbg2.1.dot.gz
dbg2.1.nodes
dbg2.1.reads
dbg2.2.dot.gz
dbg2.alignments.gz
dbg2.binkmer
dbg2.closed_bins
dbg2.clps
dbg2.events
dbg2.kmerdep

Output files from Version: 2.4 (20190312):
dbg3.1.dot.gz
dbg3.1.nodes
dbg3.1.reads
dbg3.2.dot.gz
dbg3.3.dot.gz
dbg3.alignments.gz
dbg3.binkmer
dbg3.closed_bins
dbg3.clps
dbg3.ctg.dot.gz
dbg3.ctg.lay.gz
dbg3.events
dbg3.frg.dot.gz
dbg3.frg.nodes
dbg3.kmerdep
dbg3.raw.fa

**Comment by ruanjue** [comment]
Could you paste the log message just start from aligning, like this
```txt
** PROC_STAT(0) **: real 12.441 sec, user 60.050 sec, sys 6.820 sec, maxrss 1235264.0 kB, maxvsize 2619364.0 kB
[Mon Jun 17 17:50:36 2019] Done
13727 reads|total hits 141255
...
```

**Comment by swomics** [comment]
Sure, no problem 

> ** PROC_STAT(0) **: real 1212.565 sec, user 32861.680 sec, sys 1496.460 sec, maxrss 143411248.0 kB, maxvsize 188739692.0 kB
[Sun Jun 16 00:09:27 2019] Done
1115003 reads|total hits 637435622
** PROC_STAT(0) **: real 31996.932 sec, user 1856597.060 sec, sys 29821.320 sec, maxrss 173516960.0 kB, maxvsize 234157660.0 kB
[Sun Jun 16 08:42:31 2019] sorting rdhits ... Done
[Sun Jun 16 08:42:40 2019] clipping ... 15.00% bases
[Sun Jun 16 08:42:43 2019] generating regs ... 3227759326
[Sun Jun 16 08:47:37 2019] sorting regs ...  Done
[Sun Jun 16 08:49:18 2019] generating intervals ...  43100040 intervals
[Sun Jun 16 08:49:47 2019] selecting important intervals from 43100040 intervals
[Sun Jun 16 09:01:37 2019] Intervals: kept 2403709, discarded 40696331
** PROC_STAT(0) **: real 33142.716 sec, user 1861639.000 sec, sys 30703.800 sec, maxrss 173516960.0 kB, maxvsize 245222452.0 kB
[Sun Jun 16 09:01:37 2019] Done, 2403709 nodes
[Sun Jun 16 09:01:37 2019] output "dbg2.1.nodes". Done.
[Sun Jun 16 09:01:52 2019] median node depth = 6
[Sun Jun 16 09:01:52 2019] masked 5437 high coverage nodes (>200 or <3)
[Sun Jun 16 09:01:56 2019] masked 50128 repeat-like nodes by local subgraph analysis
[Sun Jun 16 09:01:56 2019] generating edges
[Sun Jun 16 09:04:15 2019] Done, 72424897 edges
[Sun Jun 16 09:04:15 2019] output "dbg2.1.reads". Done.
[Sun Jun 16 09:04:36 2019] output "dbg2.1.dot.gz". Done.
[Sun Jun 16 09:06:01 2019] graph clean
[Sun Jun 16 09:06:05 2019] rescued 106849 low cov edges
[Sun Jun 16 09:06:09 2019] deleted 2562 binary edges
[Sun Jun 16 09:06:10 2019] deleted 505982 isolated nodes
[Sun Jun 16 09:06:17 2019] cut 122740 transitive edges
[Sun Jun 16 09:06:18 2019] output "dbg2.2.dot.gz". Done.

**Comment by ruanjue** [comment]
I am afraid it was cause by recently introduced function `rescue_high_cov_edges_graph`.  I will fix it and notice you. Thanks for bug reporting.

**Comment by ruanjue** [comment]
Please have a try with https://github.com/ruanjue/wtdbg2/commit/6f76ff1fac7bb8b45f81a11859283fd2bda45046 .

**Comment by swomics** [comment]
Hi,

All the output files seem to be present and the output log looks complete. Thanks for the quick fix!

dbg4.1.dot.gz
dbg4.1.nodes
dbg4.1.reads
dbg4.2.dot.gz
dbg4.3.dot.gz
dbg4.alignments.gz
dbg4.binkmer
dbg4.closed_bins
dbg4.clps
dbg4.ctg.dot.gz
dbg4.ctg.lay.gz
dbg4.events
dbg4.frg.dot.gz
dbg4.frg.nodes
dbg4.kmerdep
