### ISSUE TITLE
关于使用其他软件纠错后数据配合此软件组装的效果

### ISSUE THREAD

**Issue by pengbo233** [ruanjue/wtdbg2#119]
您好！
          请问下，我使用necat的纠错后的数据用于此软件组装，为什么得到的基因组大小会特别小，比如原本wtdgb2直接组装，结果是2G，但是使用necat纠错后的数据组装，只有600Mb，这个可能是什么原因引起的？纠错后的数据量有50X

祝好！

**Comment by ruanjue** [comment]
纠错后的数据需要使用 -x ccs来组装。如果这样依然得到的基因组偏小的话，可能是纠错工具没有正确区分相似区域的序列。

**Comment by yilunhuangyue** [comment]
您好，请问您是更建议使用raw data还是corrected进行组装呢？在我测试的几个数据中，使用corrected data得到的N50明显小于raw data得到的N50，还是说针对corrected data除了-x ccs以外还有特定参数？. 纠错使用的是canu correct。
非常感谢您的帮助~

**Comment by ruanjue** [comment]
不同的基因组和测序数据质量会影响组装，我们推荐的参数都是在一般情况下得到的。你需要根据实际情况判断。
