### ISSUE TITLE
clustering overlapped reads based on their alignments

### ISSUE THREAD

**Issue by tangerzhang** [ruanjue/wtdbg2#12]
Hi Jue,
I am not sure it is suitable post my question here. 
I am assembling a super-large genome (20Gb). Currently i have finished the alignment using paralleled kbm-1.2.8 method (https://github.com/ruanjue/wtdbg-1.2.8/issues/7) and would like to cluster overlapped reads to multiple small blocks for separate assembly as loading all of the alignment files in wtdbg-1.28 will require too much memory (which I do not have).
Therefore, my question is that how can I extract and cluster overlaped reads into different blocks? Any suggestion?
Thanks!

**Comment by ruanjue** [comment]
Hi, 

To reduce the RAM requirement, please have a try --tidy-reads <10000>, will drop all reads < 10kb, should work even with --load-alignments. 

WTDBG-1.2.8 loads reads and alignments into RAM which takes much of memory. It is more convenient to optimize this step than distributed assembly graph. 

Anyway, I will leave this issue unsolved, and will give a response after I update the consensus module of wtdbg.

Jue

**Comment by ruanjue** [comment]
Hi, `--aln-bestn 0 --no-read-clip` to parse alignment directly, have a try!
