### ISSUE TITLE
Parameters for 1G repetitive and heterozygous diploid genome

### ISSUE THREAD

**Issue by swomics** [ruanjue/wtdbg2#120]
Hi again,

I thought I'd open up a seperate issue for this to avoid confusion ( https://github.com/ruanjue/wtdbg2/issues/118#issue-456839866). I could use some advice about altering redbean parameters for my genome as the default "sq" parameters used with the older v2.4 install have generated sub-optimal results. The version with the new fix is still running, I will reply on the original issue when it's finished.

Our sample is outbred and assembly with Falcon-Unzip yields an assembly roughly 2x the expected size (indicating haplotype divergences >5%). I was hoping that redbean might offer an interesting contrast to this due to the way de-brujn graphs collapse heterozygosity, however the redbean assembly is >2x expected size and has a dramatically reduced N50 (nearly a factor of 7 reduction). I've got roughly 75x coverage of Sequel reads N50 ~35Kbp, so the underlying data is fairly good.

Is it possible that the sample is too outbred for the algorithm to successfully merge the divergent haplotypes? It looks like I could tweak -S -s and -A -e, but I'm not entirely sure how to balance the different considerations of heterozygosity, repeats etc...

Here is the assembly log:

[Sun Jun 16 14:53:57 2019] loading reads
2087082 reads
[Sun Jun 16 15:03:49 2019] filtering from 2087082 reads (>=5000 bp), 60280503599 bp. Try selecting 46700000000 bp
[Sun Jun 16 15:03:53 2019] Done, 1115004 reads (>=5000 bp), 46700021760 bp, 182421864 bins
** PROC_STAT(0) **: real 596.030 sec, user 1203.470 sec, sys 478.620 sec, maxrss 17045296.0 kB, maxvsize 19000276.0 kB
[Sun Jun 16 15:03:53 2019] Set --edge-cov to 3
KEY PARAMETERS: -k 15 -p 0 -K 1000.049988 -A -S 2.000000 -s 0.050000 -g 934000000 -X 50.000000 -e 3 -L 5000
[Sun Jun 16 15:03:53 2019] generating nodes, 60 threads
[Sun Jun 16 15:03:53 2019] indexing bins[0,182421864] (46699997184 bp), 60 threads
[Sun Jun 16 15:03:54 2019] - scanning kmers (K15P0S2.00) from 182421864 bins
182421864 bins
********************** Kmer Frequency **********************
                                                                                                    
           |||||||                                                                                  
          ||||||||||                                                                                
         |||||||||||||                                                                              
         |||||||||||||||                                                                            
        ||||||||||||||||||                                                                          
        ||||||||||||||||||||                                                                        
       |||||||||||||||||||||||                                                                      
       ||||||||||||||||||||||||||                                                                   
       |||||||||||||||||||||||||||||                                                                
      |||||||||||||||||||||||||||||||||                                                             
      |||||||||||||||||||||||||||||||||||||                                                         
      ||||||||||||||||||||||||||||||||||||||||||                                                    
     |||||||||||||||||||||||||||||||||||||||||||||||||                                              
     |||||||||||||||||||||||||||||||||||||||||||||||||||||||||                                      
     ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||                             
    |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||               
    ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
   |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
**********************     1 - 201    **********************
Quatiles:
   10%   20%   30%   40%   50%   60%   70%   80%   90%   95%
    30    48    73   112   179   305   588  1478  5475 17652
# If the kmer distribution is not good, please kill me and adjust -k, -p, and -K
# Cannot get a good distribution anyway, should adjust -S -s, also -A -e in assembly
** PROC_STAT(0) **: real 881.186 sec, user 10783.620 sec, sys 2114.090 sec, maxrss 22867532.0 kB, maxvsize 91063664.0 kB
[Sun Jun 16 15:08:38 2019] - high frequency kmer depth is set to 18042
[Sun Jun 16 15:08:39 2019] - Total kmers = 268426741
[Sun Jun 16 15:08:39 2019] - average kmer depth = 76
[Sun Jun 16 15:08:39 2019] - 25091 low frequency kmers (<2)
[Sun Jun 16 15:08:39 2019] - 23759 high frequency kmers (>18042)
[Sun Jun 16 15:08:39 2019] - indexing 268377891 kmers, 20469898792 instances (at most)
182421864 bins
[Sun Jun 16 15:22:20 2019] - indexed  268377891 kmers, 20456205392 instances
[Sun Jun 16 15:22:22 2019] - masked 180884 bins as closed
[Sun Jun 16 15:22:22 2019] - sorting
** PROC_STAT(0) **: real 1725.290 sec, user 37856.380 sec, sys 7673.240 sec, maxrss 143473576.0 kB, maxvsize 214937200.0 kB
[Sun Jun 16 15:22:42 2019] Done
1115003 reads|total hits 637435622
** PROC_STAT(0) **: real 36008.627 sec, user 1893639.890 sec, sys 83562.530 sec, maxrss 174279116.0 kB, maxvsize 242172872.0 kB
[Mon Jun 17 00:54:05 2019] sorting rdhits ... Done
[Mon Jun 17 00:54:13 2019] clipping ... 15.00% bases
[Mon Jun 17 00:54:16 2019] generating regs ... 3230137330
[Mon Jun 17 01:01:46 2019] sorting regs ...  Done
[Mon Jun 17 01:03:08 2019] generating intervals ...  43103700 intervals
[Mon Jun 17 01:03:34 2019] selecting important intervals from 43103700 intervals
[Mon Jun 17 01:15:42 2019] Intervals: kept 2335826, discarded 40767874
** PROC_STAT(0) **: real 37305.393 sec, user 1899647.920 sec, sys 85802.700 sec, maxrss 174279116.0 kB, maxvsize 255131652.0 kB
[Mon Jun 17 01:15:42 2019] Done, 2335826 nodes
[Mon Jun 17 01:15:42 2019] output "dbg3.1.nodes". Done.
[Mon Jun 17 01:15:56 2019] median node depth = 6
[Mon Jun 17 01:15:56 2019] masked 5185 high coverage nodes (>200 or <3)
[Mon Jun 17 01:15:59 2019] masked 49146 repeat-like nodes by local subgraph analysis
[Mon Jun 17 01:15:59 2019] generating edges
[Mon Jun 17 01:18:28 2019] Done, 67891634 edges
[Mon Jun 17 01:18:28 2019] output "dbg3.1.reads". Done.
[Mon Jun 17 01:18:42 2019] output "dbg3.1.dot.gz". Done.
[Mon Jun 17 01:19:57 2019] graph clean
[Mon Jun 17 01:20:00 2019] rescued 50998 low cov edges
[Mon Jun 17 01:20:03 2019] deleted 3512 binary edges
[Mon Jun 17 01:20:03 2019] deleted 431879 isolated nodes
[Mon Jun 17 01:20:10 2019] cut 508397 transitive edges
[Mon Jun 17 01:20:11 2019] output "dbg3.2.dot.gz". Done.
[Mon Jun 17 01:25:54 2019] 147414 bubbles; 97221 tips; 382 yarns;
[Mon Jun 17 01:25:54 2019] deleted 109193 isolated nodes
[Mon Jun 17 01:25:54 2019] output "dbg3.3.dot.gz". Done.
[Mon Jun 17 01:26:00 2019] cut 94700 branching nodes
[Mon Jun 17 01:26:00 2019] deleted 18211 isolated nodes
[Mon Jun 17 01:26:00 2019] building unitigs
[Mon Jun 17 01:26:02 2019] TOT 2294809600, CNT 87005, AVG 26376, MAX 630528, N50 51456, L50 12762, N90 13312, L90 44939, Min 768
[Mon Jun 17 01:26:02 2019] output "dbg3.frg.nodes". Done.
[Mon Jun 17 01:26:03 2019] generating links
[Mon Jun 17 01:26:03 2019] generated 144844 links
[Mon Jun 17 01:26:03 2019] output "dbg3.frg.dot.gz". Done.
[Mon Jun 17 01:26:04 2019] rescue 0 weak links
[Mon Jun 17 01:26:04 2019] deleted 661 binary links
[Mon Jun 17 01:26:04 2019] cut 33925 transitive links
[Mon Jun 17 01:26:04 2019] remove 4683 boomerangs
[Mon Jun 17 01:26:05 2019] detached 12416 repeat-associated paths
[Mon Jun 17 01:26:05 2019] remove 76120 weak branches
[Mon Jun 17 01:26:05 2019] cut 7136 tips
[Mon Jun 17 01:26:05 2019] pop 788 bubbles
[Mon Jun 17 01:26:05 2019] cut 1092 tips
[Mon Jun 17 01:26:05 2019] output "dbg3.ctg.dot.gz". Done.
[Mon Jun 17 01:26:05 2019] building contigs
[Mon Jun 17 01:26:05 2019] searched 68551 contigs
[Mon Jun 17 01:26:05 2019] Estimated: TOT 2456563456, CNT 49687, AVG 49441, MAX 1869312, N50 83712, L50 7282, N90 22272, L90 29466, Min 5120
[Mon Jun 17 01:29:11 2019] output 49687 contigs
[Mon Jun 17 01:29:23 2019] Program Done
** PROC_STAT(TOTAL) **: real 38126.245 sec, user 1906244.870 sec, sys 86535.520 sec, maxrss 174279116.0 kB, maxvsize 255131652.0 kB

**Comment by ruanjue** [comment]
Please turn `-R` on, also try to tune --aln-dovetail. I guess most of the reads alignments were not dovetailed.

**Comment by swomics** [comment]
Ok I will try adding -R and increasing --aln-dovetail, thanks for the quick responses!

**Comment by swomics** [comment]
These parameters are only having a moderate impact. 
wtdbg2 -R --aln-dovetail 10240:
Estimated: TOT 2139396864, CNT 41159, AVG 51979, MAX 4534016, N50 92416, L50 4679, N90 22272, L90 23522, Min 5120

Is it recommended to continue increasing --aln-dovetail, or are there other parameters that should be tuned?

**Comment by ruanjue** [comment]
Try to turn off it by setting --aln-dovetail -1.
