### ISSUE TITLE
Parameters setting problem

### ISSUE THREAD

**Issue by huanfa** [ruanjue/wtdbg2#121]
Hi
Ruanjue
I found a problem when I assembling with 100x  corrected reads using canu, numerous reads will be missed loading using default -X [50]. The script I used as following:

- $wtdbg2  -t ${Threads} -x corrected -g 2.5g -L 5000  -i ${RawReads}  -fo ${output}

Do you have any suggestion about how to assembly the  2.5g genomeSize with 100x corrected reads?
Thanks in advance!

**Comment by ruanjue** [comment]
`-X 100` will selecting 100X reads from input.

```sh
wtdbg2 -t 64 -x ccs -g 2.5g -X 100 -i reads.fa -fo dbg
```

**Comment by huanfa** [comment]
Is -L 5000 necessary for assembling the pacbio corrected reads? 
And another issue I have met is that  reads will miss loading when  '' /'' within read name.
![QQ截图20190618222013](https://user-images.githubusercontent.com/21327136/59692326-428dc080-9217-11e9-9f77-149408ec8f64.png)

**Comment by ruanjue** [comment]
I my experience, shorter pacbio reads contributed little to wtdbg's assembly.

Please see `wtdbg2 --help` , selecting longest subread.
```txt
 -L <int>    Choose the longest subread and drop reads shorter than <int> (5000 recommended for PacBio) [0]
             Negative integer indicate tidying read names too, e.g. -5000.

```
