### ISSUE TITLE
-R is not working (Enable re-alignment)

### ISSUE THREAD

**Issue by bitcometz** [ruanjue/wtdbg2#123]
Hello,

I used kbm2 to do the alignments of reads and then I run wtdbg2 with the alignment as inputs.
During the wtdbg2 steps, I try to run it **with** and **without** "-R(Enable realignment mode)". However, it makes no difference when selecting or not selecting this parameter.

Does "R" parameter not work for running wtdbg2(just building the layout results) alone?

Best

**Comment by ruanjue** [comment]
`wtdbg2 -R` affacts reads aligning. If you want to use it in kbm2, please see `kbm2 -z 15`.
