### ISSUE TITLE
Estimation of the operation time

### ISSUE THREAD

**Issue by jakubjulian** [ruanjue/wtdbg2#125]
Hi! Is it possible to estimate the duration of the program? I am interested in estimating the time the ctg.lay.gz graph was created. I have a large input data. Thanks!

**Comment by ruanjue** [comment]
I am not sure. If you find the file size doesn't increase for a long time, there must be some bug.

**Comment by jakubjulian** [comment]
Ok, thank you. This would be a useful option - how to predict how long it will take.

**Comment by jakubjulian** [comment]
Maybe you know how long it will take to produce ctg.lay.gz file from ~60 gigabases input fastq?
I have available 500Gb RAM and 88 threads

**Comment by ruanjue** [comment]
Shold be very fast, at most 30 mins.

**Comment by jakubjulian** [comment]
INFO: almost 60 gigabases input fastq took ~300 mins, but with "-x ont" parameter (88 threads).

**Comment by ruanjue** [comment]
Did you mean total wall-clock time or time for output <prefix>.ctg.lay.gz file?

**Comment by jakubjulian** [comment]
Total time from the beginning (reading reads took 9 mins) to end of standard wtdbg2 run.
The longest part took 4,5h.

**Comment by ruanjue** [comment]
Total time is ok.
