### ISSUE TITLE
Reg: Invalid kmer size

### ISSUE THREAD

**Issue by harish0201** [ruanjue/wtdbg2#129]
Hi!

I'm running the following parameter series on one of my highly repeat and heterozygous genome projects.

I'm using the release tagged as ` f460eee` wherein I'm encountering this error.

`-p 19 -k 6 -AS 2`

` -- Invalid kmer size 6+19=25 > 23 in main -- wtdbg.c:669 --`

Which is weird given that the readme specifies that k+p<=25 which I believe is. Or can they be individually 25 but the sum should be 23?

Can you clarify this a bit?

**Comment by ruanjue** [comment]
Hi,

The max kmer size is 23, defined in kbm.h:43. Sorry for that I haven't updated it in help document.

Jue
