### ISSUE TITLE
Splitting FIXP kmers, assertion issues and parameter queries

### ISSUE THREAD

**Issue by harish0201** [ruanjue/wtdbg2#130]
Hi!

I'm still assembling the genome on a parameter sweep as per our last discussion. 

I'm getting this error, for the parameter: `-g 2.5g -X 60 -p 17 -k 6 -L 5000 -AS 4 -o run1 --aln-dovetail -1`

I used the dovetail metric from another thread on the issues a while back and wanted to try this out.

`0|0wtdbg2: kbm.h:511: split_FIXP_kmers_kbm: Assertion `rs[0]->n_head > 0' failed.`

Is there a particular reason that this happens?

The genome is around 2.5g with an estimated 80% repeat content and about 2% heterozygosity.

I have over 190Gb data in reads over 5Kb in length on Sequel. I did try the default -x sq set and the assembly is just a bit less than 2Gb which the reason I'm doing the sweep. 

This is the attached kmer histogram on defaults. Can you suggest some parameters to tweak?

The parameters passed are: `-p 21 -AS 2 -g 2.5g -L 5000`

![image](https://user-images.githubusercontent.com/9093815/60751547-8e40b800-9fd4-11e9-92fd-cde6a47e838e.png)

**Comment by ruanjue** [comment]
I noted that kbm.h:511 in latest commit is not this assert, please update your progam. If it occurs again, I will debug it.

**Comment by harish0201** [comment]
Sure, thanks for the help, do you have any particular commit that I have to use?

**Comment by ruanjue** [comment]
Try add -R, otherwise I have no idea.

**Comment by harish0201** [comment]
Ok. I'll try again with the latest release.
