### ISSUE TITLE
Feature request: only accept input reads in table

### ISSUE THREAD

**Issue by andreaswallberg** [ruanjue/wtdbg2#131]
Dear @ruanjue ,

First, thanks for a great assembly program!

I wonder if you could consider implementing a command line option to read in a simple text file with "accepted" read header names, before reading in the FASTQ/FASTA sequence data. The option would create a temporary read list in memory and any read seen in the sequence data that is not in this list is simply discarded from the particular analysis. If the option is not used, then all reads are accepted.

This would effectively make it possible to create arbitrary and flexible hard read filters to explore various input into the assembler, without having to create new FASTQ sequence files, similar to how the "-L" length filter works today.

Cheers!

**Comment by ruanjue** [comment]
https://github.com/ruanjue/wtdbg2/commit/c89e73aa92e5eee71737a4a0faf11445c72a341c
--rdname-filter <file_name>
Please note that it works in reverse manner. wtdbg2 filters reads in the ID_file. Have a try.

**Comment by andreaswallberg** [comment]
Hi again!

The option --rdname-filter to exclude reads works pretty great! Many thanks!

For anyone looking to try it out, the option takes a text file with only the header names (i.e. you should not have the leading "@" character or the runid=... info), like these:

0f70c95a-551e-456e-bec3-64ce1a1c1c6e
1062f08e-4606-4ed9-b691-a2b9df0f5cf4
10f16ed4-f445-4f8f-af9a-c7e115537c33

For a use case where only a small subset of reads (e.g. mitochondrial or metagenomic sequences identified some other way) is meant to be assembled from a large sequence pool, it would still be useful to have a "--rdname-includeonly" option to get only accepted reads from a list. Such a list would be easy for the user to expand by appending new reads at the end before rerunning the assembler. After having seen the all reads in the list, the program could close the reading of the fastq data early.

I realize you have many more important things on your plate @ruanjue than this particular request though.

**Comment by ruanjue** [comment]
https://github.com/ruanjue/wtdbg2/commit/8caea801223c2a11111d095af4aeec1eec78f1bd

Please note that I haven't test this new option on my PC. If anything wrong please tell me.

Best,
Jue

**Comment by andreaswallberg** [comment]
Sorry for the delay testing this but "--rdname-includeonly" works great in my tests. Many thanks!
