### ISSUE TITLE
slurmstepd: error: Detected 6 oom-kill event(s) in step 640467.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.

### ISSUE THREAD

**Issue by biowackysci** [ruanjue/wtdbg2#132]
Hello, 
I trying to assemble a 2.8 g genome with both pacbio and ont sequences. It worked with SMARTDENOVO. 
So I am giving the sequences with this assembler.
The parameters i have used is 
wtdbg2 -x ont -g 2.8g -t 100 -p 19 -AS 2 -s 0.05 -L 5000 -i /group/pasture/Saila/all_assembly_reads.fastq -fo all_assembly_reads
wtpoa-cns -t 100 -i all_assembly_reads.ctg.lay.gz -fo all_assembly_reads.ctg.fa

But i get the following the error all the time 
* PROC_STAT(0) **: real 1875.949 sec, user 12270.650 sec, sys 498.480 sec, maxrss 54355568.0 kB, maxvsize 65499240.0 kB
[Mon Jul 15 13:12:43 2019] - high frequency kmer depth is set to 18426
[Mon Jul 15 13:12:43 2019] - Total kmers = 387394068
[Mon Jul 15 13:12:43 2019] - average kmer depth = 109
[Mon Jul 15 13:12:43 2019] - 1937 low frequency kmers (<2)
[Mon Jul 15 13:12:43 2019] - 47672 high frequency kmers (>18426)
[Mon Jul 15 13:12:43 2019] - indexing 387344459 kmers, 42563881870 instances (at most)

0
200000/var/spool/slurm/d/job640467/slurm_script: line 14: 382949 Killed                  wtdbg2 -x ont -g 2.8g -t 64 -p 19 -AS 2 -s 0.05 -L 5000 -i /group/pasture/Saila/all_assembly_reads.fastq -fo all_assembly_reads
--
-- total memory      790725612.0 kB
-- available         756010428.0 kB
-- 48 cores
-- Starting program: wtpoa-cns -t 64 -i all_assembly_reads.ctg.lay.gz -fo all_assembly_reads.ctg.fa
-- pid                    388382
-- date         Mon Jul 15 13:12:56 2019
--
Cannot open file for read: all_assembly_reads.ctg.lay.gz
No such file or directory
slurmstepd: error: Detected 6 oom-kill event(s) in step 640467.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.

Is there something I should be doing? Can you please help me out here ?
Thanks 
S

**Comment by ruanjue** [comment]
I am afraid you need to apply more memory for wtdbg2.

**Comment by biowackysci** [comment]
Thanks for the reply. 
I am at the moment trying with 500g memory. I will update you with what happens with 500 Memory. i can go up to 150 T. So i am adjusting the memory as and when the run fails with out of memory.

Thanks
S

**Comment by biowackysci** [comment]
Hello again,
My assembly is running at the moment. I was wondering if there is anyway I can get the stats of the assembly ? As in do you recommend any script for that ?

Many thanks
S

**Comment by ruanjue** [comment]
There is a seq_n50.pl under scripts/. Have fun.


 
---Original---

**Comment by biowackysci** [comment]
Thanks for that  :)
I have an entirely different question. Don't know if I should opena different thread or state it here.

The question is I have a couple of fasta reads (Illumina Miseq reads) that I want to add to the the fastq reads for the assembly. is there a way I could add fasta reads along with the fastq reads for the assembly ?

Thanks
S

**Comment by ruanjue** [comment]
It is a good question, I prefer to have another issue to discuss it. Redbean has its solution, but I get few feedback on `wtpoa-cns -x sam-sr`.
