### ISSUE TITLE
help for Segmentation fault

### ISSUE THREAD

**Issue by bitcometz** [ruanjue/wtdbg2#133]
hello,
**I run with wtdbg2(version:2.4.1):
./wtdbg2 -A --node-drop 0.25 --node-len 1536 --node-max 200 -s 0.05 -e 3 -i ./filt.alg.fasta --load-alignments ./kbm.filt.alg -t 10 -fo ./sample --rescue-low-cov-edges --no-read-length-sort --aln-dovetail 4608 2> run.wtdbg.log

and the log informations:**

-- total memory      131861660.0 kB
-- available         120249328.0 kB
-- 32 cores
-- Starting program: ./wtdbg2 -A --node-drop 0.25 --node-len 1536 --node-max 200 -s 0.05 -e 3 -i ./filt.alg.fasta --load-alignments ./kbm.filt.alg -t 10 -fo ./sample --rescue-low-cov-edges --no-read-length-sort --aln-dovetail -1
-- pid                     30150
-- date         Fri Jul 19 02:02:54 2019
--
[Fri Jul 19 02:02:54 2019] loading reads
2572652 reads
[Fri Jul 19 02:05:38 2019] Done, 2572652 reads (>=0 bp), 36750993270 bp, 142274140 bins
** PROC_STAT(0) **: real 163.726 sec, user 90.700 sec, sys 23.400 sec, maxrss 10835060.0 kB, maxvsize 12500740.0 kB
KEY PARAMETERS: -k 0 -p 21 -K 1000.049988 -A -S 4.000000 -s 0.050000 -g 0 -X 50.000000 -e 3 -L 0
[Fri Jul 19 02:05:38 2019] loading alignments from "./kbm.filt.alg"
131242626 lines, 104416961 hits
** PROC_STAT(0) **: real 309.231 sec, user 238.560 sec, sys 38.930 sec, maxrss 15083200.0 kB, maxvsize 17993256.0 kB
[Fri Jul 19 02:08:03 2019] sorting rdhits ... Done
[Fri Jul 19 02:08:07 2019] clipping ... 7.59% bases
[Fri Jul 19 02:08:12 2019] generating regs ... 548453771
[Fri Jul 19 02:09:25 2019] sorting regs ...  Done
[Fri Jul 19 02:09:36 2019] generating intervals ...  21388716 intervals
[Fri Jul 19 02:09:40 2019] selecting important intervals from 21388716 intervals
[Fri Jul 19 02:11:21 2019] Intervals: kept 1016896, discarded 20371820
** PROC_STAT(0) **: real 507.095 sec, user 632.580 sec, sys 205.110 sec, maxrss 23814388.0 kB, maxvsize 60030164.0 kB
[Fri Jul 19 02:11:21 2019] Done, 1016896 nodes
[Fri Jul 19 02:11:21 2019] output "./sample.1.nodes". Done.
[Fri Jul 19 02:11:26 2019] median node depth = 9
[Fri Jul 19 02:11:26 2019] masked 293 high coverage nodes (>200 or <3)
[Fri Jul 19 02:11:27 2019] masked 53157 repeat-like nodes by local subgraph analysis
[Fri Jul 19 02:11:27 2019] generating edges
[Fri Jul 19 02:11:36 2019] Done, 4004099 edges
[Fri Jul 19 02:11:36 2019] output "./sample.1.reads". Done.
[Fri Jul 19 02:11:41 2019] output "./sample.1.dot.gz". Done.
[Fri Jul 19 02:11:47 2019] graph clean
[Fri Jul 19 02:11:48 2019] rescued 40228 low cov edges
[Fri Jul 19 02:11:48 2019] deleted 200 binary edges
[Fri Jul 19 02:11:48 2019] deleted 151615 isolated nodes
[Fri Jul 19 02:11:49 2019] cut 43285 transitive edges
[Fri Jul 19 02:11:49 2019] output "./sample.2.dot.gz". Done.

Then it report "Segmentation fault" and generate 41G core file.
So how can I handle with this problem？Should I send the core file to you?

**and some core informations:
gdb wtdbg2 core.30150**

GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-114.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from wtdbg2...done.
[New LWP 30150]
[New LWP 30151]

warning: .dynamic section for "/lib64/libz.so.1" is not at the expected address (wrong library or version mismatch?)
Warning: couldn't activate thread debugging using libthread_db: Cannot find new threads: generic error

warning: File "/usr/lib64/libthread_db-1.0.so" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load:/usr/bin/mono-gdb.py:/usr/lib/golang/src/runtime/runtime-gdb.py".
To enable execution of this file add
	add-auto-load-safe-path /usr/lib64/libthread_db-1.0.so
line to your configuration file "/home/user/.gdbinit".
To completely disable this security protection add
	set auto-load safe-path /
line to your configuration file "/home/user/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"

warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
Warning: couldn't activate thread debugging using libthread_db: Cannot find new threads: generic error

warning: File "/usr/lib64/libthread_db-1.0.so" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load:/usr/bin/mono-gdb.py:/usr/lib/golang/src/runtime/runtime-gdb.py".

warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
Core was generated by `wtdbg2 -A --node-drop'.
Program terminated with signal 11, Segmentation fault.
#0  0x0000000000405fe1 in rescue_high_cov_edges_graph (max_step=<optimized out>, g=<optimized out>) at wtdbg-graph.h:1319
1319					e = ref_edgev(g->edges, ref_edgerefv(g->erefs, fidx[2])->idx);
Missing separate debuginfos, use: debuginfo-install glibc-2.17-260.el7.x86_64 zlib-1.2.7-18.el7.x86_64
(gdb) where
#0  0x0000000000405fe1 in rescue_high_cov_edges_graph (max_step=<optimized out>, g=<optimized out>) at wtdbg-graph.h:1319
#1  main (argc=<optimized out>, argv=<optimized out>) at wtdbg.c:1058

Best

**Comment by ruanjue** [comment]
This block of codes had been modified since 2.4.1, please update to lastest commit, I remember I had fix a bug in this block. If it still occurs, Iwill debug it again.

**Comment by bitcometz** [comment]
Thanks, I will try the latest version!

Best

**Comment by bitcometz** [comment]
Thanks, it is ok with the latest version!

Best
