### ISSUE TITLE
是否支持集群

### ISSUE THREAD

**Issue by focusjava** [ruanjue/wtdbg2#135]
您的这款工具是否支持集群操作？例如SGE集群，Falcon和Canu都支持SGE集群计算，希望得到您的回复信息，谢谢！

**Comment by ruanjue** [comment]
Redbean没有开发集群版本，我们的目标是使用单个节点一天内完成人类基因组组装，所以没有花费精力来开发多节点并行版本。

**Comment by focusjava** [comment]
非常感谢收到您的回复，另外问一下，您说的使用单个节点一天内完成人类基因组组装，所需要的服务器配置资源是怎样的？CPU，内存，硬盘存储？谢谢！

**Comment by ruanjue** [comment]
RAM >= 256 GB
DISK >= 1 TB
CPU >= 48 cores
