### ISSUE TITLE
Assembly autopolyploid genome

### ISSUE THREAD

**Issue by fantasticair** [ruanjue/wtdbg2#138]
Hello,
WTDBG software can assemble homologous polyploid genome to get contig, if you can, how to set the parameters?
Best wishes

**Comment by ruanjue** [comment]
Not good at it. You are possible to get a merged haploid assembly. Try use `-k 16 -p 0 -S 2 -l 4086 -m 400 -S 0.1`.

**Comment by fantasticair** [comment]
Thank you for your quick reply.
