### ISSUE TITLE
Haploid genome assembly - weird k-mer distribution

### ISSUE THREAD

**Issue by aviantask** [ruanjue/wtdbg2#139]
![Screen Shot 2019-08-14 at 1 08 33 AM](https://user-images.githubusercontent.com/2449792/63005147-cedfec80-be30-11e9-828e-d04e10722ec1.png)

Hi,

We have 100x reads from PacBio Sequel for a gametophyte genome (approx size 500Mb) and is essentially a haploid genome. Upon running wtdbg2 with default settings, we get the k-mer distribution attached. 

What would be your advice on tuning the parameters for this assembly? Also as an aside, 100% of the reads were clipped when a student ran this and he got no output result.

**Comment by ruanjue** [comment]
Have a try with `-x preset3` to increase the k-mer size.

**Comment by aviantask** [comment]
Thanks, we got it solved.
