### ISSUE TITLE
Is RAM an issue to build contig layout file after alignments are built?

### ISSUE THREAD

**Issue by vinayciba** [ruanjue/wtdbg2#140]
Hi,
I am running wtdbg2 on sequel data to generate assembly of a highly repetitive genome which is 2.5 Gb length. The run stopped after building alignments file. Attached the logs, in brief. I have two queries. 
First, Is insufficient RAM, the issue? If yes, which parameter should i tweak for another run? 
Second, Can i restart the run in same folder to generate .ctg.lay.gz file, as alignment file is already there? If yes, how to do it?
Thank you in advance.
[issue_wtdbg2.txt](https://github.com/ruanjue/wtdbg2/files/3511759/issue_wtdbg2.txt)

**Comment by ruanjue** [comment]
Out of memory. Restart the job by appending `--load-alignments` and `--load-clips`.
PS. you were using an old version of wtdbg2, upgrate to wtdbg-2.5 to get better results.

**Comment by vinayciba** [comment]
Hai, Thank you for sharing additional arguments. I have updated to wtdbg2.5. The run did actually start from the same folder with these arguments. But, the RAM issue persisted. I have only 512 GB of RAM. Is there any way I could limit RAM usage by wtdbg?

**Comment by ruanjue** [comment]
1, try decrease the seq coverage cutoff from `-X70` to `-X50` or smaller.  
2, try use `-x rs` instead of `-x sq`, because kmer coverage is very high, you can use a larger kmer-size.
