### ISSUE TITLE
Reg: Assembly of a tetraploid genome

### ISSUE THREAD

**Issue by harish0201** [ruanjue/wtdbg2#142]
Hi Rue,

We are planning to start assembling a tetraploid (auto) genome in a day or two and I was hoping that you might have some suggestions regarding the same.

Are there any specific tuning that I might need to look for?

**Comment by ruanjue** [comment]
I guess you will get a assembly of hyploid genome size.

**Comment by harish0201** [comment]
Thank you, surprisingly I got a Diploid genome after assembling.
