### ISSUE TITLE
Disk space

### ISSUE THREAD

**Issue by ctxchris** [ruanjue/wtdbg2#143]
Hi,

how much disk space does one need to perform an assembly similar to the axolotl project?

Thanks,
Chris

**Comment by ruanjue** [comment]
1TB is safe to run wtdbg2 + wtpoa-cns. But if you want to polish the assemblies using minimap2, the BAM files might be about 1TB. So, 2 TB will safe to invoke wtdbg2.pl.

**Comment by ctxchris** [comment]
That's great, much less than running Falcon or Canu.

Thx,
Chris
