### ISSUE TITLE
reproducibility of assemblies: 3 different results running the same dataset 3 times

### ISSUE THREAD

**Issue by michieitel** [ruanjue/wtdbg2#145]
Hi!

I just encountered that when running wtdbg2 three times with the same settings on the same ONT dataset I get different results. Is that expected with the used algorithm? Is that because of some heuristics involved?

I was running wtdbg2 3x each on three datasets (all reads >1kb, all >5kb, all >10kb).
The expected coverage of the three datasets were:

1kb+: ~110x
5kb+: ~80
10kb+: ~40x

I used these commands:

```
# 1kb+ repetitions
wtdbg2 -x ont -g 80m -t 40 -fo WTDBG2_1kb_run1 -i reads_porechopped.1kb.fasta.gz 2> WTDBG2_1kb_run1.log
wtdbg2 -x ont -g 80m -t 40 -fo WTDBG2_1kb_run2 -i reads_porechopped.1kb.fasta.gz 2> WTDBG2_1kb_run2.log
wtdbg2 -x ont -g 80m -t 40 -fo WTDBG2_1kb_run3 -i reads_porechopped.1kb.fasta.gz 2> WTDBG2_1kb_run3.log


# 5kb+ repetitions
wtdbg2 -x ont -g 80m -t 40 -fo WTDBG2_5kb_run1 -i reads_porechopped.5kb.fasta.gz 2> WTDBG2_5kb_run1.log
wtdbg2 -x ont -g 80m -t 40 -fo WTDBG2_5kb_run2 -i reads_porechopped.5kb.fasta.gz 2> WTDBG2_5kb_run2.log
wtdbg2 -x ont -g 80m -t 40 -fo WTDBG2_5kb_run3 -i reads_porechopped.5kb.fasta.gz 2> WTDBG2_5kb_run3.log


# 10kb+ repetitions
wtdbg2 -x ont -g 80m -t 40 -fo WTDBG2_10kb_run1 -i reads_porechopped.10kb.fasta.gz 2> WTDBG2_10kb_run1.log
wtdbg2 -x ont -g 80m -t 40 -fo WTDBG2_10kb_run2 -i reads_porechopped.10kb.fasta.gz 2> WTDBG2_10kb_run2.log
wtdbg2 -x ont -g 80m -t 40 -fo WTDBG2_10kb_run3 -i reads_porechopped.10kb.fasta.gz 2> WTDBG2_10kb_run3.log
```

The stats of the raw (unpolished) assemblies are as follows:
![WTDBG2_stats](https://user-images.githubusercontent.com/12069446/66206136-7e0da700-e6af-11e9-8dba-828d75b13632.png)

As you can see the stats are generally comparable between the runs for each dataset, but just not identical.

How one can be sure one gets the best possible assembly and how can one ensure reproducibility?

Thanks
Michael

**Comment by ruanjue** [comment]
It was mostly caused by multiple-threads in alignments, wtdbg2 is NOT granted to produce identical alignments. About best assembly, I think it make no sense to say which is better when having very little difference in contigs's length, they are identical or nearly identical.
