### ISSUE TITLE
polishing using short reads. bwa mem error: [E::bwa_idx_load_from_disk] 

### ISSUE THREAD

**Issue by astulaaa** [ruanjue/wtdbg2#146]
I have been following the pipeline steps and until polishing with short reads everything worked fine (no errors, proper size and format outputs)
but starting polishing with short reads bwa shows error  [E::bwa_idx_load_from_disk] fail to locate the index files. Am I dealing with bwa version incompatibility or indexing step is skipped in the pipeline? I still get the .srp.fa output but I wonder did the polishing actually happened?

Thanks

**Comment by ruanjue** [comment]
I skipped a `bwa index` step, please run it before short reads mapping.

**Comment by astulaaa** [comment]
Should I use bwa index with '-t 31' option (for human) ?
