### ISSUE TITLE
Missing zlib -- fatal error of 'make'

### ISSUE THREAD

**Issue by YongZhou2019** [ruanjue/wtdbg2#152]
Hello,
can you help me with the 'make' in ubuntu? Thanks
best.

![image](https://user-images.githubusercontent.com/54231229/68843262-da191180-06d8-11ea-91a6-3fca1ced4d5a.png)

**Comment by ruanjue** [comment]
Need to install zlib package.

**Comment by YongZhou2019** [comment]
Yes! 
It works now! 
Thank you so much!
