### ISSUE TITLE
statistics of assembly results

### ISSUE THREAD

**Issue by yangxiaofeill** [ruanjue/wtdbg2#154]
Hi Dr. Ruan,
      I have tried your assembler wtdbg2, and get the `raw.fa` file.  However, I cannot find the statistic results of the assembly. Could you tell me how to get it? 

Best

**Comment by ruanjue** [comment]
Run https://github.com/ruanjue/wtdbg2/blob/master/scripts/seq_n50.pl on the raw.fa

**Comment by yangxiaofeill** [comment]
Thanks

**Comment by cement-head** [comment]
Not quite sure how to interpret the output of your script - why are there TWO numbers associated with each N## score?


$ ./seq_n50.pl input.fa
Total: 6200959339
Count: 82732
Average: 74952.37
Median: 22459
N00: 5280931	1
N10: 1469795	309
N20: 1026989	823
N30: 737002	1540
N40: 535766	2528
N50: 369759	3921
N60: 224078	6063
N70: 101664	10211
N80: 51089	19151
N90: 26812	35933
N100: 1387	82732

**Comment by ruanjue** [comment]
The first num is N50, the second is L50.
