### ISSUE TITLE
Restarting WTDBG2 after computer reboot

### ISSUE THREAD

**Issue by cabbagesofdoom** [ruanjue/wtdbg2#155]
Hi. I had a WTDBG2 (v2.4) assembly running for over a week when the sys admin had to reboot the server. Is there a way to restart the assembly and get it to pick up where it was, or do I need to re-start it from scratch?

The files it has made so far are:

    tiger.wtdbg2v2.events  tiger.wtdbg2v2.kmerdep  tiger.wtdbg2v2.binkmer  tiger.wtdbg2v2.closed_bins  tiger.wtdbg2v2.alignments.gz

I think `tiger.wtdbg2v2.alignments.gz` was still being updated at the time of the reboot.

**Comment by ruanjue** [comment]
If alignemnts was not done, you need to run it from the begining.

**Comment by cabbagesofdoom** [comment]
Thanks.
