### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by MaartjeRZ** [ruanjue/wtdbg2#156]
Hello, 

I was running wtdbg2 (version 2.5) but at a certain point the job failed, having an ExitCode 11. It seemed that wtdbg2 is having an segmentation fault:

[Tue Nov 26 08:52:47 2019] wtpoa-cns[43884]: segfault at 2ab748567e9d ip 0000000000418713 sp 00002aaae7325dc0 error 4 in wtpoa-cns[400000+26000]

The problem occurs sporadically. Is this something you are aware of? And do you know if there will be a fix for this in the next release?

Thank you in advance,
Maartje

**Comment by ruanjue** [comment]
I cannot guess what's happened. If you can split the .lay file, and locate the problematic small part, then send the part to me, I will debug it.

**Comment by MaartjeRZ** [comment]
Dear Ruanjue,

Attached a lay file where the problem occurred.

**Comment by MaartjeRZ** [comment]
Dear Ruanjue,

Attached the lay file (compressed) where the problem occurs. Good to know that the problem occurred sporadically. To speed up our analysis pipeline we already split the lay file into smaller lay files.

[ctg40.zip](https://github.com/ruanjue/wtdbg2/files/3910374/ctg40.zip)

Thank you for your help. Let me know if you need more information.

Kind regards,

Maartje

**Comment by ruanjue** [comment]
Thanks for the material. I saw very large edge length, it may be the causation. But on my computer, wtpoa-cns successed to generate `1 contigs 13 edges 514601 bases`. I was using the lastest commit https://github.com/ruanjue/wtdbg2/commit/6329a5f0e2635c0b3a2c6db6a9115700089ca5a7.

**Comment by MaartjeRZ** [comment]
Hi Ruanjue,

Did you try many times? Because we also had moments it finished succesfully.But unfortunately not always..

Kind regards,
Maartje

**Comment by ruanjue** [comment]
I tried many times after your last post, but cannot repeat the segfault. Please give me the lay file when you find it again.

Jue

**Comment by MaartjeRZ** [comment]
okay thank you for trying!

**Comment by shri1984** [comment]
Hey, 
Thanks for wtdbg2. 
I was trying to use wtdbg2 in cluster. I have access to a node with 64 CPUs (120 cores) and 6000GB RAM. I am running pacbio sequences ( 2 sequel cells of data) of an organism with an estimated genome size of approximately 10g. Installation of wtdbg2 is part of slurm job script using GCC. It loads the reads and performs some tasks. Then I am getting core dumped error (see below). I tried to run two sequel cells (.fa.gz format) together like below, I got into "core dumped" issue. Then I tried to run one cell at a time, the same issue continues. Then decided to subsample the data into files based on read length. No use either. It´s also strange that wtdbg2 don't use all the memory, but still complains about the "core dumped". 
Then I thought I can reduce the coverage and used -X option help to reduce the memory load? 
the command used: ( HPC, CentOS-based cluster single node 120 cores, 6000GB
./wtdbg2 -x sq -g 10g -i sq1.fa.gz -i sq2.fa.gz -t 110 -fo sq1.sq2


here is the error message: 
 -- Out of memory, try to allocate 150323855360 bytes, old size 256, old addr 0x199b030 in encap_list -- mem_share.h:219 --
./wtdbg2[0x4025b4]
./wtdbg2[0x41255b]
./wtdbg2[0x43d93b]
./wtdbg2[0x44b791]
./wtdbg2[0x455bd2]
./wtdbg2[0x40423f]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x2b00f9b9d495]
./wtdbg2[0x409293]
/var/spool/slurmd/job420705/slurm_script: line 56: 45125 Aborted                 (core dumped) ./wtdbg2 -x sq -g 10g -i sq1.fa.gz -i sq2.fa.gz -X 30 -L 10000 -t 110 -fo sq1-sq2
 Thanks in advance, 
SB

**Comment by ruanjue** [comment]
Wtdbg2 wanted to alloc 150G memory, but failed. Please send me more log message.

**Comment by shri1984** [comment]
Thank you for quick response. 

Here s the full log file. 

-- total memory     6340818424.0 kB
-- available        6297151932.0 kB
-- 128 cores
-- Starting program: ./wtdbg2 -x sq -g 10g -i sq1.fa.gz -i sq2.fa.gz -X 30 -L 10000 -t 110 -fo sq1-sq2
-- pid                    133745
-- date         Fri Dec 13 07:57:27 2019
--
[Fri Dec 13 07:57:27 2019] loading reads
^M0^M10000^M20000^M30000^M40000^M50000^M60000^M70000^M80000^M90000^M100000^M110000^M120000^M130000^M140000^M150000^M160000^M170000^M180000^M190000^M200000^M210000^M220000^M230000^M240000^M250000^M260000^$
[Fri Dec 13 08:18:18 2019] Done, 5810864 reads (>=10000 bp), 154752115850 bp, 601611819 bins
** PROC_STAT(0) **: real 1251.365 sec, user 2314.000 sec, sys 282.990 sec, maxrss 45410276.0 kB, maxvsize 51233272.0 kB
[Fri Dec 13 08:18:18 2019] Set --edge-cov to 2
KEY PARAMETERS: -k 0 -p 19 -K 1000.049988 -A -S 2.000000 -s 0.050000 -g 10000000000 -X 30.000000 -e 2 -L 10000
[Fri Dec 13 08:18:18 2019] generating nodes, 110 threads
[Fri Dec 13 08:18:19 2019] indexing bins[(0,601611819)/601611819] (154012625664/154012625664 bp), 110 threads
[Fri Dec 13 08:18:20 2019] - scanning kmers (K0P19S2.00) from 601611819 bins
^M0^M1100000^M2200000^M3300000^M4400000^M5500000^M6600000^M7700000^M8800000^M9900000^M11000000^M12100000^M13200000^M14300000^M15400000^M16500000^M17600000^M18700000^M19800000^M20900000^M22000000^M2310000$
********************** Kmer Frequency **********************

            |||||||||
           |||||||||||||
          |||||||||||||||||
         |||||||||||||||||||||
        |||||||||||||||||||||||||
        ||||||||||||||||||||||||||||
       ||||||||||||||||||||||||||||||||||
       ||||||||||||||||||||||||||||||||||||||||
      ||||||||||||||||||||||||||||||||||||||||||||||||
      |||||||||||||||||||||||||||||||||||||||||||||||||||||||
      |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
     ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
     |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
    |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
    ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
    ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
   |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
   |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
**********************     1 - 201    **********************
Quatiles:
   10%   20%   30%   40%   50%   60%   70%   80%   90%   95%
    38    68   108   164   259   469  1109  3183 14271 38209
** PROC_STAT(0) **: real 1632.079 sec, user 34141.780 sec, sys 1197.740 sec, maxrss 54636208.0 kB, maxvsize 67227948.0 kB
[Fri Dec 13 08:24:39 2019] - high frequency kmer depth is set to 39333
 -- Out of memory, try to allocate 154618822656 bytes, old size 256, old addr 0xb5a030 in encap_list -- mem_share.h:219 --
./wtdbg2[0x4025b4]
./wtdbg2[0x41255b]
./wtdbg2[0x43d93b]
./wtdbg2[0x44b791]
./wtdbg2[0x455bd2]
./wtdbg2[0x40423f]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x2accc000e495]
./wtdbg2[0x409293]
/var/spool/slurmd/job420956/slurm_script: line 56: 133745 Aborted                 (core dumped) ./wtdbg2 -x sq -g 10g -i sq1.fa.gz -i sq2.fa.gz -X 30 -L 10000 -t 110 -fo sq1-sq2

Task and CPU usage stats:
       JobID    JobName  AllocCPUS   NTasks     MinCPU MinCPUTask     AveCPU    Elapsed ExitCode
------------ ---------- ---------- -------- ---------- ---------- ---------- ---------- --------
420956           sharkG         64                                             00:32:43      6:0
420956.batch	  batch         64        1   09:53:22          0   09:53:22   00:32:43      6:0
420956.exte+     extern         64        1   00:00:00          0   00:00:00   00:32:45      0:0


Memory usage stats:
       JobID     MaxRSS MaxRSSTask     AveRSS MaxPages   MaxPagesTask   AvePages
------------ ---------- ---------- ---------- -------- -------------- ----------
420956
420956.batch  54646556K          0  54646556K        0              0          0
420956.exte+	   129K          0	 129K        0              0          0


Disk usage stats:
       JobID  MaxDiskRead MaxDiskReadTask    AveDiskRead MaxDiskWrite MaxDiskWriteTask   AveDiskWrite
------------ ------------ --------------- -------------- ------------ ---------------- --------------
420956
420956.batch   117361.48M               0     117361.48M    58677.60M                0      58677.60M
420956.exte+        0.00M               0          0.00M            0                0              0

**Comment by ruanjue** [comment]
Please check your available RAM, there was no enough RAM to allocate 150GB.

**Comment by ruanjue** [comment]
Hi, I modified the code, it might resolve your problem, have a look at https://github.com/ruanjue/wtdbg2/commit/31dd60332dd4979009bfc3047b407c30a67ee3d9 .

**Comment by shri1984** [comment]
Hi, 
Thanks. 
[slurm-426917.txt](https://github.com/ruanjue/wtdbg2/files/4012326/slurm-426917.txt)
Now I downloaded the latest wtdbg2 from Github. It does not look like helping. getting same error. please see log. This is the best machine I can get for analysis.

**Comment by ruanjue** [comment]
I modified it again at https://github.com/ruanjue/wtdbg2/commit/df0fe8c5d77922e5d84b6a1dea79e9e0f774c242 , please make sure you are using this commit.

**Comment by shri1984** [comment]
Hey, 
This latest commit too did not work. I made sure I have the latest wtdbg.h file before I compiled wtdbg.  I got the same error as in the previous log I have uploaded.

**Comment by ruanjue** [comment]
Then, try to set a larger value for `-l `, it will filter shorter alignments.
