### ISSUE TITLE
PacBio HiFi read assembly

### ISSUE THREAD

**Issue by chklopp** [ruanjue/wtdbg2#157]
Hi,

What parameter values should I use to assemble PacBio HiFi reads (expected 1% random errors) with wtdbg2 and which parameters should I tweak to separate genome phases in different contigs?

Cheers

**Comment by ruanjue** [comment]
Hi,

`wtdbg2 -x ccs` is for HiFi reads. I don't think wtdbg2 will work well on phasing contigs, please increases `-s` if you want to try. 

Jue
