### ISSUE TITLE
ONT & PacBioSII data

### ISSUE THREAD

**Issue by cement-head** [ruanjue/wtdbg2#159]
This is more of a question before I start than an issue.  Is it possible to take ONT long reads and combine them with PacBioSII data and feed them into wtdbg2? Or is this a bad idea?

**Comment by ruanjue** [comment]
I don't think the combination will produce better result than either of RSII or ONT data. I used to test the mix, but cannot find good parameter.

**Comment by cement-head** [comment]
Okay, thanks!
