### ISSUE TITLE
Racon and Pilon

### ISSUE THREAD

**Issue by mictadlo** [ruanjue/wtdbg2#160]
Hi,
After finishing the assembly should I run [Racon](https://github.com/isovic/racon) and then [Pilon](https://github.com/broadinstitute/pilon)?

Thank you in advance,

Michal

**Comment by ruanjue** [comment]
Two options, the first is polishing consensus sequences with wtpoa-cns again and again using short reads, the second is running racon or pilon.

**Comment by mictadlo** [comment]
Which approach do you think is better?

**Comment by ruanjue** [comment]
I prefer to use wtpoa-cns, but very little comparsion.

**Comment by mictadlo** [comment]
How many rounds of `wtpoa-cns` do you do? 
Does `wtpoa-cns` replace aslo `Pilon` for you?

**Comment by ruanjue** [comment]
After generate raw contigs from wtpoa-cns, one round of long reads is ok, then two or three rounds of short reads.
