### ISSUE TITLE
Can not make correctly

### ISSUE THREAD

**Issue by Yixiangzhang1996** [ruanjue/wtdbg2#161]
Hello：
A little embarrassed, I am a newbie in genome assembly. When I run Manuel, I get the following error in the Make step. I searched on google and found that the user with root privileges used: sudo apt install zlib1g-dev, but I didn't, I don't know how to solve it.
Looking forward to your reply.

`(base) [wtdbg2]$ make
gcc -g3 -W -Wall -Wno-unused-but-set-variable -O4 -DVERSION="2.5" -DRELEASE="20190621" -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -mpopcnt -msse4.2 -o kbm2 kbm.c ksw.c -lm -lrt -lpthread -lz
In file included from filereader.h:34:0,
                 from kbm.h:26,
                 from kbm.c:20:
pgzf.h:23:18: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
                  ^
compilation terminated.
`

**Comment by ruanjue** [comment]
Without root, you also can install zlib for yourself, please search more about how to install library without root.
