### ISSUE TITLE
[E::sam_parse1] no SQ lines present in the header

### ISSUE THREAD

**Issue by mictadlo** [ruanjue/wtdbg2#163]
Hi,
I ran wtdbg2 in the following way and ran into the below 2 Errors:

```
conda activate wtdbg2
# assemble long reads
wtdbg2 -x $2 -g $1 -i $4 -t 16 -fo dbg

# derive consensus
wtpoa-cns -t 16 -i dbg.ctg.lay.gz -fo dbg.raw.fa

# polish consensus, not necessary if you want to polish the assemblies using other tools
minimap2 -t 16 -ax $3 -r2k dbg.raw.fa $4 | samtools sort -@4 > dbg.bam
samtools view -F0x900 dbg.bam | wtpoa-cns -t 16 -d dbg.raw.fa -i - -fo dbg.cns.fa

# Addtional polishment using short reads
bwa mem -t 16 dbg.cns.fa ../R1.fq.gz ../R2.fq.gz | samtools sort -O SAM | wtpoa-cns -t 16 -x sam-sr -d dbg.cns.fa -i - -fo dbg.srp.fa
```

```
** PROC_STAT(TOTAL) **: real 72365.665 sec, user 1107668.430 sec, sys 4749.400 sec, maxrss 185999288.0 kB, maxvsize 198328032.0 kB
---
--
-- total memory     6043942728.0 kB
-- available        5955220020.0 kB
-- 384 cores
-- Starting program: wtpoa-cns -t 16 -i dbg.ctg.lay.gz -fo dbg.raw.fa
-- pid                     18774
-- date         Fri Dec 13 14:19:55 2019
--
177065 contigs 2792237 edges 5384236890 bases
** PROC_STAT(TOTAL) **: real 63411.359 sec, user 1006045.420 sec, sys 5649.370 sec, maxrss 4333960.0 kB, maxvsize 6006444.0 kB
---
[M::mm_idx_gen::80.196*1.70] collected minimizers
[M::mm_idx_gen::83.085*2.17] sorted minimizers
[WARNING] For a multi-part index, no @SQ lines will be outputted. Please use --split-prefix.
[M::main::83.105*2.17] loaded/built the index for 51295 target sequence(s)
[M::mm_mapopt_update::86.992*2.12] mid_occ = 298
[M::mm_idx_stat] kmer size: 19; skip: 10; is_hpc: 1; #seq: 51295
[M::mm_idx_stat::89.211*2.09] distinct minimizers: 144625325 (46.80% are singletons); average occurrences: 3.437; average spacing: 8.090
[E::sam_parse1] no SQ lines present in the header
samtools sort: truncated file. Aborting
[ERROR] failed to write the results
[main_samview] fail to read the header from "dbg.bam".
--
-- total memory     6043942728.0 kB
-- available        6022152740.0 kB
-- 384 cores
-- Starting program: wtpoa-cns -t 16 -d dbg.raw.fa -i - -fo dbg.cns.fa
-- pid                    249718
-- date         Sat Dec 14 08:01:02 2019
--
177065 contigs 1975866 edges 5384096282 bases
** PROC_STAT(TOTAL) **: real 6549.678 sec, user 102378.030 sec, sys 342.720 sec, maxrss 6029200.0 kB, maxvsize 7311764.0 kB
---
--
-- total memory     6043942728.0 kB
-- available        6034982508.0 kB
-- 384 cores
-- Starting program: wtpoa-cns -t 16 -x sam-sr -d dbg.cns.fa -i - -fo dbg.srp.fa
-- pid                    313087
-- date         Sat Dec 14 09:50:12 2019
--
[E::bwa_idx_load_from_disk] fail to locate the index files
samtools sort: failed to read header from "-"
177065 contigs 19600987 edges 5383440136 bases
** PROC_STAT(TOTAL) **: real 1866.751 sec, user 24387.860 sec, sys 284.520 sec, maxrss 7486364.0 kB, maxvsize 9615812.0 kB
---
```

What did I miss?

Thank you in advance

**Comment by ruanjue** [comment]
Please add `bwa index dbg.cns.fa` before bwa-mem.

https://github.com/ruanjue/wtdbg2#getting-started

**Comment by xiekunwhy** [comment]
> Please add `bwa index dbg.cns.fa` before bwa-mem.
> 
> https://github.com/ruanjue/wtdbg2#getting-started

Hi,

I think you did't get the point of this problem, it happened not because of bwa.
It was happen when pipe the minimap2 result to samtools sort. I got the same error when I map ont reads to ctg.fa using the command line below.
`minimap2 -t16 -ax map-ont -r2k hci.ctg.fa hci_ont.filt.fa | /home/bam_processing/samtools/v1.8_with_libdeflate/samtools-1.8/samtools sort -@4 > hci_dbg.bam`

[WARNING] For a multi-part index, no @SQ lines will be outputted. Please use --split-prefix.
[M::main::87.711*0.44] loaded/built the index for 34425 target sequence(s)
[M::mm_mapopt_update::91.859*0.46] mid_occ = 800
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 34425
[M::mm_idx_stat::94.601*0.48] distinct minimizers: 130136947 (38.50% are singletons); average occurrences: 5.827; average spacing: 5.310
[E::sam_parse1] missing SAM header
[W::sam_read1] Parse error at line 2
samtools sort: truncated file. Aborting

How to deal with this problem?

Best,
Kun

**Comment by ruanjue** [comment]
Please have a look at `minimap2 -I <NUM>`, use a larger value than 4G, say 64G when you have enough memory.

**Comment by xiekunwhy** [comment]
It not worked, I got the same error when I set -I to 20G
`minimap2 -t16 -I 20G -ax map-ont -r2k hci.ctg.mmi hci.filt.fa | samtools sort -@4 > hci_dbg.bam`
[WARNING] For a multi-part index, no @SQ lines will be outputted. Please use --split-prefix.
[M::main::21.521*1.00] loaded/built the index for 34425 target sequence(s)
[M::mm_mapopt_update::25.592*1.00] mid_occ = 800
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 34425
[M::mm_idx_stat::28.263*1.00] distinct minimizers: 130136947 (38.50% are singletons); average occurrences: 5.827; average spacing: 5.310
[E::sam_parse1] missing SAM header
[W::sam_read1] Parse error at line 2
samtools sort: truncated file. Aborting

**Comment by xiekunwhy** [comment]
It worked well well I change ">" to "-o", the complete command line is
`minimap2 -t16 -I 20G -ax map-ont -r2k hci.ctg.mmi hci.filt.fa | samtools sort -@4 -o hci_dbg.bam`
Thank you!
Best,
Kun

**Comment by ruanjue** [comment]
I don't know the difference, @lh3 . Thanks for sharing.
