### ISSUE TITLE
how to use wtdbg-dot2gfa.pl

### ISSUE THREAD

**Issue by csuzhang** [ruanjue/wtdbg2#167]
Hi 
 How to use wtdbg-dot2gfa.pl, and any recommend parameter for wtdbg-dot2gfa.pl

Thanks

**Comment by ruanjue** [comment]
No parameter, run it as `gzip -dc dbg.3.dot.gz | wtdbg-dot2gfa.pl >dbg.3.gfa`.

**Comment by ptranvan** [comment]
hi @ruanjue,

I also need the GFA for hi-c scaffolding. What the difference and which one should I use between:

```
wtdgb2.3.dot.gz  
wtdgb2.ctg.dot.gz
wtdgb2.frg.dot.gz
```

**Comment by ruanjue** [comment]
I guess you are needing the `.ctg.dot`. `.frg.dot` is for unitigs, the unitigs are more accurate than contigs. `.ctg.dot` is the final graph comes from unitigs.
