### ISSUE TITLE
Conceptual Question about wtdbg2

### ISSUE THREAD

**Issue by chocotwig** [ruanjue/wtdbg2#168]
Hi,

I have a conceptual question about wtdbg2.

I have sequenced a genome with long reads, but low coverage (<10x).

Say I have several thousand genomic reads, and I know that 100 of these reads represent a given genomic region, and from minimap2 mapping results (or any other available alignment tool) , I know that the best mappings for each of these 100 reads are ONLY to one of these other 100 reads, and not to any reads outside these 100. (although there may be other mappings for these reads outside the 100, these are as good).

Then, if I were to input a PAF file for only these 100 reads into wtdbg2, would the resulting contig(s) for this 100-read genomic region be the same, as compared to the scenario where I would input the all the several thousand reads into wtdbg2? Or would I get two different contigs for this region in either scenario? (Assuming that real coverage drops to 0 on either side of the genomic region of interest).

This would help deciding whether to pre-filter our reads before inputting them into wtdbg2. Thanks.

**Comment by ruanjue** [comment]
If the special genomic region is unique, two contigs would be nearly the same. Otherwise, repeat may break the contigs from whole reads assembly, but no influence on only 100 reads assembly.

BTW, there is a script called `sam2kbm.pl` to convert SAM format alignments into KBM alignments, but I am not sure whether it still works for wtdbg-2.,5.

**Comment by chocotwig** [comment]
And supposing there is a large repeat region at the very end of the unique genomic region, then wtdbg2 simply break the assembly there, when all reads are inputted? Or is it likely to force through some sort of assembly of that repeat region?

Thanks a lot!

**Comment by ruanjue** [comment]
wtdbg2 try to untangle the repeat using long reads. If cannot infer a good solution of the branches of a repeat, it will leave it, thus will break contigs sequence at there. Nearly all graph-based assemblers follow this way.
