### ISSUE TITLE
Extremely Low Coverage Assembly

### ISSUE THREAD

**Issue by chocotwig** [ruanjue/wtdbg2#170]
Hi,

Im trying to get at the rough structure of a genomic region. My coverage of this region is extremely low (3x). I simply want to see how my reads stack up with one another, I don't need high-confidence assembly. 
What would be a good way to stitch together these very low coverage reads? Even if there is a 2-read contig, that is sufficient. My reads are quite long (N50 35kb), using nanopore.

I have been using:
-x ont -t 16 -S 1 -l 1000 --edge-min 1 --rescue-low-cov-edges -R --no-read-clip --aln-dovetail 

Thanks!

**Comment by ruanjue** [comment]
there looks a missing
```sh
-x ont -t 16 -S 1 -l 1000 --edge-min 1 --rescue-low-cov-edges -R --no-read-clip --aln-dovetail -1
```

**Comment by chocotwig** [comment]
Okay! Do you recommend any changes to this?

Thanks,
Niraj

**Comment by ruanjue** [comment]
It looks ok.
