### ISSUE TITLE
-edge-min 1: does it report all edges? or just best-overlap edges?

### ISSUE THREAD

**Issue by chocotwig** [ruanjue/wtdbg2#173]
Hi, if wtdbg2 is attempting to untangle a repeat as in the attached picture, where there is no single long read that spans the region from any node on the left to any node on the right, would wtdbg2 simply give up on assembly? 
(edge-min 1 settings)
As the picture seeks to show, read 2 overlaps most with Read 1 and read 3, and less so with reads 4 and 5. Would wtdbg2 report all possible contigs, i.e. 1-2-3, 1-2-5, 4-2-3 and 5-2-5? Or would it only select the path with the maximum overlap (i.e. 1-2-3?)
![image](https://user-images.githubusercontent.com/52871301/73786552-5d815680-474e-11ea-869c-f36fa6eea8a7.png)

Thanks!

**Comment by ruanjue** [comment]
Hi, wtdbg2 is conservative in untangling repeats, it won't attempt to solve such case. When only there are enough reads spaning the repetitive region, wtdbg2 try to untangle it.
