### ISSUE TITLE
-L and -S parameters

### ISSUE THREAD

**Issue by A-J-F-Mackintosh** [ruanjue/wtdbg2#174]
Hi,

I am currently assembling multiple insect genomes from Pacbio Sequel (CLR) data, where genome size varies between 400 and 800Mb and heterozygosity is between 0.5 and 3%. Many of the datasets yield very contiguous assemblies using wtdbg2 (N50 >5Mb with a handful of contigs that represent whole chromosomes), but datasets where coverage is only 30-40X yield assemblies of much less contiguity.

I have therefore tried to improve the poorer assemblies by testing out different parameter settings for wtdbg2, namely the -L and -S parameters. I was surprised that -L 5000 gave better results than -L 2000 (see plot below) - surely having more reads and therefore greater coverage would yield better assemblies? I have checked that the increase in N50 is not because of smaller assemblies when using -L 5000. I also set -S to 1 so that there would be no sub-sampling of kmers. I thought this would give better results as more overlaps would be found, but this often wasn't the case.

Could you explain why subsampling reads and kmers improves wtdbg2 performance?

Many thanks for all your work on wtdbg2,

Alex

![image](https://user-images.githubusercontent.com/56942367/74162736-2c56c980-4c19-11ea-9b36-3906ae60ef7f.png)

**Comment by ruanjue** [comment]
A vertex on Fuzzy Bruijn Graph is 1024bp in length, so shorter reads only increase the coverage of vertices but not edges, then do harm to graph clean. `-S 1` will make the alignment more accurate and sensitive, but will bring more false positive alignments when you didn't change other aligmemnt filters like `-s, -l, -m`. 

For those bad assembies, try `-R`, `-A` and `--aln-dovetail -1`.

Best,
Jue

**Comment by A-J-F-Mackintosh** [comment]
Hi Jue,

Your explanation of why shorter reads do not improve contiguity was very helpful, thank you.

Using `-L 5000 -R -A --aln-dovetail -1` improved the contiguity of most of the assemblies, so many thanks for the recommendation.

Best,

Alex
