### ISSUE TITLE
Genome Size Parameter vs. Output consensus 

### ISSUE THREAD

**Issue by agos316** [ruanjue/wtdbg2#176]
Hello, I am new to de novo assembly and this program is the only one I could use so far that generates a consensus sequence with the resources I have. My question is about the genome size parameter. I put 13.7k for the genome size and the output sequence was ~40k. Is there a reason behind this ? I am using Nanopore reads. 

Best

Marc

**Comment by ruanjue** [comment]
Genome size is used to choose parameters, e.g. `-k`, `-S`. Combined with coverage cutoff `-X`, another use is to filter input reads. It have no direct impact on the final assembly size. In your case, please map the reads on assembled contigs to get more information.

**Comment by agos316** [comment]
Thank you for your quick response, I will try this today !
