### ISSUE TITLE
Potential Parameter for Assembling non PCR-Free Virus Genome 

### ISSUE THREAD

**Issue by yonghanyu** [ruanjue/wtdbg2#178]
Dear Dr. Ruan,

We intend to assemble the 2019-nCov virus genome with wtdbg2. Our sample contains 800x non PCR-free nanopore sequence. However, the program output empty .ctg.lay.gz file after multiple attempt with different parameter. Our current usage of the wtdbg2 is `wtdbg2 -p 0 -k 15 -AS 2 -s 0.05 -L 50 -g 30k -X 0 --no-read-clip`.

The log file shows: "searched 12 contigs" but "output 0 contigs".

Thus we are wondering whether you can provide some information in similar usage.

**Comment by ruanjue** [comment]
Maybe you should increase --edge-min to at least 30 . How about the estimated contigs size, the line like `[Wed Mar 11 13:04:47 2020] Estimated: TOT ...`.

**Comment by JackTATStraw** [comment]
Thanks for the quick reply. The program generate 48 nodes and 36 edges for 1371 intervals and 350k bins and the Extimated contigs size is empty... The summary of unitigs are: `TOT 25600, CNT 12, AVG 2134, MAX 3072, N50 2048, L50 6, N90 1792, L90 11, Min 1536`

**Comment by ruanjue** [comment]
Ok, should increase edge-min.

**Comment by JackTATStraw** [comment]
Thank you for the reply again. I tried with edge-min 30. The number of node and edge decrease to 7 and 6 correspondingly, still got empty output. I will try with larger edge-min. However, I am confused since your paper mentioned that 

> After graph simplification, wtdbg2 writes the final FBG to disk with read sequences on edges contained in the file.  Wtdbg2 constructs the final consensus with partial order alignment over edge sequences.

I suppose wtdbg2 will write the graph on disk and wtpoa-cns will construct the consensus sequence. So the number of edges should not be be a problem for receiving the graph. Does the program intend to find an Euler path or something simmilar that leads to such error when the graph is too complex?

**Comment by ruanjue** [comment]
If possible, please send me the log file and `<prefix>.2.dot.gz` and `<prefix>.3.dot.gz`, I would like to see the assembly graph. 

ruanjue@gmail.com

**Comment by JackTATStraw** [comment]
> If possible, please send me the log file and `<prefix>.2.dot.gz` and `<prefix>.3.dot.gz`, I would like to see the assembly graph.
> 
> [ruanjue@gmail.com](mailto:ruanjue@gmail.com)

thank you for your time, already sent.

**Comment by chunlinxiao** [comment]
was the problem solved? if yes, can you share the working parameters for wtdbg2?
thanks

**Comment by ruanjue** [comment]
We lost contact after rounds of disscussions. 

First, wtdbg2 cannot assemble very short reads, should > 1kb, be good to > 5kb. Second, have a look at `--min-ctg-nodes` and `--min-ctg-length` from `wtdbg2 --help`.
 
Jue
