### ISSUE TITLE
What if users use corrected reads instead of raw long-reads?

### ISSUE THREAD

**Issue by DomeJoyce** [ruanjue/wtdbg2#179]
Hello there, i was wandering if the use of already corrected reads can produce biased results on wtdbg2 assembly, since in the manual you declare " Wtdbg2 is a de novo sequence assembler for long noisy reads produced by PacBio or Oxford Nanopore Technologies (ONT). It assembles raw reads without error correction and then builds the consensus from intermediate assembly output.".
I really appreciate your work and i'm using for a PacBio (only) genome assembly.
Many thanks

**Comment by ruanjue** [comment]
`wtdbg2 -x ccs` will help.

**Comment by tauanajc** [comment]
Hi there Jue Ruan,
Given the same quote that DomeJoyce mentioned above, it is not clear to me what the ideal input files are. I am using nanopore data, and I know there is a preset for that. My question is, is the recommendation to use raw reads that were base called without any quality filtering, or should we filter for quality during basecalling, and then use the base called raw data as input to wtdbg2? Thanks!

**Comment by ruanjue** [comment]
In fact, I haven't try filtering. But I think it will help.
