### ISSUE TITLE
something wrong in pgzf_inflate_core -- pgzf.h:304

### ISSUE THREAD

**Issue by xiekunwhy** [ruanjue/wtdbg2#180]
Hi,

wtdbg2 done with "[Wed Mar 18 09:12:46 2020] Estimated: TOT 4470391296, CNT 64071, AVG 69773, MAX 4793856, N50 382464, L50 2804, N90 23040, L90 24429, Min 3072
[Wed Mar 18 10:16:35 2020] output 64071 contigs
[Wed Mar 18 10:16:48 2020] Program Done
".
But wtpoa-cns stopped with "
1164 contigs 753200 edges 1101341771 bases -- something wrong in pgzf_inflate_core -- pgzf.h:304 --
1164 contigs 753287 edges 1102194767 bases
PROC_STAT(TOTAL): real 16766.309 sec, user 333009.780 sec, sys 2666.660 sec, maxrss 3865348.0 kB, maxvsize 7192108.0 kB
---
"
and the final ctg.fa is ~1.1G, smaller than "Estimated: TOT 4470391296".
Some problems there, I think.

Best,
Kun

**Comment by ruanjue** [comment]
Try to decompress the layout file by yourself.
```sh
gzip -dc <prefix>.ctg.lay.gz | wtpoa-cns <other options> -i - -fo <prefix>.raw.fa
```

**Comment by xiekunwhy** [comment]
Hi @ruanjue 
Failed again.
1164 contigs 753300 edges 1101341548 bases
gzip: hci.ctg.lay.gz: invalid compressed data--format violated
1164 contigs 753384 edges 1102345327 bases
** PROC_STAT(TOTAL) **: real 8137.597 sec, user 162925.660 sec, sys 644.600 sec, maxrss 4066524.0 kB, maxvsize 5466812.0 kB

I need to redo the assembly?

**Comment by ruanjue** [comment]
Ok, we need to regenerate the `hci.ctg.lay.gz` file.
```sh
wtdbg2 <all of your previous options> --load-nodes hci.1.nodes --load-clips hci.clps
```
It will start the assembly quickly from graph cleaning.

**Comment by xiekunwhy** [comment]
Thank you, I will try it.

You said that "wtdbg2 <all of your previous options>", I am wondering that if I can change some options to get new results? 
like
`wtdbg2 -g 3g -R -p 19`
change to 
`wtdbg2 -g 3.2g -R -p 21 --aln-dovetail -1 -L 5000`

Best,
Kun

**Comment by ruanjue** [comment]
The options your proposed work on aligning, will do nothing on loading alignments.
