### ISSUE TITLE
complex genome with high heterozygosity and high duplication

### ISSUE THREAD

**Issue by fengyuanli304** [ruanjue/wtdbg2#182]
Hi,
I am running wtdbg2 to assembly a 2.9G genome. The data was generated from Pacbio sequel II library, representing approximately 84-fold coverage of the genome. The genome feature high levels of repetitive sequences (60.05%) and heterozygosity(1.3%).

At first, I use  --edge-min 4 -S 4 to save memory.
Data were assembled with the following parameters:
wtdbg2 -x sq -g 2.9g -t 16 -i merge.fastq.gz -fo prefix --tidy-reads 5000 --edge-min 4 -S 4 -L5000 > wtdbg2.log

The parameters received the following stats:
Largest contig              3372355   
Total length                5255609601
GC (%)                      28.70     
N50                         210837    
N75                         99358     
L50                         7081      
L75                         16105     
# N's per 100 kbp           0.00    
The genome size was estimated to be 2.91Gb, but total length is 5G.  
What parameters do you recommend for my data? Thank you very much!

**Comment by ruanjue** [comment]
Try remove `--edge-min 4`, add '-R'.

**Comment by fengyuanli304** [comment]
Hi,
I am sorry to bother you again. I have assembled the data using 'wtdbg2 -x sq -g 2.9g -R -S 4 -t 20 -i merge.fastq.gz -fo three --tidy-reads 5000 -L5000 > wtdbg2.log &' but the total length is larger than the genome size.  What can we do for solving this problem? Thank you.
The parameters received the following stats:
Largest contig              5875974     
Total length                5824894066  
GC (%)                      29.03       
N50                         237709      
N75                         85384       
L50                         5720        
L75                         16023

**Comment by ruanjue** [comment]
Please draw a dot-plot of all vs all contigs to see their similarity.

**Comment by fengyuanli304** [comment]
Many thanks for your answer.  But I do not understand how to compare these. all represents the assembly (pre.cfg.fa)? how can I get all contigs? Could you please clarify this in detail?

**Comment by ruanjue** [comment]
all contigs meant the contigs sequences from `wtpoa-cns`

**Comment by fengyuanli304** [comment]
Thank you.  send results via email

**Comment by jdmontenegro** [comment]
> Try remove `--edge-min 4`, add '-R'.

Hi ruanjue,

Since heterozygous regions will have lower depth than homozygous regions, the first parameter would reduce the minimum coverage of an edge to default (3) so heterozygous regions could be assembled separately. What would be the purpose of -R, to increase sensibility of read alignment to improve haplotype assembly?

Cheers,

Juan D.

**Comment by ruanjue** [comment]
`-R` is to increase sensitivity. After wtdbg2 produces the alignments, `-R` and `--realn-XXXXX` parameters will invoke realignments. Please note that I haven't tested the `--relan-XXXX` like parameters more than guess. If you want to use it, please tune them.
