### ISSUE TITLE
The log display for the wtdbg2

### ISSUE THREAD

**Issue by fredzhou91** [ruanjue/wtdbg2#187]
Hi,

I've been recently working on some assembly task and I'm now testing the wtdbg2.

I received the log info displayed as:

```
......
......
[Sun Apr 12 12:05:14 2020] - indexed  42976855 kmers, 33046838998 instances
[Sun Apr 12 12:05:16 2020] - masked 434905 bins as closed
[Sun Apr 12 12:05:16 2020] - sorting
** PROC_STAT(0) **: real 1718.414 sec, user 70638.190 sec, sys 919.870 sec, maxrss 230373076.0 kB, maxvsize 237792532.0 kB
[Sun Apr 12 12:06:37 2020] Done
```

then comes the following numebrs after the Done....
`3496000|257378850`

May I understanding what are the numbers representing for?

Thank you very much!

Best,
Fred

**Comment by ruanjue** [comment]
This is the progress, `<#reads>`|`<#alignments>`.

**Comment by fredzhou91** [comment]
Thank you Ruan Jue!

This indeed helps.. 

Then my task will be finished in one week which is much faster than expected!!!

Best,
Fred
