### ISSUE TITLE
Pronunciation and meaning of wtdbg?

### ISSUE THREAD

**Issue by dzyim** [ruanjue/wtdbg2#188]
Hello,  

I've been using wtdbg2 recently. 
I'm wondering the pronunciation of wtdbg2 and the full name or meaning of wtdbg2. 
Looking forward to your explanations.

Many thanks!

**Comment by ruanjue** [comment]
`wt` `dbg` = `watchtower` `DBG`
Or you can call it `redbean`, alias for `read bin`.
