### ISSUE TITLE
metagenomic sample parameters

### ISSUE THREAD

**Issue by deearahman** [ruanjue/wtdbg2#190]
Hi, 

I've sequence a clinical sample on the minion platform and would like to assemble it. I'm wondering what would the best parameters be. For example:
wtdbg2 -x rs -g ?m -i *fastq -t 16 -fo project
not too sure if this will work best and what should I choose for option -g

Thanks!

**Comment by ruanjue** [comment]
For metaassembly, try to tune parameters around  `--node-max 1000 -e 2` together with `-x ont/rs/sq`. Sequencing coverage is not available, so don't add `-g`.
