### ISSUE TITLE
fungi genome

### ISSUE THREAD

**Issue by YL1004** [ruanjue/wtdbg2#192]
Hi,i want to use this software to generate a fungi genome，it about 60mb，could you give me some suggestion parameter.Thank you

**Comment by ruanjue** [comment]
You can use the presets according to the input seqence type. Please see `-x`.

**Comment by YL1004** [comment]
My sequence type is ont,do you have Other parameters.Thank you

**Comment by ruanjue** [comment]
Try `-x ont -g 60m` first.

**Comment by YL1004** [comment]
Ok,i will try it at once

**Comment by YL1004** [comment]
I use this parameter，it generate 28 contigs.My expectation is within 20. Do you have any other parameters recommended

**Comment by ruanjue** [comment]
Too little information to give any further suggestion.
