### ISSUE TITLE
What does ‘share k-mers’ mean?

### ISSUE THREAD

**Issue by phoenix-jiaqi** [ruanjue/wtdbg2#194]
Hi. 
In paper,'Bins/boxes with the same color suggest they share k-mers'.
What does ‘share k-mers’ mean?

**Comment by phoenix-jiaqi** [comment]
Is that different bins have a same k-mer at least ?

**Comment by ruanjue** [comment]
When there is no sequencing error and repetitve sequences, bins from the same genomic region are identical, sharing all kmers. If sequencing high error rate, only a few k-mers are identical between 'identical' bins. If has repetitive sequences, different bins might share k-mers. However, wtdbg2 find matching bins in a dynamic programming way, which tolerates errors and repetitive seqs. The figure iluminates a basic framework of wtdbg2.
