### ISSUE TITLE
mistake in output on server

### ISSUE THREAD

**Issue by twolfe** [ruanjue/wtdbg2#195]
Hi,
I am trying to run wtdbg2 on a scientific cluster with slurm.
I get the follow in output when I grep the assembly fasta headers:

\>ctg1 len=573000
TTATAAAAATCTAACCCGGTTTCACCGATACTAATTACCTTTTGGTTCTTGGGAAATTCAACTATTCATCAACATGTTACACTCACCGTTTTTTA>>c>ct>ctg2 len=327600
AATTCCTGATATCCATTGTACCCTCACTGCATGGAAATTTTTTTTTTATTGTCAAATTTTCTTTAAAATAACTTTAAATTTTTGGGCTTTTGTAT>ct>ct>ctg3 len=168596
GCGTTGGCGTAAATAATTTTACATCAATTTTAGGCTTTGTTTGAATTGTAGTTTTTATAGGGTATCACGATGTTGTTTTCCGTCATTTTTA>ct>ct>ctg4 len=93446
ATGGAGTGCACATTTTCCATATCCTTCATTAGCAGTTATCC>ct>ct>ctg5 len=122087
TGATTTGGGGGTTAATCCAGAGTTTCTCAAGCAAGGCTCTGCAGTATCAGATTTTTTATACCCAGATAGGATAATAATAGGA>ct>ct>ctg6 len=57681
\>ctg7 len=32678
\>ctg8 len=28620
\>ctg9 len=17770
\>ctg10 len=4283
\>ctg11 len=5933
\>ctg12 len=3239
\>ctg13 len=5178

I tried with both versions 2.4 and 2.5 and also unzipped the ctg.lay.gz file before running wtpoa-cns.
Version 2.4 works fine on my local.
Thanks for your help and support

**Comment by ruanjue** [comment]
If you run v2.5 on this ctg.lay.gz multiple times, will the greped header change?
