### ISSUE TITLE
core dump illegal instructions 

### ISSUE THREAD

**Issue by giancarloRussoFGCZ** [ruanjue/wtdbg2#197]
Hi Jue, thanks for working on wtdbg2. I am using it (on a 256MB RAM node via SGE, I tried 16 and 32 threads) and I experience a core dump. This is the cmd (sequel data, about 620M genome size, about 100x coverage. 

###
wtdbg2 -L 5000 -x sq -g 620m -t 16 -i final.fastq -fo p3252_sylvestris
###

this is the stderr

###
/usr/local/var/ge62/default/spool/fgcz-c-048/job_scripts/576433: line 27: 33248 Illegal instruction     (core dumped) $wtdbg2 -L 5000 -x sq -g 620m -t 16 -i final.fastq -fo p3252_sylvestris
###

and this is the debug 

###
[Mon May 18 16:53:04 2020] loading reads
[New Thread 0x7ffff68ee700 (LWP 24556)]
3380000[Thread 0x7ffff68ee700 (LWP 24556) exited]
3388366 reads
[Mon May 18 17:04:08 2020] filtering from 3388366 reads (>=5000 bp), 64781069455 bp. Try selecting 31000000000 bp
[Mon May 18 17:04:16 2020] Done, 877106 reads (>=5000 bp), 31000019712 bp, 121093729 bins
** PROC_STAT(0) **: real 672.700 sec, user 652.720 sec, sys 221.700 sec, maxrss 17460084.0 kB, maxvsize 17798356.0 kB
[Mon May 18 17:04:16 2020] Set --edge-cov to 3
KEY PARAMETERS: -k 15 -p 0 -K 1000.049988 -A -S 2.000000 -s 0.050000 -g 620000000 -X 50.000000 -e 3 -L 5000
[Mon May 18 17:04:16 2020] generating nodes, 16 threads
[New Thread 0x7ffff68ee700 (LWP 26366)]
[New Thread 0x7fffecb71700 (LWP 26367)]
[New Thread 0x7fffe653a700 (LWP 26368)]
[New Thread 0x7fffe5d39700 (LWP 26369)]
[New Thread 0x7fffdeffd700 (LWP 26370)]
[New Thread 0x7fffde7fc700 (LWP 26371)]
[New Thread 0x7fffddffb700 (LWP 26372)]
[New Thread 0x7fffdd7fa700 (LWP 26373)]
[New Thread 0x7fffdcff9700 (LWP 26374)]
[New Thread 0x7fffdc7f8700 (LWP 26375)]
[New Thread 0x7fffdbff7700 (LWP 26376)]
[New Thread 0x7fffdb7f6700 (LWP 26377)]
[New Thread 0x7fffdaff5700 (LWP 26378)]
[New Thread 0x7fffda7f4700 (LWP 26379)]
[New Thread 0x7fffd9ff3700 (LWP 26380)]
[New Thread 0x7fffd97f2700 (LWP 26381)]
[New Thread 0x7fffd8ff1700 (LWP 26382)]
[Mon May 18 17:04:16 2020] indexing bins[(0,121093729)/121093729] (30999994624/64348378112 bp), 16 threads
[New Thread 0x7fffd87f0700 (LWP 26383)]
[New Thread 0x7fffd7fef700 (LWP 26384)]
[New Thread 0x7fffd77ee700 (LWP 26385)]
[New Thread 0x7fffd6fed700 (LWP 26386)]
[New Thread 0x7fffd67ec700 (LWP 26387)]
[New Thread 0x7fffd5feb700 (LWP 26388)]
[New Thread 0x7fffd57ea700 (LWP 26389)]
[New Thread 0x7fffd4fe9700 (LWP 26390)]
[New Thread 0x7fffb7fff700 (LWP 26391)]
[New Thread 0x7fffb77fe700 (LWP 26392)]
[New Thread 0x7fffb6ffd700 (LWP 26393)]
[New Thread 0x7fffb67fc700 (LWP 26394)]
[New Thread 0x7fffb5ffb700 (LWP 26395)]
[New Thread 0x7fffb57fa700 (LWP 26396)]
[New Thread 0x7fffb4ff9700 (LWP 26397)]
[New Thread 0x7fffaffff700 (LWP 26398)]
[Mon May 18 17:04:17 2020] - scanning kmers (K15P0S2.00) from 121093729 bins
121093729 bins

Program received signal SIGILL, Illegal instruction.
0x000000000043471c in index_kbm (kbm=0x66ad00, beg=0, end=121093729, ncpu=<optimized out>, kmstat=0x45fda80) at kbm.h:989
989                     _kcnts = malloc(200 * sizeof(u8i));
(gdb) 
###

Any help would be appreciated. 
Thanks ,
Giancarlo

**Comment by ruanjue** [comment]
This error might caused by codes in other lines. However, please add 
```txt
 kmstat = NULL;
```
at just before kbm.h:987, then compile and run it again.
