### ISSUE TITLE
The genome size and N50 of the genome  is much smaller after polished for 2 times,  the old polish tools such as pilon, after polishment, the genome and N50 will be a little bigger than before,  and which type of snp/indel is changed?

### ISSUE THREAD

**Issue by forrwill** [ruanjue/wtdbg2#199]

**Comment by forrwill** [comment]
with tools wtpoa-cns for pacbio reads and Illumina reads.

**Comment by ruanjue** [comment]
Could you give the commands, genome size and N50?

**Comment by forrwill** [comment]
/Bio/Linux-src-files/NGS/Align/bam_processing/samtools/v1.8_with_libdeflate/samtools-1.8/samtools view -@ 16 -O SAM /public2/Bio/Project/GDD6379/GDD6379_std_2/4.Polish/Polish2/Merge.bam | /Bio/User/kxie/software/wtdbg2/wtpoa-cns  -t 16 -x sam-sr -d /public2/Bio/Project/GDD6379/GDD6379_std_2/4.Polish/index/wtdbg-cns/pecan_1.fasta -i - -fo /public2/Bio/Project/GDD6379/GDD6379_std_2/4.Polish/Polish2/wtdbg-cns/pecan_2.fasta

**Comment by forrwill** [comment]
before:
![image](https://user-images.githubusercontent.com/41096851/82519139-8e499800-9b53-11ea-8b74-b9e10b744978.png)
after 2 times polish
![image](https://user-images.githubusercontent.com/41096851/82519162-9bff1d80-9b53-11ea-8cef-f46dd65d65f7.png)

**Comment by ruanjue** [comment]
The images cannot be displayed

**Comment by forrwill** [comment]
![Uploading image.png…]

**Comment by ruanjue** [comment]
I am afraid you need to paste text here, I still cannot display the image.

**Comment by forrwill** [comment]
before:
	Statistics:		Scaffold	Contig
	Total Number (#):	4116		4116
	Total length (bp):	993692583		993692583
	Gap(N)(bp):		0		0
	Average Length (bp):	241421.91		241421.91
	N50 Length (bp):	1184072		1184072
	N90 Length (bp):	87150		87150
	Maximum Length (bp):	6163683		6163683
	Minimum Length (bp):	340		340
	GC content :		36.28%		36.28%

after 2 times polish
	Statistics:		Scaffold	Contig
	Total Number (#):	4116		4116
	Total length (bp):	958727807		958727807
	Gap(N)(bp):		0		0
	Average Length (bp):	232927.07		232927.07
	N50 Length (bp):	1136923		1136923
	N90 Length (bp):	83433		83433
	Maximum Length (bp):	5909804		5909804
	Minimum Length (bp):	328		328
	GC content :		36.48%		36.48%

**Comment by ruanjue** [comment]
Thanks. Please select some tens of polished contigs to be compared with their original. Are the differences small indels or large? If you find there are many large indels on one contig, I am happy to debug on it later.

**Comment by forrwill** [comment]
while using Illumina reads for polishing, if the snps will be replaced?

**Comment by ruanjue** [comment]
Yes, `wtpoa-cns -x sam-sr` call consensus sequence from the multiple alignments of short reads.

**Comment by forrwill** [comment]
Thank you very much! I will compare some contigs at some time!
