### ISSUE TITLE
more details about the option "--no-read-length-sort"

### ISSUE THREAD

**Issue by bitcometz** [ruanjue/wtdbg2#20]
Hello,

(A) I used Single node to run wtdbg with ath data, the I get the results:
total length: 132015737, Max_length: 1433722, N50_len: 198115

(B) I used Multi node to run the kbm alignment according the way mentioned beford and adding the parameter: **--no-read-length-sort**, and get the results:
total length: 132770392, Max_length: 889975, N50_len: 178479

(C) I used alignments from (A), which is generated with Single node, and I run the assembly with the parameter: --no-read-length-sort, and get the results:
total length: 132675424, Max_length: 838984, N50_len: 176245

It seems that Single node usually generate better results than Multi node probably because of running the assembly part without "--no-read-length-sort" option.
My question is that: Can I run the alignment with Multi node and then do something with the alignment, and then run the assembly part without "--no-read-length-sort" option?
Or can you give me more details about the option "--no-read-length-sort"?

Thanks

**Comment by ruanjue** [comment]
If `kbm -c`, no need to add `--no-read-length-sort`. Else, needed. 

```sh
 --no-read-length-sort
   Defaultly, `wtdbg` sorts input sequences by length DSC. The order of reads affects the generating of nodes in selecting important intervals
``` 
wtdbg selects intrevals in reads as nodes, it raises a problem that which region in which read should be treated as a node. Currently, wtdbg2 prefers to select node in the first read it met. So, sorting reads by length affects, and tends to be better.

**Comment by bitcometz** [comment]
Thanks！
The above works find for ath genome.
However, I failed on the ~500M genome:
**For Single node**:
**command:** wtdbg-1.2.8 -t 32 -i raw.fasta --tidy-reads 5000 -fo raw -k 0 -p 19 -S 1 --rescue-low-cov-edges --aln-noskip --aln-dovetail -1
**Results:** Estimated: TOT 651820288, CNT 8653, AVG 75329, MAX 11719168, N50 742912
[Thu Sep 13 08:21:40 2018] selecting important intervals from 31087245 intervals
[Thu Sep 13 08:24:25 2018] Intervals: **kept 1018883**, discarded 30068362

**For Multi node**
**kbm command:** wtdbg2/kbm -t 10 -c -p 19 -K 200 -S 1 -i reads.1.fa -d reads.1.fa -o reads.kbmap.1.1
....
**wtdbg command:** wtdbg2 -i total.fasta --load-alignments total.alg -t 5 -fo ori --edge-min 4 --no-read-length-sort --aln-dovetail -1
**Results:** TOT 1123026944, CNT 14182, AVG 79187, MAX 8086016, N50 408320
[Fri Oct 12 10:17:40 2018] selecting important intervals from 24385214 intervals
[Fri Oct 12 10:22:00 2018] Intervals: **kept 1519600**, discarded 22865614

Unexpected, the size of assembly from Multi node is about twice as big as that from Single node.

Thanks

**Comment by ruanjue** [comment]
I had tested kbm+wtdbg2 on C.elegans dataset, my script is lised in below:
```sh
#!/bin/bash
#
#

NUM=10
NCPU=20

split_seqs_2.pl $NUM wt.fa
perl -we'$N=shift || 10;$T=shift || 20;for($i=1;$i<=$N;$i++){for($j=$i;$j<=$N;$j++){ print "kbm -t $T -i wt.fa.shuffle$i". (($i == $j)? " -c" : " -d wt.fa.shuffle$j") . " -fo out.kbmap.$j.$i\n"; }}' $NUM $NCPU >run.sh
#
# You should qsub jobs
# but local jobs here
#
bash run.sh >log.kbm 2>&1
cat out.kbmap.* >wt.fa.kbmap
cp wt.fa.shuffle1 wt.trans.fa
for i in `seq 2 $NUM`; do
        cat wt.fa.shuffle$i >>wt.trans.fa
done

wtdbg2 -t $NCPU -i wt.trans.fa --load-alignments wt.fa.kbmap -L 5000 --keep-name --no-read-length-sort -fo dbg >log.asm 2>&1

wtpoa-cns -t $NCPU -i dbg.ctg.lay -fo dbg.ctg.lay.fa >log.poa 2>&1
```
Please use the latest wtdbg2 (https://github.com/ruanjue/wtdbg2/commit/b7c775aee7ea333abbeeea35093a342e8e9aa854).

The assmebly looks as good as running in single node.

Best,
Jue

**Comment by bitcometz** [comment]
Thanks!

I am wondering if the genome size is about 1Gb and then the split the total 60G reads into ~6Gbp for each (10 parts in total).
Than there are some difference between single node and Multi node
because in the Multi node wtdbg will masked more low frequency kmers than in single node, which in turn generate different alignments?
Am I right?

**Comment by ruanjue** [comment]
Yes, you are right in low freq kmers. Also, wtdbg2 will skip the contained reads when no '-A'. It will be another difference.

**Comment by bitcometz** [comment]
Thanks！
If I detected the contained reads from alignments of different pats and then deleted all the alignments related to these contained reads, will this process help to reduce the difference?
And according to your experience, is it necessary to keep the alignments from contained reads?

Best

**Comment by ruanjue** [comment]
I don't think it is neceesary to reduce the difference, but need to focus on the accuracy of assemblies. If the assemblies is ok, any procedure and parameters are fine.

Most of times, alignments of contianed reads will help in assembly, but will slow the assembling. I also add `-A` to some low sequence coverage assembly, please see the table in https://github.com/ruanjue/wtdbg2#usage.

**Comment by bitcometz** [comment]
Thanks.
And If I remove the alignments from contained reads, will it affect the performance of "edge-min"?
I am afraid that if the edge-min is 2, the assembly errors which is generated from chimeric reads will be retained in the final results.

**Comment by ruanjue** [comment]
In principle, removing alignments from contained reads won't affect the edge coverage. But I cannot always grant that, because node selecting is not a clearly predicted job in the present of different alignments set.

`-e 2` is only suggested to be used in low sequencing coverage assembly like 30X.

**Comment by bitcometz** [comment]
Thanks!
The only problem is that the Multi node yields a scaffolds twice the size of the from Single node for high heterozygosity genomes (at least two genomes).
Anyway, I will try to filtered out some alignments to reduce the genome sizes.

**Comment by ruanjue** [comment]
There should be something wrong in wtdbg, I will let you know when find it.

**Comment by bitcometz** [comment]
Thanks!
For arabidopsis thaliana genome，Multi node yields good result as well as Single node!

**Comment by bitcometz** [comment]
Thanks. I try --keep-name without --no-read-length-sort but worst results (lower N50 and still twice genome sizes)

**Comment by bitcometz** [comment]
Hello,
I tried the Multi node approach with the following parameters:

"-E 2 -n 50 -p 17 **-k 0** -S 1 -t 10 -c" for self-part vs self-part alignment
"-E 2 -n 50 -p 17 **-k 0** -S 1 -t 10" for self-part vs other-part alignment
"--no-read-length-sort" for assembly.

Then, I got the same good result as single node.

Thanks for all your help!

**Comment by bitcometz** [comment]
Hello,

For the 4.0 Gb reads of arabidopsis thaliana, 
**(A)** I run the commands:
wtdbg2 -i reads.total -t 10 -fo ath --rescue-low-cov-edges --no-read-length-sort --aln-dovetail -1 -p 17 -k 0 -S 1
And I found **642** alignment hits for one read named with "266932_18078".

**(B)** I split the 4.0Gb reads into 3.8Gb (reads.1.fa) and 190M (reads.2.fa) and run the commands:
kbm -E 2 -m 400 -n 700 -p 17 -k 0 -S 1 -t 10 -i reads.1.fa -d reads.2.fa -fo reads.kbmap.1.2
And I found **8911** alignment hits for the same read named with "266932_18078".
(the read "266932_18078" was in the reads.2.fa)

So I thinks this is another differences for running alignments with Multi node approach because
kbm would output unlimited alignments hits for the reads as the references.

Could you add a similar parameter (-n, Max hits per query) to limit the alignment hits for reads when they are used as reference?

Thanks

**Comment by ruanjue** [comment]
In kbm, there is an option to limit num_hits
` -n <int>    Max hits per query, [1000]`

BTW, for sequel dataset, please use `-k 15 -p 0 -AS 2` or `-x sequel` in wtdbg-2.2.

**Comment by bitcometz** [comment]
Thanks!

One more question: 
Why high frequency kmers  affect results so much(1.4G vs 176Mb), even though they account for a very small percentage of the total kmer numbers ？ 

Running commands : 
kbm2 -m 300 -K 200 -p 0 -k 15 -S 2 -t 10 -c -i reads.1.fa -fo reads.kbmap.1.1

(A) par->ktop  = 0.05;
[Wed Nov 14 14:50:38 2018] - high frequency kmer depth is set to 477
[Wed Nov 14 14:50:38 2018] - Total kmers = 223993753
[Wed Nov 14 14:50:38 2018] - average kmer depth = 6
[Wed Nov 14 14:50:38 2018] - 54900428 low frequency kmers (<2)
[Wed Nov 14 14:50:38 2018] - **47361** high frequency kmers (>477)

Alignment File: **1.4G	reads.kbmap.1.1**

(B) par->ktop  = 0.15;
[Wed Nov 14 15:55:47 2018] - high frequency kmer depth is set to 200
[Wed Nov 14 15:55:47 2018] - Total kmers = 223993753
[Wed Nov 14 15:55:47 2018] - average kmer depth = 6
[Wed Nov 14 15:55:47 2018] - 54900428 low frequency kmers (<2)
[Wed Nov 14 15:55:47 2018] - **172128** high frequency kmers (>200)

Alignment File: **176M	reads.kbmap.1.1**

Best

**Comment by ruanjue** [comment]
`-K 0.15` filtered too much kmers! 

One kmer counting 100, will potentially bring 100*99/2 pairs.

**Comment by bitcometz** [comment]
Thanks!
Another question:

I am doing self vs self alignment for reads (~ 10x) : 
kbm2 -m 300 -n 100 -p 0 -k 15 -S 2 -t 10 -c -i reads.2.fa -fo reads.kbmap.2.2

and I find the the min kmer depth is set to 2:
71252090 low frequency kmers (**<2**)

because in the code:

	if(qrys->size == 0){
		par->self_aln = 1;
		interactive = 0;
		**if(par->kmin < 2) par->kmin = 2;**
	}

Could you explain why？ And would filtering these low kmers reduce the alignment output if the reads depth is ~10x?

Best

**Comment by ruanjue** [comment]
When performing all vs all alignments, kmers[depth=1] is useless in aligning. Because it potentially forms 1*0/2 pairs. It doesn't matter 10x or 100x.

**Comment by ruanjue** [comment]
Have a look at the node median coverage, With -g parameter, wtdbg2 will select about `-X 50.0` reads for alignment and assembly. 

We are preparing a manuscript for wtdbg2, maybe firstly put on bioRxiv, will describe more on how to selecting nodes from alignments.

BTW, try -l, -m, -s to filter alignments.

Best,
Jue

**Comment by bitcometz** [comment]
For single node:
median node depth = 67
masked 18033 high coverage nodes (>200 or <10)
masked 14341 repeat-like nodes by local subgraph analysis

For Multi node:
median node depth = 19
masked 2283 high coverage nodes (>200 or <3)
masked 30009 repeat-like nodes by local subgraph analysis

Thanks for your advise and looking forward to reading your article !!!

Best,

**Comment by bitcometz** [comment]
Hello, 
I think the parameter of "--node-len" is similar to the parameter 'Kmer size' in soapdenovo?
So, 
(A) for high heterozygous genomes, we should decrease it to "768" to merge more bubbles?
(B) for high repetitive genomes, we should increase it to "1280" to solve more repeat structures?

Thanks!

**Comment by ruanjue** [comment]
--node-len is times of BIN, let's say k-bins. The default is 4-bins. However, I am not sure of your inferrence, because I found the 4-bins was best in my tests.

Thanks,
Jue

**Comment by bitcometz** [comment]
Indeed, I do not understand this parameter very well.
Does it mean there are 4 KBM_BIN considered as **one** node?

However, in my test, I try **2048**(8) and it works really well, it help increase the N50 from **172544** to **702208**.
I thinks it gets better N50 index mainly because it selected only **317354**( Done, 317354 nodes, half of those with default parameter "1024"), and the median node depth = 17

But, will it generate a lot of assembly errors?

Best,

**Comment by bitcometz** [comment]
**And One more thing:**
I filtered out the "Overhang" alignment defined in miniasm paper for the candidate repetitive reads (with  high frequency alignment hits) and alignments from contained reads.
By doing this help me reduce the memory consumption to less than 30G.

With default "1024" , I can get N50 ~200Kbp.

**Comment by ruanjue** [comment]
Glad to hear that 8-bins work better than 4-bins, to be honest, I haven't try so large k-bins. On mis-assemblies, I don't think 8-bin will bring more errors.

`--aln-dovetail` might meet your need in filtering overhangs.

Thanks,
Jue

**Comment by bitcometz** [comment]
Thank you for reminding me about this option !
And about filtering overhangs, I did a test before: If I filtered Overhang alignment for all the reads, the assembly size will increase much bigger than I want. I think it might be due to that I filter some alignments between highly heterozygous regions and hence has a negative effect on the bubble merging. And If I remove Overhang alignment for reads with much alignment hits, it have little effect on genome size as well as N50 index

Best,

**Comment by bitcometz** [comment]
Hello,

I got the log information from the log file generated by wtdbg2:

Estimated: **TOT 455993600**, **CNT 2380**, AVG 191594, MAX 8397312, **N50 1021184**, L50 101, N90 83456, L90 764

And then run:
wtdbg-cns -t 10 -i test.ctg.lay -fo test.ctg.lay.fa -c 0

I do the statistics for the file test.ctg.lay.fa : 
#Title          Total_length    Total_number    Num>=100        Num>=2000       Average_length  Max_length      Min_length      N50_len
Contig          699259420       2380            2380            2380            293806          13807584        6974            1690385

The number of contigs is consistent, but the total length(699259420) and N50 length(1690385) is much larger.

Could you help with this question？

Thanks!

**Comment by ruanjue** [comment]
Did you change the --node-len in wtdbg2. If so, please have a look at wtpoa-cns -j <int>. I used to set -j 1500 when --node-len=1024.

**Comment by bitcometz** [comment]
Hello,
I try -j 2800 and the size is normal. Thanks!

**Comment by ruanjue** [comment]
Great! 

Set -j = 1500 along with --node-len=1024. Because wtdbg2 doesn't align sequences in bp, but in BIN(256bp), the consensus sequence of a node is often large than 1024.
