### ISSUE TITLE
rGFA

### ISSUE THREAD

**Issue by jdmontenegro** [ruanjue/wtdbg2#200]
Dear Jue,

Thnk you for the tools, it is wroking wonderfully with my dataset. I have one question though. I am attempting to use graph assemblies to try and dissentangle consensus sequences into chromatid-specific reads for reassembly. I have used the dot2gfa script that you provide, but the sequences are not parsed, so I cannot actually use it for mapping my reads. Is there any obvious way I could do this from the files that are already generated after assembly? I would need the sequences of the edges to add them in the GFA that is already produced.

Cheers,

Juan D. Montenegro

**Comment by ruanjue** [comment]
Have a look at the `<prefix>.ctg.lay.gz`. There is some text for it at https://github.com/ruanjue/wtdbg2/blob/master/README-ori.md#output.
