### ISSUE TITLE
polishment using other tools

### ISSUE THREAD

**Issue by wangjiawen2013** [ruanjue/wtdbg2#202]
Hello,
Does the quick start (./wtdbg2.pl -t 16 -x rs -g 4.6m -o dbg reads.fa.gz) wraps the following three steps:
1 ./wtdbg2 -x rs -g 4.6m -i reads.fa.gz -t 16 -fo dbg
2 ./wtpoa-cns -t 16 -i dbg.ctg.lay.gz -fo dbg.raw.fa
3 minimap2 -t16 -ax map-pb -r2k dbg.raw.fa reads.fa.gz | samtools sort -@4 >dbg.bam
samtools view -F0x900 dbg.bam | ./wtpoa-cns -t 16 -d dbg.raw.fa -i - -fo dbg.cns.fa
If so, if i wanna polish the data using other tools, does it means that I must run the above three steps separately ? namely, run step 1 and 2 first, then run step3 with other polishment tools ?

**Comment by ruanjue** [comment]
Yes, you are right. Besides, you can run other polish tool after all those 3 steps finished.
