### ISSUE TITLE
parameters setting for 30X raw/corrected ONT reads

### ISSUE THREAD

**Issue by HanKMU** [ruanjue/wtdbg2#205]
Hi, 
We are going to try the assembly of both raw or corrected nanopore reads through wtdbg2.
The estimated genome size is 1G and we got about 30-35 coverage sequence.
Would you please give us some suggestion on our parameters setting?
We take issue #120 #72 #109 and #170 as references.

input nanopore RAW reads:
```-x ont -t 4 -i <ONT.fastq> -o <Prefix of output files> -g 1g -S 2 -p 19 --edge-min 2 --rescue-low-cov-edges -R --no-read-clip --aln-dovetail```

input nanopore CORRECTED reads:
```-x ccs -t 4 -I <ONT.fastq> -o <Prefix of output files> -g 1g -S 2 -p 19 --edge-min 2 --rescue-low-cov-edges -R --no-read-clip --aln-dovetail```

We're also confuse that should we add `-A` or `-l 1000` and how to set the value of `--aln-dovetail`

Thanks for your time!

**Comment by ruanjue** [comment]
For the low coverage assembly, I suggest to add `-A`. About the max overhang size in dovetail, please first try to set it to `--aln-dovetail -1` , then you can test `1024`.

Besides, for the corrected reads, please set the similary `-s 0.5`.

Jue

**Comment by HanKMU** [comment]
Got it! Thank you so much for the immediate response!
