### ISSUE TITLE
Consensus exited - dbgcns.h:1122 --

### ISSUE THREAD

**Issue by msikic** [ruanjue/wtdbg2#206]
Hi, 

I have tried to run redbean on NA12878 genome. 
After assembly successfully finished (/usr/bin/time -v wtdbg2 -x ont -g3g -t 64 -i rel_6.fastq.gz -o redbean_NA12878 2> err_redbean ) 
I run the consensus and got the following message

-- total memory     1056751744.0 kB
-- available         399633452.0 kB
-- 256 cores
-- Starting program: wtdbg-cns -t 64 -i redbean_NA12878.ctg.lay.gz -o redbean_NA12878.ctg.fa
-- pid                    106509
-- date         Fri Jun 12 08:49:55 2020

 -- something wrong, nb = 21759(K0869), ne = 4724(K156860) in DP_best_path_DirectFuzzyBruijnGraph -- dbgcns.h:1122 --
Command exited with non-zero status 1

I have tried twice and got the same message. 

The version is: wtdbg-cns 1.1

Best, 

Mile

**Comment by ruanjue** [comment]
Please run `wtpoa-cns` instead. The base accuracy of contigs from `wtdbg-cns` is lower than `wtpoa-cns`. I haven't updated `wtdbg-cns` for years.

**Comment by ahcm** [comment]
Mabe remove wtdbg-cns from default build to avoid confusion.
