### ISSUE TITLE
is there a checkpoint in wtdbg2

### ISSUE THREAD

**Issue by daiqinli** [ruanjue/wtdbg2#207]
I have running wtdbg2 for assembling a 4.5 GB genome with PBS, but the supercomputer centre is allowed for large memories up to 6TB but only 24 hrs walltime. The run stops after allocated 24 hrs and exited without finishing. I thought wtdbg2 might have checkpoints for resubmitting the same job and continue running the last point. However, it seems start from zero again. I am wondering if wtdbg2 has checkpoints or not. Might I have some problems with my setting? can anyone help?

**Comment by ruanjue** [comment]
Please have a look at `wtdbg2 --help`, there are many options starting with `--dump` or `--load`. However, I am not sure wtdbg2 can finish the alignment step within 24 hrs.

**Comment by daiqinli** [comment]
thank you for your suggestion. If wtdbg2 cannot finish the alignment step in 24 hrs, what is your suggestions?

**Comment by ruanjue** [comment]
Apply for more time.

**Comment by daiqinli** [comment]
Thanks. If extending beyond 24 hrs walltime is impossible due to the policies, and alignment cannot finish within 24 hrs, whether and how can I use  -- dump or --load. can I use --load-alignments <string> + ? which will allow continue alignment after 24 hrs? 

can you give your advice on the setting as below?

-x sq -g 4.04g -i ~.gz -t 48 -fo *_kbm --tidy-reads 5000 --edge-min 3 --rescue-low-cov-edges -R --aln-dovetail --load-alignments *.alignments.gz +

Thanks

**Comment by ruanjue** [comment]
change the preset to `-x rs` will increase the speed of alignment
