### ISSUE TITLE
Segmentation fault with Slurm exit code 139

### ISSUE THREAD

**Issue by biowackysci** [ruanjue/wtdbg2#213]
Hello 
I am trying to run an assembly job with the following script 
wtdbg2 -x ont -g 2.8g -t 100 -p 19 -AS 2 -s 0.05 -L 30000 -i /group/pasture/Saila/wtdg2_L20KB_readlength/2020_newassembly/HSandSVreads/30kbplusreads/30kbplus_HSandSV_allreads_combine.fastq -fo HSandSVII_30kbabove_reads
wtpoa-cns -t 100 -i HSandSVII_30kbabove_reads.ctg.lay.gz -fo HSandSVII_30kbabove_reads.ctg.fa

I get the following error messages each time I try 
--
-- total memory      790881552.0 kB
-- available         756311976.0 kB
-- 48 cores
-- Starting program: wtdbg2 -x ont -g 2.8g -t 100 -p 19 -AS 2 -s 0.05 -L 30000 -i /group/pasture/Saila/wtdg2_L20KB_readlength/2020_newassembly/HSandSVreads/30kbplusreads/30kbplus_HSandSV_allreads_combine.fastq -fo HSandSVII_30kbabove_reads
-- pid                    326481
-- date         Wed Aug 12 21:23:08 2020
--
(Then it starts to load the reads)
and does everything until it fails at 
232 contigs 18200 edges 41541150 bases/var/spool/slurm/d/job2581635/slurm_script: line 51: 420083 Segmentation fault      (core dumped) wtpoa-cns -t 100 -i HSandSVII_30kbabove_reads.ctg.lay.gz -fo HSandSVII_30kbabove_reads.ctg.fa

Is there somehow I can solve this segmentation fault

Thanks
S

**Comment by ruanjue** [comment]
It was the error of `wtpoa-cns`. If you can separate the very small number of contigs's layout around 232'th from the big total lay file that will produce the segmentation fault, I will debug on the samll file to find what' wrong.

**Comment by biowackysci** [comment]
Hello Ruanjue,
I could not 232 as it was empty, so I have sent you 231 contig. 
[test.txt](https://github.com/ruanjue/wtdbg2/files/5073026/test.txt)

**Comment by ruanjue** [comment]
I meant the minimal part of input file that repeat the seqfault.

**Comment by biowackysci** [comment]
Sorry, I am not entirely sure of what file you are after. Are you after the source input fastq file? Sorry I new to the assembly world.

Thanks
S

**Comment by ruanjue** [comment]
`HSandSVII_30kbabove_reads.ctg.lay.gz`

**Comment by biowackysci** [comment]
Hello,
The previous file I sent you was an extract from the .lay file. Do you require more contigs or something else?
Sorry for this 
Thanks again
S

**Comment by ruanjue** [comment]
Hi,

When you are sure of the minimal part that repeat the error on your computer, please compress the file and send to me (ruanjue.big AT qq.com)

Jue

**Comment by biowackysci** [comment]
Hello Ruanjue,

I have sorted the issue out. I had some bad fastq reads and I cleaned them and resubmitted the job. its all good now 
Thanks for your input though
S 
PS you may close the issue
