### ISSUE TITLE
Plasmid problems

### ISSUE THREAD

**Issue by davidvilanova** [ruanjue/wtdbg2#217]
Hello,
I have sequenced a plasmid with 50 tandem repeats (using nanopore) . It´s a lab plasmid used to produce a specific protein. The plasmid is 5Kb and tandem repeats(150nt)  are also 5Kb so the overall estimated size is 10kb. 
The 5´prime of the plasmid is a vector and the 3´end also. Repeats are in between
I have tried to assembly the plasmid using the following command:

` -k 15 -p 0 -K 1000.049988 -A -S 4.000000 -s 0.050000 -g 0 -X 50.000000 -e 3 -L 5000`

The final contig is too large and contains only a few of the expected tandem repeats. Mummer analysis does show that the plasmid does not match all the repeats. I also have the reference fasta sequence of the expected plasmid.

Is there a way to assembly such plasmid ?

**Comment by ruanjue** [comment]
Try increase the overlap length of alignment by `-l 4096`.  Or plus `-R` option.

**Comment by davidvilanova** [comment]
Thanks, will give it a try
