### ISSUE TITLE
A 7g genome 

### ISSUE THREAD

**Issue by chensunefu** [ruanjue/wtdbg2#22]
I used wtdbg-1.28 to assemble a 7g plant genome with about 70X pacbio data under default parameters (-L 5000) and got a ~6.5 g result.
But, now I am assembling this genome using the same data with wtdbg2.1. The software stoped at indexing k-mers. I have tried several times. I think maybe there are some bugs in this version. Please could you check it?
PS. I can get a poor results with 2.1 version when only used reads longer then 15 Kb.

**Comment by ruanjue** [comment]
Thanks for feedback.

When you said " stoped at indexing k-mers", does it mean program core dump, or cannot go on in indexing but alive?

**Comment by chensunefu** [comment]
Thanks for your quick response.


I attached the problem.


陈肃
林木遗传育种国家重点实验室（东北林业大学）
On 10/11/2018 10:58，Jue Ruan<notifications@github.com> wrote：

Thanks for feedback.

When you said " stoped at indexing k-mers", does it mean program core dump, or cannot go on in indexing but alive?

**Comment by ruanjue** [comment]
I guess github cannot process attached files. Please send it to my email `ruanjue@gmail.com`, or paste it here.

**Comment by chensunefu** [comment]
The wtdbg2 cannot go on, it still alive but seems to be a zombie.

**Comment by ruanjue** [comment]
```sh
rm -f wtdbg2
make wtdbg2 DEBUG=1

gdb /path/to/wtdbg2
gdb> run -t 40 -i your_seqs.fa -p 19 ....  
```
When you find the program stop in indexing
```sh
gdb> bt
gdb> info threads
```
Please also contact me.

**Comment by chensunefu** [comment]
Thanks so much. I will contact you once I meet problem or I get a result.

**Comment by chensunefu** [comment]
The program stop at index step. But now gdb doesnt response to any operations......
What can I do now?

**Comment by ruanjue** [comment]
paste the latest 40 lines in screen

**Comment by chensunefu** [comment]
#0  0x0000000000416072 in index_kbm (kbm=0x69e720, beg=0, end=132551813                                                                                                      7, ncpu=40) at kbm.h:905
#1  0x000000000042e113 in build_nodes_graph (maxbp=18446744073709551615                                                                                                      , ncpu=40, pws=0x0, rdclip=1,
    prefix=0x7fffffffe056 "wtdbg-5k", dump_kbm=0x0) at wtdbg.c:1265
#2  0x0000000000472e7e in main (argc=13, argv=0x7fffffffdcf8) at wtdbg.                                                                                                      c:6953
(gdb) info threads
  84 Thread 0x7fff2e1fc700 (LWP 17278)  0x0000000000413ce1 in thread_mi                                                                                                      dx_func (obj=0x2fe96b90) at kbm.h:745
  83 Thread 0x7fff2ebfd700 (LWP 17277)  0x0000000000413c81 in thread_mi                                                                                                      dx_func (obj=0x2fe96aa0) at kbm.h:744
  82 Thread 0x7fff2f5fe700 (LWP 17276)  0x0000000000413c81 in thread_mi                                                                                                      dx_func (obj=0x2fe969b0) at kbm.h:744
  81 Thread 0x7fff34dfa700 (LWP 17275)  0x0000000000413c81 in thread_mi                                                                                                      dx_func (obj=0x2fe968c0) at kbm.h:744
  80 Thread 0x7fff357fb700 (LWP 17274)  0x0000000000413c81 in thread_mi                                                                                                      dx_func (obj=0x2fe967d0) at kbm.h:744
  79 Thread 0x7fff361fc700 (LWP 17273)  0x0000000000413ce1 in thread_mi                                                                                                      dx_func (obj=0x2fe966e0) at kbm.h:745
  78 Thread 0x7fff36bfd700 (LWP 17272)  0x0000000000413ce1 in thread_mi                                                                                                      dx_func (obj=0x2fe965f0) at kbm.h:745
  77 Thread 0x7fff375fe700 (LWP 17271)  0x0000000000413c81 in thread_mi                                                                                                      dx_func (obj=0x2fe96500) at kbm.h:744
  76 Thread 0x7fff3cdfa700 (LWP 17270)  0x0000000000413ce1 in thread_mi                                                                                                      dx_func (obj=0x2fe96410) at kbm.h:745
  75 Thread 0x7fff3d7fb700 (LWP 17269)  0x0000000000413c81 in thread_mi                                                                                                      dx_func (obj=0x2fe96320) at kbm.h:744
  74 Thread 0x7fff3e1fc700 (LWP 17268)  0x0000000000413ce1 in thread_mi                                                                                                      dx_func (obj=0x2fe96230) at kbm.h:745
  73 Thread 0x7fff3ebfd700 (LWP 17267)  0x0000000000413c81 in thread_mi                                                                                                      dx_func (obj=0x2fe96140) at kbm.h:744
  72 Thread 0x7fff3f5fe700 (LWP 17266)  0x0000000000413c81 in thread_mi                                                                                                      dx_func (obj=0x2fe96050) at kbm.h:744
  71 Thread 0x7fff44dfa700 (LWP 17265)  0x0000000000413c81 in thread_mi                                                                                                      dx_func (obj=0x2fe95f60) at kbm.h:744
  70 Thread 0x7fff457fb700 (LWP 17264)  0x0000000000413c81 in thread_mi                                                                                                      dx_func (obj=0x2fe95e70) at kbm.h:744
  69 Thread 0x7fff461fc700 (LWP 17263)  0x0000000000413c81 in thread_mi                                                                                                      dx_func (obj=0x2fe95d80) at kbm.h:744
  68 Thread 0x7fff46bfd700 (LWP 17262)  0x0000000000413ce1 in thread_mi                                                                                                      dx_func (obj=0x2fe95c90) at kbm.h:745
---Type <return> to continue, or q <return> to quit---return
  67 Thread 0x7fff475fe700 (LWP 17261)  0x0000000000413c81 in thread_mi                                                                                                      dx_func (obj=0x2fe95ba0) at kbm.h:744
  66 Thread 0x7fff4cdfa700 (LWP 17260)  0x0000000000413c81 in thread_mi                                                                                                      dx_func (obj=0x2fe95ab0) at kbm.h:744
  65 Thread 0x7fff4d7fb700 (LWP 17259)  0x0000000000413ce1 in thread_mi                                                                                                      dx_func (obj=0x2fe959c0) at kbm.h:745
  64 Thread 0x7fff4e1fc700 (LWP 17258)  0x0000000000413c81 in thread_mi                                                                                                      dx_func (obj=0x2fe958d0) at kbm.h:744
  63 Thread 0x7fff4ebfd700 (LWP 17257)  0x0000000000413c81 in thread_mi                                                                                                      dx_func (obj=0x2fe957e0) at kbm.h:744
  62 Thread 0x7fff4f5fe700 (LWP 17256)  0x0000000000413ce1 in thread_mi                                                                                                      dx_func (obj=0x2fe956f0) at kbm.h:745
  61 Thread 0x7fff54d0f700 (LWP 17255)  0x0000000000413c81 in thread_mi                                                                                                      dx_func (obj=0x2fe95600) at kbm.h:744
  60 Thread 0x7fff55710700 (LWP 17254)  0x0000000000413c81 in thread_mi                                                                                                      dx_func (obj=0x2fe95510) at kbm.h:744
  59 Thread 0x7fff56111700 (LWP 17253)  0x0000000000413ce1 in thread_mi                                                                                                      dx_func (obj=0x2fe95420) at kbm.h:745
  58 Thread 0x7fffbeb71700 (LWP 17252)  0x0000000000413ce1 in thread_mi                                                                                                      dx_func (obj=0x2fe95330) at kbm.h:745
  57 Thread 0x7fffbf572700 (LWP 17251)  0x0000000000413c81 in thread_mi                                                                                                      dx_func (obj=0x2fe95240) at kbm.h:744
  56 Thread 0x7fffbff73700 (LWP 17250)  0x0000000000413ce1 in thread_mi                                                                                                      dx_func (obj=0x2fe95150) at kbm.h:745
  55 Thread 0x7fffc0974700 (LWP 17249)  0x0000000000413c81 in thread_mi                                                                                                      dx_func (obj=0x2fe95060) at kbm.h:744
  54 Thread 0x7fffc1375700 (LWP 17248)  0x0000000000413ce1 in thread_mi                                                                                                      dx_func (obj=0x2fe94f70) at kbm.h:745
  53 Thread 0x7fffc1d76700 (LWP 17247)  0x0000000000413ce1 in thread_mi                                                                                                      dx_func (obj=0x2fe94e80) at kbm.h:745
  52 Thread 0x7fffc2777700 (LWP 17246)  0x0000000000413ce1 in thread_mi                                                                                                      dx_func (obj=0x2fe94d90) at kbm.h:745
  51 Thread 0x7fffc3178700 (LWP 17245)  0x0000000000413ce1 in thread_mi                                                                                                      dx_func (obj=0x2fe94ca0) at kbm.h:745
---Type <return> to continue, or q <return> to quit---
  50 Thread 0x7fffc3b79700 (LWP 17244)  0x0000000000413c81 in thread_midx_func (obj=0x2fe94bb0) at kbm.h:744
  49 Thread 0x7fffc457a700 (LWP 17243)  0x0000000000413ce1 in thread_midx_func (obj=0x2fe94ac0) at kbm.h:745
  48 Thread 0x7fffc4f7b700 (LWP 17241)  0x0000000000413ce1 in thread_midx_func (obj=0x2fe949d0) at kbm.h:745
  47 Thread 0x7ffff4eed700 (LWP 17240)  0x0000000000413c81 in thread_midx_func (obj=0x2fe948e0) at kbm.h:744
  46 Thread 0x7ffff58ee700 (LWP 17239)  0x0000000000413ce1 in thread_midx_func (obj=0x2fe947f0) at kbm.h:745
  45 Thread 0x7ffff62ef700 (LWP 17238)  0x0000000000413c81 in thread_midx_func (obj=0x2fe94700) at kbm.h:744
  44 Thread 0x7ffe37fff700 (LWP 17237)  0x00000039d2e0b98e in pthread_cond_timedwait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
  43 Thread 0x7ffe3ffff700 (LWP 17236)  0x00000039d2e0b98e in pthread_cond_timedwait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
  42 Thread 0x7ffe47fff700 (LWP 17235)  0x00000039d2e0b98e in pthread_cond_timedwait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
  41 Thread 0x7ffe4ffff700 (LWP 17234)  0x00000039d2e0b98e in pthread_cond_timedwait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
  40 Thread 0x7ffe57fff700 (LWP 17233)  0x00000039d2e0b98e in pthread_cond_timedwait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
  39 Thread 0x7ffe5ffff700 (LWP 17232)  0x00000039d2e0b98e in pthread_cond_timedwait@@GLIBC_2.3.2 ()
---Type <return> to continue, or q <return> to quit---
   from /lib64/libpthread.so.0
  38 Thread 0x7ffe67fff700 (LWP 17231)  0x00000039d2e0b98e in pthread_cond_timedwait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
  37 Thread 0x7ffe6ffff700 (LWP 17230)  0x00000039d2e0b98e in pthread_cond_timedwait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
  36 Thread 0x7ffe77fff700 (LWP 17229)  0x00000039d2e0b98e in pthread_cond_timedwait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
  35 Thread 0x7ffe7ffff700 (LWP 17228)  0x00000039d2e0b98e in pthread_cond_timedwait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
  34 Thread 0x7ffe87fff700 (LWP 17227)  0x00000039d2e0b98e in pthread_cond_timedwait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
  33 Thread 0x7ffe8ffff700 (LWP 17226)  0x00000039d2e0b98e in pthread_cond_timedwait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
  32 Thread 0x7ffe97fff700 (LWP 17225)  0x00000039d2e0b98e in pthread_cond_timedwait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
  31 Thread 0x7ffe9ffff700 (LWP 17224)  0x00000039d2e0b98e in pthread_cond_timedwait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
---Type <return> to continue, or q <return> to quit---
  30 Thread 0x7ffea7fff700 (LWP 17223)  0x00000039d2e0b98e in pthread_cond_timedwait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
  29 Thread 0x7ffeaffff700 (LWP 17222)  0x00000039d2e0b98e in pthread_cond_timedwait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
  28 Thread 0x7ffeb7fff700 (LWP 17221)  0x00000039d2e0b98e in pthread_cond_timedwait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
  27 Thread 0x7ffebffff700 (LWP 17220)  0x00000039d2e0b98e in pthread_cond_timedwait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
  26 Thread 0x7ffec7fff700 (LWP 17219)  0x00000039d2e0b98e in pthread_cond_timedwait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
  25 Thread 0x7ffecffff700 (LWP 17218)  0x00000039d2e0b98e in pthread_cond_timedwait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
  24 Thread 0x7ffed7fff700 (LWP 17217)  0x00000039d2e0b98e in pthread_cond_timedwait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
  23 Thread 0x7ffedffff700 (LWP 17216)  0x00000039d2e0b98e in pthread_cond_timedwait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
  22 Thread 0x7ffee7fff700 (LWP 17215)  0x00000039d2e0b98e in pthread_cond_timedwait@@GLIBC_2.3.2 ()
---Type <return> to continue, or q <return> to quit---
   from /lib64/libpthread.so.0
  21 Thread 0x7ffeeffff700 (LWP 17214)  0x00000039d2e0b98e in pthread_cond_timedwait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
  20 Thread 0x7ffef7fff700 (LWP 17213)  0x00000039d2e0b98e in pthread_cond_timedwait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
  19 Thread 0x7ffefffff700 (LWP 17212)  0x00000039d2e0b98e in pthread_cond_timedwait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
  18 Thread 0x7fff07fff700 (LWP 17211)  0x00000039d2e0b98e in pthread_cond_timedwait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
  17 Thread 0x7fff0ffff700 (LWP 17210)  0x00000039d2e0b98e in pthread_cond_timedwait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
  16 Thread 0x7fff17fff700 (LWP 17209)  0x00000039d2e0b98e in pthread_cond_timedwait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
  15 Thread 0x7fff1ffff700 (LWP 17208)  0x00000039d2e0b98e in pthread_cond_timedwait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
  14 Thread 0x7fff27fff700 (LWP 17207)  0x00000039d2e0b98e in pthread_cond_timedwait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
---Type <return> to continue, or q <return> to quit---
  13 Thread 0x7fff2ffff700 (LWP 17206)  0x00000039d2e0b98e in pthread_cond_timedwait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
  12 Thread 0x7fff37fff700 (LWP 17205)  0x00000039d2e0b98e in pthread_cond_timedwait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
  11 Thread 0x7fff3ffff700 (LWP 17204)  0x00000039d2e0b98e in pthread_cond_timedwait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
  10 Thread 0x7fff47fff700 (LWP 17203)  0x00000039d2e0b98e in pthread_cond_timedwait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
  9 Thread 0x7fff4ffff700 (LWP 17202)  0x00000039d2e0b98e in pthread_cond_timedwait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
  8 Thread 0x7fff56b12700 (LWP 17201)  0x00000039d2e0b98e in pthread_cond_timedwait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
  7 Thread 0x7fff57513700 (LWP 17200)  0x00000039d2e0b98e in pthread_cond_timedwait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
  6 Thread 0x7fff57f14700 (LWP 17199)  0x00000039d2e0b98e in pthread_cond_timedwait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
  5 Thread 0x7fff58915700 (LWP 17198)  0x00000039d2e0b98e in pthread_cond_timedwait@@GLIBC_2.3.2 ()
---Type <return> to continue, or q <return> to quit---
   from /lib64/libpthread.so.0
  4 Thread 0x7ffff75b4700 (LWP 17197)  0x00000039d2e0ef3d in nanosleep () from /lib64/libpthread.so.0
  2 Thread 0x7ffff7ff7700 (LWP 3714)  0x00000039d2ae53e7 in munmap () from /lib64/libc.so.6
* 1 Thread 0x7ffff7ff9700 (LWP 3709)  0x0000000000416072 in index_kbm (kbm=0x69e720, beg=0, end=1325518137,
    ncpu=40) at kbm.h:905

**Comment by chensunefu** [comment]
Thanks for helping me to assemble this big genome.
