### ISSUE TITLE
Separation of contigs by long deletions

### ISSUE THREAD

**Issue by ziczhang** [ruanjue/wtdbg2#241]
Sorry if this is a rudimentary question.
I'm using wtdbg2 to assemble a human genome by Nanopore long reads (40Gbase, about 13x).
I run wtdbg2 as "wtdbg2 -t $THREADS -x ont -g 3G -i $FASTQ -fo $OUTPUT" and did the polishment.
When I mapped both of the contigs and the long reads to a reference human genome, I found some of contigs were separated by long deletions like this figure.
![image](https://user-images.githubusercontent.com/57785667/145347825-353c124e-11eb-41aa-a9f0-9c7f26f973f0.png)

Can you help with this? 

Thanks.

**Comment by ruanjue** [comment]
If there is a heterozygous INDEL, wtdbg2 might fail to merge them, but break into more than one contigs. In fact, I am not quite understanding your exact question.

**Comment by ziczhang** [comment]
Thanks Jue.
I'm just curious about why this is happening though each reads is still connected in these regions, and if my parameters have something wrong, how I can fix it.
But as you said, I should consider heterozygous INDELs.

**Comment by ruanjue** [comment]
Yes, please check INDELS around.
