### ISSUE TITLE
wtpoa-cns状态长时间不更新

### ISSUE THREAD

**Issue by Neo-xbx-00** [ruanjue/wtdbg2#242]
您好，我在使用wtpoa-cns获取.fa文件时，wtpoa-cns一直在运行，但.fa文件已经有12h没有更新了。.fa文件的大小已经超出了我预估的基因组大小，这个时候wtpoa-cns是已经运行完成了吗
![Uploading 捕获.PNG…]()

**Comment by ruanjue** [comment]
wtpoa-cns中有个隐含的BUG我一直没有调试出来，偶尔会有用户遇到，你可以尝试把.lay文件切割成多份（https://github.com/ruanjue/wtdbg2/blob/master/scripts/split_seqs_3.pl），分别运行

**Comment by Neo-xbx-00** [comment]
好的，谢谢您，我尝试一下

**Comment by Neo-xbx-00** [comment]
** PROC_STAT(TOTAL) **: real 6426.662 sec, user 187152.210 sec, sys 3586.970 sec, maxrss 21623464.0 kB, maxvsi
ze 28522856.0 kB
当log文件出现这一行时，是否说明wtpoa-cns已经运行完成呢，使用top等命令已经发现wtpoa-cns停止，但并未传递Done的信号...

> wtpoa-cns中有个隐含的BUG我一直没有调试出来，偶尔会有用户遇到，你可以尝试把.lay文件切割成多份（[https://github.com/ruanjue/wtdbg2/blob/master/scripts/split_seqs_3.pl），分别运行](https://github.com/ruanjue/wtdbg2/blob/master/scripts/split_seqs_3.pl%EF%BC%89%EF%BC%8C%E5%88%86%E5%88%AB%E8%BF%90%E8%A1%8C)

**Comment by ruanjue** [comment]
是的，任务已经结束
