### ISSUE TITLE
Wtdbg2: Parameter -g setting problem

### ISSUE THREAD

**Issue by 17863952296** [ruanjue/wtdbg2#247]
when I run the following command:
wtdbg2 -x ont -g 100m -t 16 -i  ../food_bac_filtered/Cy_nano_nofood_filtered.fastq -fo Cy_nano_100m
wtdbg2 -x ont -g 150m -t 16 -i ../food_bac_filtered/Cy_nano_nofood_filtered.fastq -fo Cy_nano_150m
wtdbg2 -x ont -g 200m -t 16 -i ../food_bac_filtered/Cy_nano_nofood_filtered.fastq -fo Cy_nano_200m
wtpoa-cns -t 16 -i Cy_nano_100m.ctg.lay.gz -o Cy_nano_100m.ctg.fa
wtpoa-cns -t 16 -i Cy_nano_150m.ctg.lay.gz -o Cy_nano_150m.ctg.fa
wtpoa-cns -t 16 -i Cy_nano_200m.ctg.lay.gz -o Cy_nano_200m.ctg.fa
output results: The larger the -g parameter is set, the larger the final genome size (Cy_nano_XXX.ctg.fa) result is
How do I determine the actual genome size of a species?(Denovo assemble: I don't know the genome size)

**Comment by ruanjue** [comment]
`-g` and `-X` are used together to select enough reads. When genome size is unknown, just set `-g` to a large enough number.

**Comment by 17863952296** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Thank you for your reply! 
        Best regardsZiguang Deng
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Jue ***@***.***>
            
        
      
      
        
         Date 
        
        
        9/26/2022 08:55
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [ruanjue/wtdbg2] Wtdbg2: Parameter -g setting problem (Issue #247)
        
      
    
  
  
-g and -X are used together to select enough reads. When genome size is unknown, just set -g to a large enough number.
