### ISSUE TITLE
-i with multiple files doesn't work properly / fails to throw error

### ISSUE THREAD

**Issue by thackl** [ruanjue/wtdbg2#25]
Awesome program, thanks! I came across the following issue, though. The help reads like `-i a.fq b.fq c.fq ...` would be a valid call for multiple read files. And it doesn't throw an error. But if specified like that, wtdbg2 only reads the first read file, and ignores the other files without warning or exception.

 `-i a.fq -i b.fq ...` works. So it would be helpful to have this documented more clearly, and/or have an error thrown on unused extra arguments.

a.fq and b.fq have on read each. But only one is read

```
~software/wtdbg2/wtdbg2 -i a.fq b.fq -o foo
--
-- total memory       65922936.0 kB
-- available          42977240.0 kB
-- 16 cores
-- Starting program: /nobackup1/chisholmlab/software/wtdbg2/wtdbg2 -i a.fq -o foo b.fq
-- pid                     10006
-- date         Wed Oct 24 10:54:02 2018
--
[Wed Oct 24 10:54:03 2018] loading reads
1 reads
[Wed Oct 24 10:54:03 2018] Done, 1 reads, 5000 bp, 19 bins
```

**Comment by thackl** [comment]
Agreed, but `-i *.fq` is just so tempting for multiple files ;). Thanks for the fix.

**Comment by ruanjue** [comment]
Added a nasty way to support -i *.fq in command line. Wtdbg2 will check whether the 'file' in unused arguments exists, if yes, adds it to input file list.
