### ISSUE TITLE
C++/ Python  library 

### ISSUE THREAD

**Issue by Lionward** [ruanjue/wtdbg2#257]
Since I have too many separate small genomic regions that I want to assemble, I would like to run the wtdbg2 assembler internally using c++ or maybe a python library without the need to have a fasta file, is it possible to do that?

**Comment by ruanjue** [comment]
I have no plan to develop such library. One way is utilizing your memory filesystem, e.g /dev/shm, to generate fasta and output directly to RAM memory.
