### ISSUE TITLE
"make install" should depend on $(PROGS)

### ISSUE THREAD

**Issue by tseemann** [ruanjue/wtdbg2#27]
```
install:
	cp -fvu $(PROGS) $(BIN)
```

should be

```
install: $(PROGS)
	cp -fvu $(PROGS) $(BIN)
```

so that `make install` will build the binaries.

**Comment by ruanjue** [comment]
Thanks!
https://github.com/ruanjue/wtdbg2/commit/1397c43e553752e6a2737b7939c57010ebea5017
