### ISSUE TITLE
Version 2.1 now in Homebrew Science

### ISSUE THREAD

**Issue by tseemann** [ruanjue/wtdbg2#32]
```
brew install brewsci/bio/wtdbg2
```

🎉 New formula wtdbg2 in Brewsci/bio for Linux!
ℹ️ Fuzzy de Bruijn Graph long read assembler
🍺 brew install brewsci/bio/wtdbg2
🏡 https://github.com/ruanjue/wtdbg2
🔬 https://github.com/brewsci/homebrew-bio
🐧 http://linuxbrew.sh #bioinformatics
```

**Comment by ruanjue** [comment]
Thanks!
