### ISSUE TITLE
Reads longer than 256kb

### ISSUE THREAD

**Issue by nickloman** [ruanjue/wtdbg2#34]
Hi there

Would it be possible to implement support for reads longer than 256kb (nanopore) ? I expect such reads should contribute a great deal to assembly of difficult repeats. At the moment we have reads up to 2.5Mb, but I expect longer reads may be possible soon, so perhaps some head room can be built into wtdbg2 to allow for technology improvements.

Thank you very much for wtdbg2!

Best
Nick

**Comment by lh3** [comment]
See also #33.

**Comment by ruanjue** [comment]
Dear Nick,

Yes, there is still much room to allow increasing read length in wtdbg2. We are preparing to enlarge the maximum of read length, please have a wait. I will close this issue after released the `huge reads` version.

Thanks for suggestions!
Jue

**Comment by Lordhooze** [comment]
Hello,  prof. ruanjue
I have ultra-long reads which are more than 256K
what parameters should i use for these reads.
Thanks

**Comment by ruanjue** [comment]
Have a try with `-x ont -g <genome_size>`.

**Comment by ruanjue** [comment]
https://github.com/ruanjue/wtdbg2/tree/huge-genome

New version 2.3 has no limitation on read length and read count. I have tested it on severel genomes. Any problem, please discuss it in this thread.

Jue

**Comment by Lordhooze** [comment]
ok, i will use version 2.3.
thank you very much

**Comment by Lordhooze** [comment]
[hujiaxiang@localhost wtdbg2.3]$ make  
gcc -g3 -W -Wall -Wno-unused-but-set-variable -O4 -DTIMESTAMP="Sun Dec 23 19:29:33 HKT 2018" -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -mpopcnt -msse4.2 -o kbm2 kbm.c ksw.c -lm -lrt -lpthread -lz
kbm.c:20:19: fatal error: kbm-x.h: No such file or directory
 #include "kbm-x.h"
                   ^
compilation terminated.
make: *** [kbm2] Error 1

**Comment by Lordhooze** [comment]
[hujiaxiang@localhost wtdbg2.3]$ make 
gcc -g3 -W -Wall -Wno-unused-but-set-variable -O4 -DTIMESTAMP="Sun Dec 23 21:00:56 HKT 2018" -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -mpopcnt -msse4.2 -o kbm2 kbm.c ksw.c -lm -lrt -lpthread -lz
gcc -g3 -W -Wall -Wno-unused-but-set-variable -O4 -DTIMESTAMP="Sun Dec 23 21:01:05 HKT 2018" -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -mpopcnt -msse4.2 -o wtdbg2 wtdbg.c ksw.c -lm -lrt -lpthread -lz
In file included from wtdbg.c:20:0:
wtdbg.h:23:19: fatal error: kbm-x.h: No such file or directory
 #include "kbm-x.h"
                   ^
compilation terminated.
make: *** [wtdbg2] Error 1

**Comment by Lordhooze** [comment]
file kbm-x.h ; kbmpoa-x.h; are missing

**Comment by ruanjue** [comment]
Fixed, please try again.

**Comment by gentlewasp** [comment]
Hi Jue, I can not install the wtdbg2.3 with following error. I need your help. Thanks. shujun

[@localhost wtdbg2.3]$ make
gcc -g3 -W -Wall -Wno-unused-but-set-variable -O4 -DTIMESTAMP="2019年 01月 03日 星期四 08:38:58 CST" -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -mpopcnt -msse4.2 -o kbm2 kbm.c ksw.c -lm -lrt -lpthread -lz
kbm.c: In function ‘kbm_main’:
kbm.c:475:100: warning: passing argument 11 of ‘init_ctgcns’ makes pointer from integer without a cast [-Wint-conversion]
     maln->cc = init_ctgcns(kb, iter_kbmblock, info_kbmblock, 1, 1, 1, maln->corr_max, 200, 100, 1, 96, 2, -5, -2, -4, -1, 16, 3, 0.5, 512);
                                                                                                    ^
In file included from kbmpoa.h:24:0,
                 from kbm.c:21:
wtpoa.h:190:23: note: expected ‘POGPar * {aka struct <anonymous> *}’ but argument is of type ‘int’
 static inline CTGCNS* init_ctgcns(void *obj, iter_cns_block itercns, info_cns_block infocns, u4i ncpu, int shuffle_rds, u4i seqmax, int winlen, int winmin, int fail
                       ^
kbm.c:475:16: error: too many arguments to function ‘init_ctgcns’
     maln->cc = init_ctgcns(kb, iter_kbmblock, info_kbmblock, 1, 1, 1, maln->corr_max, 200, 100, 1, 96, 2, -5, -2, -4, -1, 16, 3, 0.5, 512);
                ^
In file included from kbmpoa.h:24:0,
                 from kbm.c:21:
wtpoa.h:190:23: note: declared here
 static inline CTGCNS* init_ctgcns(void *obj, iter_cns_block itercns, info_cns_block infocns, u4i ncpu, int shuffle_rds, u4i seqmax, int winlen, int winmin, int fail
                       ^
make: *** [Makefile:24: kbm2] Error 1

**Comment by ruanjue** [comment]
Updated.

**Comment by gentlewasp** [comment]
Thanks, it works.
