### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by FAFUyangyang** [ruanjue/wtdbg2#35]
^Cmake: *** [kbm] Interrupt

I have such installation problems as follow.I hope you can help me! Thank you.

**Comment by tseemann** [comment]
We need more information.

Or, you could install using Hombrew via `brew install brewsci/bio/wtdbg2`

**Comment by ruanjue** [comment]
It looks like you have killed it when compiling. Please try again.

**Comment by FAFUyangyang** [comment]
> We need more information.
> 
> Or, you could install using Hombrew via `brew install brewsci/bio/wtdbg2`

I meet this information as follow，because there are too much，so I picked a part.
……
list.h:552:35: note: in expansion of macro ?.efine_list_core?
 #define define_list(name, e_type) define_list_core(name, e_type, size_t, 0xFFFFFU)
                                   ^
kbm.h:544:1: note: in expansion of macro ?.efine_list?
 define_list(tmpbmerv, kbm_tmp_bmer_t);
 ^
kbm.c: In function ?.bm_main?.
kbm.c:254:3: warning: implicit declaration of function ?.trcasecmp?.[-Wimplicit-function-declaration]
   if(strcasecmp("start", argv[optind]) == 0) server = 1;
   ^
In file included from kbm.h:26:0,
                 from kbm.c:20:
filereader.h: In function ?.eadtable_filereader?.
filereader.h:514:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make: *** [kbm] Error 1

**Comment by ruanjue** [comment]
Please attach the full message by dragging and dropping files.

Also please pay attend to the Garbled message, such as `.?efine_list_core`, should be caused by unicode.

**Comment by ammodramus** [comment]
I am also having this issue. I've attached the complete STDERR from `make`.
[errormsg.txt](https://github.com/ruanjue/wtdbg2/files/2535474/errormsg.txt)

**Comment by ammodramus** [comment]
Adding either `#include <string.h>` or `#include "string.h"` to `kbm.h` fixed this for me. I didn't look closely at the difference between the system `string.h` and this program's `string.h`, so maybe the developers can decide which is correct to include here.

**Comment by lh3** [comment]
See also #36. For now, you can use the precompiled binary in the [release page](https://github.com/ruanjue/wtdbg2/releases), or install via bioconda.

**Comment by ruanjue** [comment]
string.h will be renamed to chararray.h in next commit.
