### ISSUE TITLE
Unable to install on linux x64

### ISSUE THREAD

**Issue by ggstatgen** [ruanjue/wtdbg2#36]
Hi

Thanks for developing wtdbg2. I cloned the repository but am unable to compile the code.  I'm on 64bit linux,  gcc --version is 7.3.0. The following is the output of `make`

[error.txt](https://github.com/ruanjue/wtdbg2/files/2524669/error.txt)

I wonder if it's a missing library problem. In your `Makefile` you request

`GLIBS=-lm -lrt -lpthread`

Not sure if these are present in my system.

Any help appreciated.

Best wishes,

**Comment by ruanjue** [comment]
Please have a look at those
https://github.com/ruanjue/smartdenovo/issues/17#issuecomment-396851886
https://github.com/ruanjue/smartdenovo/issues/17#issuecomment-396855819
https://github.com/ruanjue/smartdenovo/issues/17#issuecomment-396861401

Most possible problem is you had inclued `.` in GCC search path.

**Comment by ggstatgen** [comment]
Hi 

Thanks for this. No `.` in GCC search path. However, if I set

`C_INCLUDE_PATH=""`

the program compiles. Any idea? Thanks!

**Comment by ruanjue** [comment]
Try `echo | gcc -E -Wp,-v -`. 

https://github.com/ruanjue/smartdenovo/issues/17#issuecomment-396852811

**Comment by richardmleggett** [comment]
I also had this problem. Took me ages to figure out that GCC had been compiled with . in the search path. Can you consider renaming your string.h to a different name? That would help avoid conflict with the standard library file of the same name...

**Comment by ruanjue** [comment]
Ok, will be updated in next commit.

**Comment by ruanjue** [comment]
https://github.com/ruanjue/wtdbg2/commit/6444781175995618c9286788337d4ff35b28e4e1
updated.

**Comment by richardmleggett** [comment]
Thank you! And thanks for providing this software.

**Comment by ggstatgen** [comment]
Yep thanks!
