### ISSUE TITLE
wtdbg2 hangs when creating *.1.dot.gz

### ISSUE THREAD

**Issue by claczny** [ruanjue/wtdbg2#37]
Hi,

thanks for this very nice software! It is really fast and consumes (rather) little resources.

When I try the current version in the master-branch (f020cb62325e5dcc316860fc435e5bafb5ab7e70), it seems to hang at the output step of the `*.1.dot-gz' file:

```
Sun Nov  4 11:53:31 CET 2018
--
-- total memory      131916384.0 kB
-- available         115516468.0 kB
-- 28 cores
-- Starting program: apps/software/wtdbg2_git/wtdbg2 -t 28 -i results/binning/kraken2/reads/GridION-Zymo_CS_BB_LSK109.Saccharomyces_cerevisiae.fq -fo results/assembly/wtdbg2-L_1000/per_bin/GridION-Zymo_CS_BB_LSK109.Saccharomyces_cerevisiae -L 1000
-- pid                     18416
-- date         Sun Nov  4 11:53:31 2018
--
[Sun Nov  4 11:53:31 2018] loading reads
0 reads
[Sun Nov  4 11:53:31 2018] Done, 0 reads, 0 bp, 0 bins
** PROC_STAT(0) **: real 0.003 sec, user 0.000 sec, sys 0.000 sec, maxrss 972.0 kB, maxvsize 79856.0 kB
[Sun Nov  4 11:53:31 2018] generating nodes, 28 threads
0 reads|total hits 0
** PROC_STAT(0) **: real 0.003 sec, user 0.000 sec, sys 0.000 sec, maxrss 972.0 kB, maxvsize 79856.0 kB
[Sun Nov  4 11:53:31 2018] chainning ...  0 hits into 0
[Sun Nov  4 11:53:31 2018] picking best 500 hits for each read ... 0 hits
[Sun Nov  4 11:53:31 2018] clipping ... -nan% bases
[Sun Nov  4 11:53:31 2018] generated 0 regs
[Sun Nov  4 11:53:31 2018] sorting regs ...  Done
[Sun Nov  4 11:53:31 2018] generating intervals ...  0 intervals
[Sun Nov  4 11:53:31 2018] selecting important intervals from 0 intervals
[Sun Nov  4 11:53:31 2018] Intervals: kept 0, discarded 0
** PROC_STAT(0) **: real 0.003 sec, user 0.000 sec, sys 0.000 sec, maxrss 972.0 kB, maxvsize 79856.0 kB
[Sun Nov  4 11:53:31 2018] Done, 0 nodes
[Sun Nov  4 11:53:31 2018] output "results/assembly/wtdbg2-L_1000/per_bin/GridION-Zymo_CS_BB_LSK109.Saccharomyces_cerevisiae.1.nodes". Done.
[Sun Nov  4 11:53:31 2018] median node depth = 0
[Sun Nov  4 11:53:31 2018] masked 0 high coverage nodes (>200 or <3)
[Sun Nov  4 11:53:31 2018] masked 0 repeat-like nodes by local subgraph analysis
[Sun Nov  4 11:53:31 2018] generating edges
[Sun Nov  4 11:53:31 2018] Done, 1 edges
[Sun Nov  4 11:53:31 2018] output "results/assembly/wtdbg2-L_1000/per_bin/GridION-Zymo_CS_BB_LSK109.Saccharomyces_cerevisiae.1.reads". Done.
[Sun Nov  4 11:53:31 2018] output "results/assembly/wtdbg2-L_1000/per_bin/GridION-Zymo_CS_BB_LSK109.Saccharomyces_cerevisiae.1.dot.gz".
```

Clearly, there is something strange with this input, e.g.,
> [Sun Nov  4 11:53:31 2018] loading reads
> 0 reads

which might explain this unexpected behavior.

Yet, I would expect a program to fail gracefully with some info message rather than just hang ;)
Since the compression appears to have been recently added (after v2.2, which is not yet tagged/released?), I assume this is an easy-to-fix bug/non-robust-feature.

The input is a set of reads from https://github.com/LomanLab/mockcommunity (most likely Release 1 as I downloaded it several weeks ago, and *not* the currently shown Release 2) binned by using Kraken2.

Hence, this is an attempt to see how per-bin assembly would work instead of a meta-assembly.
For several other bins, this step worked fine.

TIA for looking into this.

Best,

Cedric

**Comment by ruanjue** [comment]
Thanks Cedric, I found the bug and fixed at https://github.com/ruanjue/wtdbg2/commit/768b362e69747c24292ae9ef392c962ca99e8262

BTW, when assembling the zymo-comm dataset, have a try with -p 19 -S 2 -A --node-max 1000, it resulted in a good result, previously using wtdbg-1.2.8.
