### ISSUE TITLE
wtdbg-dot2gfa.pl does not work with contig dot file

### ISSUE THREAD

**Issue by nickloman** [ruanjue/wtdbg2#39]
Hi there

I would like to produce a contig GFA to inspect in Bandage. I found the wtdbg-dot2gfa.pl script but it only seems to work on the sequence graph (3.dot) rather than the contig graph. Is it possible to modify it to work with contigs?

Best
Nick

**Comment by ruanjue** [comment]
Recently,  I modified the script to support prefix.ctg.dot. If it still doesn't not work, please let me know.

**Comment by nickloman** [comment]
Great! Sorry I didn't spot that before raising the issue, I was using an older commit.
