### ISSUE TITLE
For the "ont" preset, change -L to 5000

### ISSUE THREAD

**Issue by lh3** [ruanjue/wtdbg2#44]
On the several ONT datasets at my hand, the N50 is not much longer than 10kb. Using "-L10000" would discard too many reads. BTW, I have changed "sq" preset to "-p0 -k15". You changed the text, but didn't change the actual setting. See 9ab7df6.

**Comment by ruanjue** [comment]
Yes, I forgot to change the code. Thanks!

As there is new option -X 50 by default, -L5000 should be good for all.

**Comment by ruanjue** [comment]
git pushed！
