### ISSUE TITLE
polish error

### ISSUE THREAD

**Issue by gentlewasp** [ruanjue/wtdbg2#49]
I got an error in polish step using the new release of version 2.2. Is it a bug or caused by wrong parameters.
[@localhost canu1.8_wtdbg2]$ wtpoa-cns -t $cores -d tp.canu.wtdbg.ctg.lay1.fa -i tp.canu.wtdbg.ctg.lay2.map.sam -fo tp.canu.wtdbg.ctg.lay2.fa
-- total memory      396031892.0 kB
-- available         334581040.0 kB
-- 120 cores
-- Starting program: wtpoa-cns -t 24 -d tp.canu.wtdbg.ctg.lay1.fa -i tp.canu.wtdbg.ctg.lay2.map.sam -fo tp.canu.wtdbg.ctg.lay2.fa
-- pid                    100642
-- date         Mon Dec  3 15:16:59 2018
wtpoa-cns: wtpoa.h:472: init_samblock: Assertion `bstep <= bsize && 2 * bstep >= bsize' failed.

**Comment by ruanjue** [comment]
https://github.com/ruanjue/wtdbg2/commit/aad2f20f896c6ea93ac33b7c4549163942b3bc07
Please have a test with the updated wtpoa-cns.

**Comment by gentlewasp** [comment]
Hi Jue,
Thanks for the update. However, the same error occurred in my analyses, as below.
wtpoa-cns: wtpoa.h:472: init_samblock: Assertion `bstep <= bsize && 2 * bstep >= bsize' failed.
Thanks for your help.
shujun

**Comment by ruanjue** [comment]
https://github.com/ruanjue/wtdbg2/commit/c3fb7d0e4607f3a8796d59eaed14058ac37d3f0a
I had tested this update on e.coli.

**Comment by gentlewasp** [comment]
Hi Jue, it works well. Thanks very much. shujun
