### ISSUE TITLE
how to set -K for repeats

### ISSUE THREAD

**Issue by leleory** [ruanjue/wtdbg2#52]
Hi Jue,
Can you advise what is the best way of setting -K to filter possibly repeat derived kmers?
E.g. with 30X read coverage if I want to filter repeats which are present at least 10 or more copies should I set -K to 300? 
Also, assuming that 40% of the genome made up by repeats I assume that the fraction of the total repeat driven kmer count should be set to 0.4? 
So would the two above be captured as -K 300.4? 
Do I interpret the -K parameter correctly?
Thank you,
Lel

**Comment by ruanjue** [comment]
No, please reminder of high error rate. Excepting huge genomes, I think -K 1000.05 is good enough for most assemblies in performance and result.
