### ISSUE TITLE
support for ".fasta"

### ISSUE THREAD

**Issue by rlorigro** [ruanjue/wtdbg2#54]
I noticed that if you use the flag 

`-o output_file.fasta` 

No output is generated. But if you use either of the following:

`-o output_file`
`-o output_file.fa` 

Then the corresponding file is generated.

**Comment by rlorigro** [comment]
yes

**Comment by ruanjue** [comment]
Both work well on my computer, could you give me more information on your test?

**Comment by rlorigro** [comment]
ah just kidding it was a stupid mistake. I was running wtdbg2 from a python script and forgot that I told my IDE to ignore fasta files 🧠

**Comment by ruanjue** [comment]
never mind.
