### ISSUE TITLE
Error when input *fq and *fa files simultaneously.

### ISSUE THREAD

**Issue by zhouqiansolab** [ruanjue/wtdbg2#56]
The wtdbg can accept files in *fa or *fq format and allows multiple files following the -i. But when I input files in different format, like `-i s1.fa.gz -i s2.fq.gz` , the program  ended  with "core dump" at the "loading reads" stage.  Can wtdbg support the *fa  and *fq files in the same run?

**Comment by ruanjue** [comment]
Please test whether the bug came from gz, or mixture of fasta and fastq. It will be kind to offer me a small test data to reproduce the bug. 

Jue

**Comment by zhouqiansolab** [comment]
In my test,  `-i s1.fasta.gz -i s2.fastq.gz` and `-i s1.fasta -i s2.fastq` both  ended with "core dump", only `-i s1.fasta -i s2.fasta` worked.

**Comment by ruanjue** [comment]
Thanks for the information. I will test mixture seq formats.

**Comment by ruanjue** [comment]
I found the problem, but it looks hard to fix it. I will state it in https://github.com/ruanjue/wtdbg2#limitations .

Thanks for the BUG report.

**Comment by zhouqiansolab** [comment]
Thanks for the reply. 
I think its not a big problem and  users can easily  avoid it  by choosing proper input files.
