### ISSUE TITLE
No contig output for local assembly

### ISSUE THREAD

**Issue by GuillaumeHolley** [ruanjue/wtdbg2#59]
Hello,

I am trying to assemble the ONT reads overlapping a specific region of the human genome and unfortunately, in this region, I end up with only 4 reads (3 of which have a length below 5 kbp). After running wtdbg2 and wtpoa-cns, I get no contig.

The end of wtdbg2 log indicates:
```
searched 1 contigs
Estimated:
output 0 contigs
```

and wtpoa-cns log indicates:
```
0 contigs 1 edges
```

I am using the following parameters for the assembly:
```
-p 0 -k 15 -AS 1 --edge-min 1 --rescue-low-cov-edges
```

Do you know what is happening here (too low coverage?) and if I can do something to solve the issue (some parameters I didn't think about)? I also tried to decrease `-k` and `-l` without success.

Thank you for your help.

Guillaume

**Comment by ruanjue** [comment]
Please have a look at `--ctg-min-length`, `--ctg-min-nodes` in `wtdbg2 --help`.  Since your input was 4 reads, please generate a assembly-graph image from `prefix`.3.dot using `dot -Tpdf -O ...`. If you have question about the dot graph, please contact me.

**Comment by GuillaumeHolley** [comment]
Thank you for your input. Both parameters helped a lot for a few use-cases I had.
