### ISSUE TITLE
Assembly of 2 reads, 1 or 0 contig depending on number of threads

### ISSUE THREAD

**Issue by GuillaumeHolley** [ruanjue/wtdbg2#61]
Hello,

I am in the situation where I try to assemble exactly 2 reads using the following parameters:
```
-p 0 -k 15 -AS 1 -L 0 --ctg-min-nodes 1 -e 1 --rescue-low-cov-edges
```

With parameter `-t` less than or equal to 4, I obtain one contig. However, parameter `-t` above 4 gives me **most of the time** no contig and **sometimes** one contig. From the log, it seems that the "earliest" difference I can spot is that after creating the nodes, the edge generation steps creates sometimes 191 edges and sometimes 1 edge, resulting in 1 and 0 contig in output respectively. I am using the latest version of wtdbg2 (2.3) but I had the same issue with version 2.2. It doesn't seem to depend on the reads as I tried different non-overlapping sets of 2 reads mapping to different locations of chromosome 1. Also, I always get a contig when I add a 3rd read in input.

Thank you for your help.

Guillaume

**Comment by ruanjue** [comment]
How about the difference in `<prefix>.alignments.gz` using different `-t`?

**Comment by GuillaumeHolley** [comment]
Unfortunately, I cannot reproduce this behavior today.

I am working on a compute cluster and the machine I use today is different than the one from yesterday (I don't know to which one I was connected yesterday). Unfortunately (or fortunately?), after trying the same steps, I have now a consistent behavior on this machine: For different sets of 2 reads, I always obtain the same output (1 or 0 contig) over multiple consecutive runs of wtdbg2, doesn't matter the number of threads used.

**Comment by ruanjue** [comment]
OK. When you catch it again, please have a look at the alignments.

**Comment by GuillaumeHolley** [comment]
Thanks, will do.
I close the issue for now and will re-open it if I encounter this problem again.
