### ISSUE TITLE
trace segments/sequences in contigs from dot file

### ISSUE THREAD

**Issue by MichelMoser** [ruanjue/wtdbg2#62]
Hi, 

Is it possible to visually traceback (with bandage for example) which path was taken in the .dot.gz files or converted gfa files (i used wtdbg-dot2gfa.pl) for creating the final contigs by wtdbg-cns?

Segments in the dot.gz file have names starting with F1, F2, F2... . But in the .lay.gz file are segments with start S00011.. . So i dont know how they refer to the F segments in .dot.gz. 

I would like to investigate assebmly graphs to detect problematic regions of assembly and possibly detect segmental duplications in fish genomes. 

Thank you, 
Michel

**Comment by ruanjue** [comment]
Hi,

There is a file named `<prefix>.events`. You will find the trace information like this
```sh
ctg3        F71         -           0
ctg3        F3          -           5888
ctg3        F45         +           838656
```
```sh
OUTPUT_CTG  ctg3 -> ctg4 nodes=767 len=845056
```

Best,
Jue

**Comment by MichelMoser** [comment]
Hi Jue, 

Thank you for the information. And the difference between
``` 
OUTPUT_CTG      ctg0 -> ctg1 nodes=58707 len=66842880
```
 and actual length of contig in ctg.lay.fa
```
>ctg1 len=67714918
```
is due to wtdbg2-cns adding or removing some bases when doing consensus calling?

**Comment by ruanjue** [comment]
Yes, `len=66842880` is estimated by raw read length (select one from a group), `len=67714918` is the length of consensus seuqence.
