### ISSUE TITLE
no kmer peak value during runing wtdbg2,how to change the parameter of  -k, -p, and -K

### ISSUE THREAD

**Issue by feiyu007** [ruanjue/wtdbg2#63]
|
|
|
|
|
|
|
|
|
|
|
||
||
||
||
||
||
||
|||
|||
|||
||||
||||
||||||
|||||||||
||||||||||||||||
||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
**********************     1 - 201    **********************
Quatiles:
   10%   20%   30%   40%   50%   60%   70%   80%   90%   95%
     2     3     6    12    21    34    66   166   550  1569
# If the kmer distribution is not good, please kill me and adjust -k, -p, and -K

**Comment by ruanjue** [comment]
If you are using '-x rs', the distribution is ok.
