### ISSUE TITLE
Output alternative contigs?

### ISSUE THREAD

**Issue by fangli08** [ruanjue/wtdbg2#64]
Hi,
May I ask if wtdbg2 could output alternative contigs? (e.g. the other haplotype?)

**Comment by ruanjue** [comment]
Cannot get the alternative bases in wtdbg2. To get a better performance in speed, wtdbg2 cannot distinguish similarity difference of two alignments at most time.

I have a plan to distinguishing haplotypes in coming wtdbg3, maybe one year later.

Jue

**Comment by fangli08** [comment]
Thank you. I don't mean alternative bases that are SNPs or small indels, but large structural variants that have a differnt path in the graph.

**Comment by ruanjue** [comment]
WTDBG2 will break into unitigs when has alternative paths.

**Comment by fangli08** [comment]
So will the unitigs be output ?

**Comment by ruanjue** [comment]
Have a look at `<prefix>.frg.nodes`. Actually, contigs from wtdbg2 will break at multilple branches too.
