### ISSUE TITLE
Specific version of samtools ?

### ISSUE THREAD

**Issue by bitcometz** [ruanjue/wtdbg2#65]
hello,
minimap2 -t 16 -x map-pb -a prefix.ctg.fa reads.fa.gz | samtools view -Sb - >prefix.ctg.map.bam
samtools sort prefix.ctg.map.bam prefix.ctg.map.srt
samtools view prefix.ctg.map.srt.bam | ./wtpoa-cns -t 16 -d prefix.ctg.fa -i - -fo prefix.ctg.2nd.fa

Does wtdbg require specific version of samtools?
I used Version: 1.3 and it generate "core" file.

1 contigs 100 edges /job_scripts/369797: line 10:  2222 Broken pipe             /samtools view Ath.ctg.lay.map.srt.bam
      2223 Segmentation fault      (core dumped)

Best

**Comment by ruanjue** [comment]
It should be caused by segfault of wtpoa-cns, but not samtools.
