### ISSUE TITLE
Parameters to change for high heterozygosity

### ISSUE THREAD

**Issue by lstevens17** [ruanjue/wtdbg2#66]
Hello, 

One of my ONT datasets is from a **very** heterozygous nematode genome. Ideally, I'd like to end up with a haploid assembly. With Canu, you typically achieve this by increasing the corrected error rate parameter to allow for a larger number of differences between reads/overlaps. 

Do you have any suggestions for which parameters within wtdbg2 to change/play with in order to collapse heterozygosity? The default parameters in wtdbg2 yield an assembly with a larger than expected span, suggesting haplotypes are being separated.

Thanks for your help, 

Lewis

**Comment by ruanjue** [comment]
Usually, wtdbg2 collapses heterozygosity. In your case, please try to decrease `-k/-p` and use `-S 2` to find more overlaps between less identity sequences. It will comsume more RAM and take more time.

Best,
Jue

**Comment by lstevens17** [comment]
Thanks for this - will give it a go! 

Lewis
