### ISSUE TITLE
good assemblies with low kmer coverage

### ISSUE THREAD

**Issue by MichelMoser** [ruanjue/wtdbg2#69]
Hi, 

When experimenting with different coverage cutoffs of nanopore data, i seem to be getting best assemblies with very low average kmer coverage (5 x) and very right-skewed kmer histograms. 

Is there an explanation for this?

Also i see a drop in assembly N50 when adding more data then 20x of ONT data but almost no change in total assembly size.

Is more data just confusing the fuzzy Bruijn graph?

Thanks, 
Michel

**Comment by ruanjue** [comment]
There was a line in log message, like `KEY PARAMETERS: ...`. Please check whether it differed among your tests. If it still is confused, please send me the log files to me ruanjue(AT)gmail.com, thanks!

Jue
