### ISSUE TITLE
Parameters for low-coverage ultra-long ONT reads

### ISSUE THREAD

**Issue by glogsdon1** [ruanjue/wtdbg2#72]
Hi Jue/Heng,

I have 10x coverage of ultra-long ONT reads (N50 ~150 kb). I tried running wtdbg2 (version 2.3) on these reads with the following parameters: -x ont -g 3.2g -S 2 -A -e 2. Unfortunately, I got a low contig N50 of ~750 kb. Can you recommend parameters to change to improve the contig N50?

Thanks,
Glennis

**Comment by ruanjue** [comment]
I have no experience on such low coverage, maybe you can play with `--no-read-clip`, `--aln-dovetail`.
