### ISSUE TITLE
Support for local assembly?

### ISSUE THREAD

**Issue by OscarAspelin** [ruanjue/wtdbg2#73]
Hi, is it possible to perform local assemblies using wtdbg2? Say that I have 30 reads that have been mapped to a specific gene, would it be possible to do a local assembly of just those reads?

**Comment by ruanjue** [comment]
I am not sure. But please pay attention to `--tidy-reads`, `--aln-noskip`, `--edge-min`, `--bubble-step`, `--tip-step`, `--ctg-min-length`, `--ctg-min-nodes`, and `--no-read-clip`. Default values were set for whole genome assembly, need to be changed, you can find them using `wtdbg2 --help`. 

Good luck!
