### ISSUE TITLE
Unstable wtpoa-cns ？

### ISSUE THREAD

**Issue by bitcometz** [ruanjue/wtdbg2#74]
Hello，
I tried the wtpoa-cns to do the polishing according to the guidance and I found 
it is unstable.
Sometimes I can finish the polishing, but sometimes I cannot, for example:

-- Starting program: ./wtpoa-cns -t 16 -d ./sample.1st.fa -i - -fo ./paozi.fa
-- pid                     27526
-- date         Fri Mar  1 08:57:28 2019
--
1 contigs 100 run.sh: line 16: 27525 Broken pipe

./samtools view ./sample.ctg.lay.map.srt.bam
     27526 Segmentation fault      (core dumped) | ./wtpoa-cns -t 16 -d ./sample.1st.fa -i - -fo ./sample.fa

However, there may be too little LOG information to find the bug.

Thanks!

**Comment by ruanjue** [comment]
I have got a test data (one contig's lay file)  from UG to debug wtpoa-cns, hope those two cases caused by the same bug. If you can locate the error contig, please send me a small test dataset.

**Comment by bitcometz** [comment]
Thanks, I got the error message quickly when I ran wtdbg-cns, So I think the error contig is the first contig among the contigs. Later, I will send the contig file and the related bam file to your mail:
ruanjue.big(AT)qq.com

Best

**Comment by ruanjue** [comment]
Thanks for the valuable test data. Please find the fixed version at https://github.com/ruanjue/wtdbg2/commit/84795141d3770dda8d016c6a22e967e5b68a88f8 .
