### ISSUE TITLE
Suggestion for 3G repetitive plant genome assembly with high heterozygosity

### ISSUE THREAD

**Issue by bitcometz** [ruanjue/wtdbg2#75]
Hello,

I used the wtdbg2 to do the assembly of 3G repetitive plant genome assembly with high heterozygosity based on 195G ONT data (the minimal reads length is > 19kbp).

The parameters for this genome assembly:
for kbm alignment: -m 400 -p 19 -k 0 -S 2
for wtdbg assembly: 
-A --node-drop 0.20 --node-len 2304[or 1536] --node-max 200 -s 0.05 -e 3 -i  
--rescue-low-cov-edges --no-read-length-sort --aln-dovetail 9216 [or -1]

I tried several rounds of assembly with the optional parameters and the following best results:
--
-- total memory      131861660.0 kB
-- available         128012780.0 kB
-- 32 cores
-- Starting program: ./wtdbg2 -A --node-drop 0.20 --node-len 2304 --node-max 200 -s 0.05 -e 3 -i ./filt.alg.fasta --load-alignments ./filt.alg -t 10 -fo ./sample --rescue-low-cov-edges --no-read-length-sort --aln-dovetail 9216
-- pid                     21322
-- date         Sat Mar  2 18:38:06 2019
--
[Sat Mar  2 18:38:06 2019] loading reads
5377630 reads
[Sat Mar  2 18:50:00 2019] Done, 5377630 reads (>=0 bp), 144239487302 bp, 560757993 bins
** PROC_STAT(0) **: real 713.985 sec, user 377.630 sec, sys 114.470 sec, maxrss 42134824.0 kB, maxvsize 48410992.0 kB
KEY PARAMETERS: -k 0 -p 21 -K 1000.049988 -A -S 4.000000 -s 0.050000 -g 0 -X 50.000000 -e 3 -L 0
[Sat Mar  2 18:50:00 2019] loading alignments from "./filt.alg"
125100874 lines, 118125322 hits
** PROC_STAT(0) **: real 1320.203 sec, user 1009.970 sec, sys 156.260 sec, maxrss 47599148.0 kB, maxvsize 54850404.0 kB
[Sat Mar  2 19:00:06 2019] clipping ... 14.96% bases
[Sat Mar  2 19:00:12 2019] generating regs ... 707962653
[Sat Mar  2 19:02:32 2019] sorting regs ...  Done
[Sat Mar  2 19:02:50 2019] generating intervals ...  49228947 intervals
[Sat Mar  2 19:02:57 2019] selecting important intervals from 49228947 intervals
[Sat Mar  2 19:06:43 2019] Intervals: kept 2473989, discarded 46754958
** PROC_STAT(0) **: real 1717.622 sec, user 1866.530 sec, sys 539.360 sec, maxrss 59409760.0 kB, maxvsize 96748800.0 kB
[Sat Mar  2 19:06:43 2019] Done, 2473989 nodes
[Sat Mar  2 19:06:43 2019] output "sample.1.nodes". Done.
[Sat Mar  2 19:07:00 2019] masked 872 high coverage nodes (>200 or <3)
[Sat Mar  2 19:07:06 2019] masked 128650 repeat-like nodes by local subgraph analysis
[Sat Mar  2 19:07:06 2019] generating edges
[Sat Mar  2 19:07:52 2019] Done, 22158288 edges
[Sat Mar  2 19:07:52 2019] output "sample.1.reads". Done.
[Sat Mar  2 19:08:10 2019] output "sample.1.dot.gz". Done.
[Sat Mar  2 19:08:36 2019] graph clean
[Sat Mar  2 19:08:41 2019] rescued 72366 low cov edges
[Sat Mar  2 19:08:42 2019] deleted 716 binary edges
[Sat Mar  2 19:08:42 2019] deleted 285907 isolated nodes
[Sat Mar  2 19:08:47 2019] cut 630734 transitive edges
[Sat Mar  2 19:08:47 2019] output "sample.2.dot.gz". Done.
[Sat Mar  2 19:10:15 2019] 114196 bubbles; 250492 tips; 870 yarns;
[Sat Mar  2 19:10:16 2019] deleted 214991 isolated nodes
[Sat Mar  2 19:10:16 2019] output "sample.3.dot.gz". Done.
[Sat Mar  2 19:10:20 2019] cut 24554 branching nodes
[Sat Mar  2 19:10:20 2019] deleted 3644 isolated nodes
[Sat Mar  2 19:10:20 2019] building unitigs
[Sat Mar  2 19:10:21 2019] TOT 3915366656, CNT 79863, AVG 49027, MAX 3106816, N50 118016, L50 8300, N90 21760, L90 38196, Min 2560
[Sat Mar  2 19:10:22 2019] output "sample.frg.nodes". Done.
[Sat Mar  2 19:10:22 2019] generating links
[Sat Mar  2 19:10:23 2019] generated 63624 links
[Sat Mar  2 19:10:23 2019] output "sample.frg.dot.gz". Done.
[Sat Mar  2 19:10:23 2019] rescue 0 weak links
[Sat Mar  2 19:10:23 2019] deleted 593 binary links
[Sat Mar  2 19:10:23 2019] cut 4667 transitive links
[Sat Mar  2 19:10:23 2019] remove 1975 boomerangs
[Sat Mar  2 19:10:23 2019] detached 2565 repeat-associated paths
[Sat Mar  2 19:10:23 2019] remove 21333 weak branches
[Sat Mar  2 19:10:23 2019] cut 7241 tips
[Sat Mar  2 19:10:23 2019] pop 307 bubbles
[Sat Mar  2 19:10:23 2019] cut 597 tips
[Sat Mar  2 19:10:23 2019] output "sample.ctg.dot.gz". Done.
[Sat Mar  2 19:10:23 2019] building contigs
[Sat Mar  2 19:10:24 2019] searched 60040 contigs
[Sat Mar  2 19:10:24 2019] Estimated: TOT 3944375808, CNT 44501, AVG 88636, MAX 4039424, N50 253184, L50 3808, N90 35840, L90 21485, Min 5888
[Sat Mar  2 19:35:10 2019] output 44501 contigs
[Sat Mar  2 19:35:14 2019] Program Done
** PROC_STAT(TOTAL) **: real 3428.830 sec, user 16419.260 sec, sys 652.830 sec, maxrss 59409760.0 kB, maxvsize 96748800.0 kB

As you can see, the final genome assembly(3.9G) is much bigger than the estimated genome size(3G)
and the N50 is relatively low(~250K).

Could you give some suggest on this genome assembly ? Thanks

Best

**Comment by ruanjue** [comment]
Have you tried `wtdbg2 -p 21 -AS 2 -g 3g -L 5000`?

**Comment by bitcometz** [comment]
Thanks for your suggestion!
I replaced "-p 21" with "-p 19" and the results are not much difference from what they were before.
Indeed, this genome might be too complex to do the assembly using current sequencing techniques.
If there is a good result, I will let you know.

Thanks!

**Comment by malonge** [comment]
Your larger than expected assembly size may be the result of both haplotypes being assembled for certain loci. This is very common for highly heterozygous genomes (I'd be curious if you have an estimate of exactly how heterozygous).

There are some tools that will try to separate such "redundant" contigs:

- [Falcon Unzip](https://github.com/PacificBiosciences/FALCON_unzip) for falcon assemblies of PacBio data

- The [VCG](https://github.com/VGP/vgp-assembly/tree/master/pipeline/purge_haplotigs) has some code for this, though I have never used it.

- We developed a tool called [Pseudohaploid](https://github.com/schatzlab/pseudohaploid) which has worked for us. The method is currently under review as a part of an assembly project of a fairly heterozygous pineapple genome. 

Often, since these redundant contigs are smaller, your N50 will also increase.

**Comment by bitcometz** [comment]
Thanks for your suggestion!

I had tried Falcon Unzip and Purge Haplotigs for several projects and these methods tended to generated poor results than wtdbg. So I am not going to use them in this project.
According to my experience,  wtdbg is good at handling the problem of heterozygosity.
So I think the poor performance of this 3G genome might be due to the abundance of repetitive sequences with too complex structure.
I used GCE(https://arxiv.org/abs/1308.2012) to characterize the genome structures and the estimated 
heterozygosity rate is about 1.3%.

I will try  Pseudohaploid  with this genome and post the results once I finish the test.

Best

**Comment by malonge** [comment]
No problem! Yeah, 1.3% is pretty high. I agree that some of these repetitive plant genomes can be difficult to assemble, but I would have guessed that that explains the relatively low N50 rather than the large assembly size. Good luck!

**Comment by bitcometz** [comment]
Wonderful !!!
Thanks very much for your reminding. That it doesn't have to be reassembled really helps a lot.

Thanks!

**Comment by xiekunwhy** [comment]
> Thanks for your suggestion!
> 
> I had tried Falcon Unzip and Purge Haplotigs for several projects and these methods tended to generated poor results than wtdbg. So I am not going to use them in this project.
> According to my experience, wtdbg is good at handling the problem of heterozygosity.
> So I think the poor performance of this 3G genome might be due to the abundance of repetitive sequences with too complex structure.
> I used GCE(https://arxiv.org/abs/1308.2012) to characterize the genome structures and the estimated
> heterozygosity rate is about 1.3%.
> 
> I will try Pseudohaploid with this genome and post the results once I finish the test.
> 
> Best

Hi bitcometz,

Did you get an improved results after using Pseudohaploid?

Best,
Kun
