### ISSUE TITLE
Many erroneous 1-bp deletions

### ISSUE THREAD

**Issue by iwohlers** [ruanjue/wtdbg2#77]
Dear Jue,
We have used WTDBG (Version: 2.3 (20181206)) and WTPOA-CNS (Version: 2.3) to 
generate a human assembly from 90x PacBio data using default parmeters (wtdbg2: 
 '-x sq -g 3g'). We are very impressed by your tool, assembly took only about 
two days and assembly metrics and alignment of contigs look comparably or better
 than our previous assembly using Falcon followed by some additional polishing. 
 We observe a problem with the WTDBG2 assembly though and hope you can help!
The WTDBG2 assembly has many 1-bp deletions that are likely assembly errors. For
 an example gene, I computed and visualized the differences between assembly and
 GRCh38 and viewed this in IGV together with short-read data of the same 
individual and SNPs called from the short read data (see attached figure). The 
WTDBG2 assembly has about twice as many SNPs as the Falcon-based assembly 
(approx. 3000 instead of approx. 1500), and almost all likely erroneous 
WTDBG2-only SNPs are deletions of an indvidual base after a stretch of identical
 bases. The large number of deletions may be reflected in the length difference 
 after wtdbg2 (Estimated: TOT approx. 2,860 MB) and after wtdpoa-cns (approx. 
 2,770 MB). 
Do you have a suggestion how this can be prevented?
Thank you!
Inken

![wtdbg2](https://user-images.githubusercontent.com/14835042/53790076-4e829a80-3f26-11e9-8dab-c5d18005054f.png)

**Comment by ruanjue** [comment]
Most of the deletions are erroneous, and caused by inaccurate run length of homopolymers. As higlighted in wtpoa-cns, `Keep in mind that I am not going to generate high accurate consensus sequences here`, wtpoa-cns is a bridge between wtdbg2 and other polishers, e.g. quiver, pilon.

So, please polish the contigs using short reads. If it is possible, would you like to test the short reads polishment described in README.md of wtdbg2.
```txt
# polish contigs using short reads
bwa mem -t 16 prefix.ctg.fa sr.1.fa sr.2.fa | samtools view -Sb - >sr.bam
samtools sort sr.bam sr.srt
samtools view sr.srt.bam | ./wtpoa-cns -t 16 -x sam-sr -d prefix.ctg.fa -i - -fo prefix.ctg.3rd.fa
```
Best,
Jue

**Comment by iwohlers** [comment]
Dear Jue,
Thanks for the quick answer. So my mistake was not doing the polishing which is described in "Getting Started", I will do this now. So far I also didn't do the polishing with the PacBio reads as described in the README. So I guess I should first use wtpoa-cns with the PacBio Reads and afterwards with the short reads, i.e the steps under "# polish consensus, not necessary if you want to polish the assemblies using other tools" and then the steps under "# polish contigs using short reads"?
Thanks again,
Inken

**Comment by ruanjue** [comment]
Yes, please polish the contigs following instructions or use other tools, like quiver and pilon.

**Comment by iwohlers** [comment]
Just a quick feedback: As you said, I ran the wtpoa-cns polishing, first with 
the long reads and subsequently with the short reads. Just using the long reads 
doesn’t improve the 1bp deletion issue much, according to quast-lg about 20% 
less indels per 100kbp, but still a lot, as can be seen in the figure. The 
result after polishing additionally with the short read data is good though, 
with about 80% less indels and slightly less indels per 100 kbp than the 
alternative Falcon assembly assembly after pilon polishing. I attach the 
updated figure for a visual impression. I will continue with this assembly 
without further external polishing, I think.
![wtdbg2_with_wtpoa-cns_polishing](https://user-images.githubusercontent.com/14835042/54757461-8f4b0680-4bea-11e9-9569-608ea92553ec.png)

**Comment by ruanjue** [comment]
Thanks for the information, it is valuable for the further improvement of wtpoa-cns.
