### ISSUE TITLE
Reproducibility of results

### ISSUE THREAD

**Issue by trichoptera** [ruanjue/wtdbg2#80]
Dear Jue Ruan,

I was running wtdbg2 on the same data set with the same parameters but got slightly different assembly statistics. Is this possible? Is there an explanation for this?
Could you please also explain why wtdbg2 may produce an assembly smaller than the true genome
when using Nanopore data?

Thank you!

**Comment by ruanjue** [comment]
The step of selecting vertices from read alignments is multi-threads, thusly cause very few runtime depended differences.

wtdbg2 tends to collapse haplotypes/repeats as in de Bruijn graph. QUAST always give the lowest duplication rate to wtdbg2.

Jue

**Comment by trichoptera** [comment]
Thank you for your answer!
