### ISSUE TITLE
where is the run_wtdbg_assembly.sh script?

### ISSUE THREAD

**Issue by xiaoyezao** [ruanjue/wtdbg2#83]
Hi,
In the manual, it says use run_wtdbg_assembly.sh to generate a run.sh file. But I can not find this script.

Thanks!

**Comment by ruanjue** [comment]
wtdbg2 and wtpoa-cns are easy to run since v2.1, so this invoker is useless. please find the example in https://github.com/ruanjue/wtdbg2#getting-started . By the way, the old README-ori.md is also obsolete.
