### ISSUE TITLE
run wtdbg2 with multiple nodes in cluster

### ISSUE THREAD

**Issue by xiaoyezao** [ruanjue/wtdbg2#84]
Hi, I have a few lay questions:

Is it possible to submit wtdbg2 job to multiple nodes in the cluster?

wtdbg2 use "-i" flag to read in the input files, and i need to list a lot of subreads files one by one after "-i". Are there any easier ways to do this? It's painful to list one by one, as I have dozens of subreads files.

Thanks

**Comment by ruanjue** [comment]
There is a closed issue about how to run wtdbg2 on parallel nodes.

`wtdbg2 [option] *.fa` will treat all the .fa files as input.
