### ISSUE TITLE
error: Segmentation fault

### ISSUE THREAD

**Issue by xiaoyezao** [ruanjue/wtdbg2#85]
Hi,

I am running wtdbg2 on a 1.4G plant genome. The command is: `yhrun -n 1 -N 1 -p test ./wtdbg2 -x sq -t 0 -i *.gz -o rheum`

I got the error message: `1yhrun: error: cn13122: task 0: Segmentation fault`

What's going wrong here?

Thanks.

**Comment by ruanjue** [comment]
```sh
make wtdbg2 DEBUG=1
gdb ./wtdbg2
gdb> run -x sq -t 0 -i *.gz -fo rheum
**** when seg fault ****
gdb> bt
```

**Comment by xiaoyezao** [comment]
> ```shell
> make wtdbg2 DEBUG=1
> gdb ./wtdbg2
> gdb> run -x sq -t 0 -i *.gz -fo rheum
> **** when seg fault ****
> gdb> bt
> ```

Thank you very much for this. It's successfully running now!
Can you please explain a little bit about this? I want to know what's going on with these few commands.

Thanks

**Comment by ruanjue** [comment]
The above commands are for debuging, but no seg fault found. Try compile wtdbg2 in normal way, and execute it directly without `yhrun`, I am not familiar with it.
