### ISSUE TITLE
out of memory ?

### ISSUE THREAD

**Issue by xiaoyezao** [ruanjue/wtdbg2#87]
Hi,
I am running wtdbg2 on a 24-core node:

-- total memory      132009044.0 kB
-- available         130766524.0 kB
-- 24 cores
-- Starting program: /BIGDATA1/wbgcas_tfeng_1/app/wtdbg2//wtdbg2 -x sq -t 0 -i *.gz

after the stage "scanning kmers", the program exits reporting: 

[Tue Mar 19 21:06:42 2019] - high frequency kmer depth is set to 3970
 -- Out of memory, try to allocate 107374182400 bytes, old size 256, old addr 0x226bc50 in encap_list -- mem_share.h:219 --

however, the suggested memory " 107374182400 bytes " does not exceed the node memory.

what's going wrong here?

**Comment by ruanjue** [comment]
Program try to alloc addtional 100G RAM.
