### ISSUE TITLE
assembly with "-B 384"

### ISSUE THREAD

**Issue by bitcometz** [ruanjue/wtdbg2#88]
Hello,

I try to run the kbm2 with the parameters "-B 384".
Do I need to adjust the related parameters in the assembly process of wtdbg?
Thanks!

Best,

**Comment by ruanjue** [comment]
Seeds within a BIN cannot exceed 256, -B 384 is weird. Anyway, you needn't adjust related parameters in wtdbg2.

**Comment by bitcometz** [comment]
Oh, that is my misunderstanding.
Since wtdbg2 did nor worked well for my repetitive plant genome, I want to increase the size of a BIN.
So the size of a BIN is fixed,  Is there a way to change it? to increase to 512?
Bigger bins might solve more repeat structure.

Thanks!

**Comment by ruanjue** [comment]
BIN size is defined as a const value. Have a try with `-l`, `-m`, `--node-matched-bins`.

**Comment by bitcometz** [comment]
Thanks!

These parameters didn't work well for my project.
With the same data, Falcon can archive better N50 and total assembly size.
So I guess there should be much improvement room for wtdbg2 on repetitive plant genomes, such as maize, rape et al.

Best,
