### ISSUE TITLE
Consenser reduces the expected genome size?

### ISSUE THREAD

**Issue by harish0201** [ruanjue/wtdbg2#89]
Hi,

I have been running the wtdbg2 for a 2.4Gb genome and I'm curious about how the consensus works. I'm attaching the last few lines from wtbdg2:

[Sat Mar 23 01:15:54 2019] Estimated: TOT 1960930048, CNT 12279, AVG 159698, MAX 8510976, N50 1075200, L50 481, N90 92416, L90 2733, Min 5120
[Sat Mar 23 01:23:40 2019] output 12279 contigs
[Sat Mar 23 01:23:50 2019] Program Done
** PROC_STAT(TOTAL) **: real 226690.564 sec, user 12656029.450 sec, sys 35287.640 sec, maxrss 258557952.0 kB, maxvs

However, on running the tool wtpoa-cns to derive the consensus as has been written in the README. I have subsequently derived the stats:
num_seqs        2168
sum_len 1550431256
min_len 10781
avg_len 715143.6
max_len 7837267
IQR1      227474
IQR2      414700
IQR3      896727
N50     1201053

I'm curious as to why the genome-size reduces on running the consenser, because this seems to be like a reduction of 20%. Is there any way to retain all the data from the layout that the consenser uses?

**Comment by ruanjue** [comment]
Error correction on edges will remove INDELs, which most composed of insertion, thus decrease the contigs' length. However, failed in error correction may rarely lose some edges. In your case, the total size decrease so much, please check the lay file and final cns.fa file, were there some contigs lost, or decrease too much in length. If you find some unusual, I would like to get the contig layout and test in my computer.

Best,
Jue

**Comment by harish0201** [comment]
Sure, I can share the layout file, however its around 21gb compressed. Would you be having a write-only location so that I can ftp you that? However, in the meantime please let me know what I should be looking around in the layout file to get an idea.

**Comment by ruanjue** [comment]
I meant share the layout of some problematic contigs, not all contigs. Please see https://github.com/ruanjue/wtdbg2/blob/master/README-ori.md for the format of layout.

**Comment by harish0201** [comment]
All right thank you for the help! Meanwhile I'm also running wtpoa-cns as an alternative to see what issue is actually arising.

wtpoa-cns seems to output all the contigs though, so I'm going to have to sift through this. Would you recommend doing this?

**Comment by ruanjue** [comment]
You can split the layout file by contig, then the test will be easy.

**Comment by chen5864647** [comment]
There is no comment!!

**Comment by harish0201** [comment]
Sorry, I was a bit busy since the past few days, so I have to check up on the results.

I will get back soon.

**Comment by chen5864647** [comment]
I'm a student yet.
Don't take it seriously.

Harish <notifications@github.com> 于2019年4月2日周二 下午12:32写道：
