### ISSUE TITLE
wtdbg2 stagnate at the sorting stage?

### ISSUE THREAD

**Issue by xiaoyezao** [ruanjue/wtdbg2#92]
Hi, I am rnning wtdbg2 on canu corrected pacbio reads. It takes about two hours to get to the **sorting** stage and then seems to have stagnated there for 7 hours up to now. Nothing changed in the log file for the past seven hours. Because I submitted the job to cluster, I am not sure whether it's still running, or I should kill the job.

the last lines of the log are: 
[Fri Mar 29 13:18:55 2019] - indexed  37903968 kmers, 904259273 instances
[Fri Mar 29 13:19:03 2019] - masked 3777124 bins as closed
[Fri Mar 29 13:19:03 2019] - sorting
** PROC_STAT(0) **: real 5590.962 sec, user 2448.800 sec, sys 3133.670 sec, maxrss 9736684.0 kB, maxvsize 13504296.0 kB
[Fri Mar 29 13:24:09 2019] Done

**Comment by ruanjue** [comment]
The next step of this job should be alignment, please have a look whether <prefix>.alignments file exists. You'd better to run it again.

**Comment by xiaoyezao** [comment]
Hi ruanjue, I run it again and this time it finished the alignment, but exited at `generating regs` step because of memery shortage. I try to allocate more memory and run it again. Is it possible to resume the process from the `generating regs` step?

**Comment by ruanjue** [comment]
Have a look at `wtdbg2 --help` for the option `--load-alignments`.

**Comment by xiaoyezao** [comment]
Thanks, that works
