### ISSUE TITLE
Suggestions for mixed ont+pacbio 

### ISSUE THREAD

**Issue by apredeus** [ruanjue/wtdbg2#94]
Hello, 

I was wondering what sort of settings would you suggest using for a mixed dataset of ~ 50x PacBio and ~20x (much longer) Nanopore reads, on a 650 mb genome? Thank you!

**Comment by ruanjue** [comment]
`-x sq` should be better than `-x ont`.

**Comment by macarima** [comment]
I have tried with PacBio and Nanopore, but in my case.... the result was not better than PacBio only.
Processing of assembly with pacbio and scaffolding with nanopore can be a good option.
You may use LINKS for scaffolding.
