### ISSUE TITLE
Large difference in total assembly size with PacBio error correction

### ISSUE THREAD

**Issue by evolgen** [ruanjue/wtdbg2#96]
Hi Jue,

Thanks for the awesome tool. I have been using it to generate assemblies for PacBio data of fishes. However, there are differences in assembly sizes with and without PacBio correction. There are the estimates along with their kmer spectra -
1) Without PacBio correction : -p 21 -K 1000.049988 -A -S 2.000000 -s 0.050000 -g 1000000000 -X 50.000000 -e 3 -L 5000
Quatiles:
   10%   20%   30%   40%   50%   60%   70%   80%   90%   95%
     2     4     6     9    14    19    26    42   142   729
TOT 824091392, CNT 982, AVG 839197, MAX 32493312, N50 13875968, L50 19

2) Using a kmer of 19 changes the spectra as follows, but assembly size remains similar
Quatiles:
   10%   20%   30%   40%   50%   60%   70%   80%   90%   95%
    16    28    41    58    79   107   147   228   583  2064
TOT 809877248, CNT 1549, AVG 522839, MAX 27841792, N50 7682304, L50 26

3) PacBio corrected using canu : -p 21 -K 0.050000 -A -S 1.000000 -s 0.500000 -g 0 -X 50.000000 -e 3 -L 5000
Quatiles:
   10%   20%   30%   40%   50%   60%   70%   80%   90%   95%
    29    37    41    45    49    57    88   164  1163  6607
TOT 726574592, CNT 1151, AVG 631256, MAX 28809472, N50 7465472, L50 25

I tried different values of K,p,S and these were the best ones selected in terms of contiguity. 

The assembly estimates from falcon assembler are -
TOT 1446944912, CNT 2657, MAX 6301574, N50 2489382, L50 117

We do not have a genome size estimate for the same species, but flow cytometry data of other related species indicate a genome size of 920-970 Mb. 
The estimated heterozygosity is 0.25% with the error corrected data, is there a reason for ~14% change in assembly size while using error corrected data?

**Comment by ruanjue** [comment]
I am not sure. The error correction may collapse similar genomic regions. Since you have got good enough assembly metric, the next step might be comparing two assemlies in structure accuracy, then choose one for further polishing.

**Comment by evolgen** [comment]
I was comparing these assemblies - the assembly with falcon too was 800Mb, in addition to 300Mb associated contigs. I guess I will go with the error corrected ones since their BUSCOs are highest. Thanks for the help
