### ISSUE TITLE
different result between version 2.3 and 2.4

### ISSUE THREAD

**Issue by bjmiao** [ruanjue/wtdbg2#99]
Dear @ruanjue ,
I tried version 2.3 (the released version) and the version 2.4 (latest, source code version), and it seems that the result in some examples are not the same.

Take [D. melanogaster ISO1](https://www.ebi.ac.uk/ena/data/view/SRR6702603) as an example, I use the recommended running-flag:

> ./wtdbg2 -xont -g144m -t0 -i ${INPUT_PATH} -fo ${PREFIX}
> ./wtpoa-cns -t0 -i ${PREFIX}.ctg.fa.gz -fo ${RESULT}

both in v2.3 and v2.4.

And here's the result of ${RESULT} (by bio-info stat tool):
v2.3

num_seqs | sum_len     | min_len | avg_len | max_len   | Q1    | Q2     | Q3     | sum_gap | N50       | Q20(%) | Q30(%) |
----------|-------------|---------|---------|-----------|-------|--------|--------|---------|-----------|--------|--------|
1,092    | 139,499,704 | 2,340   | 127,747 | 6,294,513 | 6,875 | 12,721 | 31,542 | 0       | 1,347,176 | 0      | 0      |

v2.4

num_seqs | sum_len     | min_len | avg_len   | max_len    | Q1    | Q2     | Q3     | sum_gap | N50       | Q20(%) | Q30(%) |
-----------|-------------|---------|-----------|------------|-------|--------|--------|---------|-----------|--------|--------|
|  975     | 138,735,138 | 3,132   | 142,292.4 | 10,033,852 | 6,719 | 12,843 | 35,193 | 0       | 1,579,807 | 0      | 0      |

There seems a gap between them, especially the N50 and the number of sequences. (And I also observed that v2.4 is a little bit faster than v2.3 in general)

I wonder, which one is correct(or better)? Is the result of v2.4 reliable? Thank you.

Best regards,
bjmiao

**Comment by ruanjue** [comment]
Both should be correct, QUAST or other tools can give the evaluation. In genome assembly, those differences on number are accepted, don't warry.

**Comment by bjmiao** [comment]
Great! Thanks so much.
